### ISSUE TITLE
How to describe Children?

### ISSUE THREAD

**Issue by just-boris** [JetBrains/kotlin-wrappers#10]
I have the following code:

```kt
class App : RComponent<RProps, RState>() {
    override fun RBuilder.render() {
        div {
            Panel {
                div { +"Line 1" }
                div { +"Line 2" }
            }
        }
    }
}
```

I want to create my custom React Component called `Panel` to accept children, like the following JSX

```jsx
<Panel>
  <div>Line 1</div>
  <div>Line 2</div>
</Panel>
```

How should I describe `Panel` component in Kotlin to make children accessible?

**Comment by just-boris** [comment]
So far I have come up with the following implementation

```
package components

import react.*
import react.dom.*

fun RBuilder.Panel(children: RBuilder.() -> Unit) {
    div("panel") {
        buildElements(children)
    }
}
```

This code seems to accept children, but it doesn't emit them out. What have I missed? Any pointers will be appreciated.

**Comment by Hypnosphi** [comment]
In your example, it should be just
```js
fun RBuilder.Panel(children: RBuilder.() -> Unit) {
    div("panel") {
        children()
    }
}
```

**Comment by just-boris** [comment]
That indeed works! Thank you!
