### ISSUE TITLE
'background' in the `style` modifier of HTML elements

### ISSUE THREAD

**Issue by akuleshov7** [JetBrains/kotlin-wrappers#1003]
I have the following HTML code that I would like to use in KotlinJS:
```
<div style="background: -webkit-linear-gradient(270deg, rgb(84, 83, 97), rgb(25, 34, 99), rgb(49, 70, 180));" class="page-header align-items-start min-vh-100"></div></div>
```

It adds `style` modifier to the `div` tag. Is there any way to provide `background` attribute to this style modifier?

The following code does not work:

```
 div("page-header align-items-start min-vh-100") {
                attrs.style = kotlinext.js.js {
                    background = "-webkit-linear-gradient(270deg, rgb(84, 83, 97), rgb(25, 34, 99), rgb(49, 70, 180));"
                }
            }
```

**Comment by turansky** [comment]
You can use `react.dom.html.ReactHML.div` to solve this problem:

```kotlin
import react.dom.html.ReactHML.div

div {
    attrs {
        className = "page-header align-items-start min-vh-100"
        style = jso {
            background = linearGradient("270deg, rgb(84, 83, 97), rgb(25, 34, 99), rgb(49, 70, 180)")
        }
    }

// coming soon in wrappers    
inline fun linearGradient(
    source: String,
): Background =
    "-webkit-linear-gradient($source)".unsafeCast<Background>()    
```

**Comment by akuleshov7** [comment]
@turansky do I need any imports for `background`?

**Comment by turansky** [comment]
`CSSProperties` already contains this property
No import required  ([example](https://github.com/karakum-team/kotlin-react-table-sample/blob/31732f018f3ba49d113883e6988494d91c39dc09/src/main/kotlin/component/Header.kt#L18))

<img width="365" alt="Screen Shot 2021-12-01 at 7 16 14 PM" src="https://user-images.githubusercontent.com/9942723/144271543-db578907-4258-49b8-89dc-d06805c2e448.png">

Valid `div` is violet :)
<img width="110" alt="Screen Shot 2021-12-01 at 7 21 07 PM" src="https://user-images.githubusercontent.com/9942723/144272042-a3e0fab8-b282-40f2-831c-b0e6c74e14f9.png">

**Comment by turansky** [comment]
@akuleshov7 Problem solved?

**Comment by akuleshov7** [comment]
@turansky unfortunately no, could you please provide the library (gradle dependency) that you are importing (kotlinReact)

**Comment by akuleshov7** [comment]
I am using the following div: 
https://github.com/diktat-static-analysis/save-cloud/blob/master/save-frontend/src/main/kotlin/org/cqfn/save/frontend/components/views/FallbackView.kt

**Comment by turansky** [comment]
Invalid - `import react.dom.div`
Valid - `react.dom.html.ReactHTML.div`

**Comment by akuleshov7** [comment]
> Invalid - `import react.dom.div`
> Valid - `import react.dom.html.ReactHTML.div`

I understand it, but that lib is missing in the `react.dom` that I am importing: https://github.com/diktat-static-analysis/save-cloud/blob/acc7411fffd6bc85057b84389114569741634a43/save-frontend/build.gradle.kts

**Comment by turansky** [comment]
[Latest](https://github.com/JetBrains/kotlin-wrappers/releases/tag/pre.274) will be fine

**Comment by akuleshov7** [comment]
Found much easiest solution without a migration to other `div` and simple usage of `import react.dom.div`:
```
import react.CSSProperties
import react.dom.div

            div("page-header align-items-start min-vh-100") {
                attrs["style"] = jsObject<CSSProperties> {
                    background = linearGradient("270deg, rgb(84, 83, 97), rgb(25, 34, 99), rgb(49, 70, 180)")
                }
            }
```
