### ISSUE TITLE
kotlin-react-router-dom how to add to the app

### ISSUE THREAD

**Issue by PaulienVa** [JetBrains/kotlin-wrappers#102]
What is the exact syntax to add the router into your app?
I now have this method describing my router:
```
fun RBuilder.router(): ReactElement {
        return hashRouter {
            // or "browserRouter"
            switch {
                route("products", Products::class, exact = true)
                route("contact", Contact::class, exact = true)
            }
        }

    }
```

And I really try to integrate it at this level, but I can't seem to find the right syntax:

```

    render(document.getElementById("root")) {
        app()
    }
```

**Comment by geisterfurz007** [comment]
Can't you just replace `app()` with `router()`?

**Comment by PaulienVa** [comment]
I can, but where do I leave my app() declaration?

**Comment by Leonya** [comment]
Just put them next to each other, why not?

**Comment by PaulienVa** [comment]
Putting them like this next to each other:
```
render(document.getElementById("root")) {
        router()
        app()
    }
```
Will still end-up in the error:
`You should not use <Route> or withRouter() outside a <Router>`

When adding my menu implemented as follows:
```
class NavigationMenu : RComponent<RProps, RState> () {
    override fun RBuilder.render() {
        nav(classes = "Navigation-Header") {
            ul {
                li(classes = "Navigation-Text") {
                    navLink(to = "products", className = "products") {}
                    +"Products"
                }


            }
        }
        }
}
```

I am bit confused on what is not working there

**Comment by thorakmedichi** [comment]
@PaulienVa here is what I did to get this working

App.kt
```
package app

import react.*
import react.dom.*
import react.router.dom.*
import react.redux.*

import header.*
import sidebar.*
import screens.*

class App : RComponent<RProps, RState>() {
    override fun RBuilder.render() {
        sidebar()

        div("wrapper"){
            header()

            browserRouter { // "browserRouter" or "hashRouter"
                switch {
                    route("/", IndexScreen::class, exact = true)
                    route("/redux", ReduxScreen::class, exact = true)
                    route("/test") {
                        p{
                            +"Test Screen for closure function"
                        }
                    }
                }
            }
        }
    }
}

fun RBuilder.app() = child(App::class) {}
```

Sidebar.kt
```
package sidebar

import react.*
import react.dom.*

fun RBuilder.sidebar() {
    div("sidebar"){
        a{
            attrs.href = "/"
            +"Home"
        }
        a{
            attrs.href = "/redux"
            +"Redux"
        }
        a{
            attrs.href = "/test"
            +"Test"
        }
    }
}
```

**Comment by ericwdq** [comment]
@thorakmedichi , I had a try on kotin-react app , I think the sidebar() should inside "browserRouter" or "hashRouter", otherwise app will throws error:  Error: Invariant failed: You should not use <Link> outside a <Router>
`
class App : RComponent<RProps, RState>() {
    override fun RBuilder.render() {
        div("wrapper"){
            header()

            browserRouter { // "browserRouter" or "hashRouter"
               sidebar() 
               switch {
                    route("/", IndexScreen::class, exact = true)
                    route("/redux", ReduxScreen::class, exact = true)
                    route("/test") {
                        p{
                            +"Test Screen for closure function"
                        }
                    }
                }
            }
        }
    }
}
`

**Comment by ojaynico** [comment]
@ericwdq Using **routerLinks** inside the **browserRouter** worked for me too.
