### ISSUE TITLE
Using JS Set in wrappers

### ISSUE THREAD

**Issue by Neitex** [JetBrains/kotlin-wrappers#1044]
As Kotlin/JS documentation states, Kotlin Set does not map to JS Set (and vice versa), which creates troubles in creating wrappers for JS libraries that use JS Set (i.e. Ring UI Table component,  #1042). There is a workaround to also create wrapper for JS Set itself, but it seems like a bad idea.

Any ideas on how to do it better way?

**Comment by Neitex** [comment]
So any suggestions or ideas on what to do? Any comments from maintainers team? It seems like this is a common question/problem/issue.

**Comment by turansky** [comment]
> So any suggestions or ideas on what to do?

Research required before for fine solution

From TypeScript compiler (#1137):
https://github.com/karakum-team/types-kotlin/commit/782b67452bcc7d806b34326538a0a609688364f9

cc @sgrishchenko

**Comment by turansky** [comment]
@Neitex Now we have `JsIterator` in `kotlinx.js` package
Could you add `JsSet` in the same package?

**Comment by Neitex** [comment]
> @Neitex Now we have `JsIterator` in `kotlinx.js` package Could you add `JsSet` in the same subproject/package?

Sure :)
Is there anything else needed? Can we freely implement new wrappers already? :)

**Comment by turansky** [comment]
> Can we freely implement new wrappers already? :)

Which subproject do you mean?

**Comment by Neitex** [comment]
I've taken a goal to wrap most of Ring UI, so kotlin-ring-ui

**Comment by turansky** [comment]
FYI - beta version already contains [typings](https://unpkg.com/browse/@jetbrains/ring-ui@5.0.0-beta.16/components/alert/)

**Comment by turansky** [comment]
Solved in #1200

cc @Leonya
