### ISSUE TITLE
New ChildrenBuilder breaking React.Children.only

### ISSUE THREAD

**Issue by PeredurOmega** [JetBrains/kotlin-wrappers#1062]
It seems like `Children.only` does not work anymore with `ChildrenBuilder`.
Indeed, instead of an opaque structure, `PropsWithChildren` now has an `Array` for `children`, which cause `Children.only` to always fail.

This failure can be understood through the reading of its [implementation](https://github.com/facebook/react/blob/main/packages/react/src/ReactChildren.js#L313-L335) which depends on [isValidElement](https://github.com/facebook/react/blob/main/packages/react/src/ReactElement.js#L559-L572).

As a workaround I now use:
```kotlin
const val ReactOnlyChildError = "React.Children.only expected to receive a single React element child"

fun onlyChild(children: ReadonlyArray<ReactNode>?): ReactElement {
    if ((children?.size ?: 0) > 1) error("$ReactOnlyChildError (more than one were provided).")
    return children?.getOrNull(0)?.asElementOrNull() ?: error("$ReactOnlyChildError (none were provided).")
}
```

However, maybe `Children.only` should be removed and replaced by a working usage (such as the one above).
I also wonder if there are other cases where the new `ChildrenBuilder` breaks functions provided by `React`.

**Comment by turansky** [comment]
Do you have short example for problem reproducing?

**Comment by PeredurOmega** [comment]
```kotlin
val example = FC<Props> {
    parentWithOnlyChild {
        onlyChild { }
    }
}

val parentWithOnlyChild = FC<PropsWithChildren> { props ->
    val test = 0
    child(cloneElement(Children.only(props.children), jso<TestProps> {
        number = test
    }))
}

val onlyChild = FC<TestProps> { props ->
    h1 {
         +props.number
    }
}

external interface TestProps: Props {
    var number: Int
}
```

This code was working on react-legacy, works in react JS and is always failing with the new `ChildrenBuilder`.

**Comment by turansky** [comment]
Unary plus declared for `String` only
In both builders
IDEA highlight this problem

Works fine with following
```kotlin
val onlyChild = FC<TestProps> { props ->
    h1 {
         +props.number.toString()
    }
}
```

<img width="556" alt="Screenshot 2021-12-21 at 11 50 37" src="https://user-images.githubusercontent.com/9942723/146900213-cd18c222-90a7-4ac7-ba48-22376ad89560.png">

**Comment by turansky** [comment]
Was it your local extension? :)

**Comment by PeredurOmega** [comment]
Thanks @turansky, I just tested myself and it's working, sorry for the trouble.

In fact, my error was coming from the fact that I did not realize I was directly passing `children` (not using `ChildrenBuilder`).
Indeed, I was passing an `arrayOf` of a single `ReactElement`, but doing the following instead works:
```kotlin
myComp {
     children = createElement(myOnlyChild, myOnlyChildProps).unsafeCast<ReadonlyArray<ReactNode>>()
}
```

FYI, I was doing so because I can't figure out how to have generic functional components working the same way as their non-generic counterpart.

```kotlin
fun <T> ChildrenBuilder.monitor(handler: MonitorProps<T>.() -> Unit) =
    child(InternalMonitor.unsafeCast<FC<MonitorProps<T>>>(), jso(handler))

private val InternalMonitor: FC<MonitorProps<Any?>> = FC("Monitor", ChildrenBuilder::monitor)

private fun <T> ChildrenBuilder.monitor(props: MonitorProps<T>) {
    // ...
}

external interface MonitorProps<T> : PropsWithChildren {
    // ...
}
```

Is there any alternative to:
```kotlin
fun <T> ChildrenBuilder.monitor(handler: @ReactDsl ChildrenBuilder.(MonitorProps<T>) -> Unit) {
    InternalMonitor {
        handler(this.unsafeCast<MonitorProps<T>>())
    }
}
```
or to
```kotlin
fun <T> ChildrenBuilder.monitor(handler: @ReactDsl MonitorProps<T>.() -> Unit) =
    child(InternalMonitor.unsafeCast<FC<MonitorProps<T>>>(), jso(handler))
```
which could help me to use a handler with  two receivers (`ChildrenBuilder` and `MonitorProps`) ?

**Comment by turansky** [comment]
Usually I use similar:
```kotlin
private val Body by FC<BodyProps<*>>  = ...

fun <D : Any> ChildrenBuilder.Body(
    block: BodyProps<D>.() -> Unit,
) {
    child(Body, jso(block))
}
```

With `*` no `unsafeCast` required

**Comment by PeredurOmega** [comment]
Ok but this way we can't use `ChildrenBuilder` to add children, can we ?

I think the code below would not work:
```kotlin
Body {
    bodyText = "Text"
    h1 {
        +"Example"
    }
    h2 {
        +"Example2"
    }
}
```

**Comment by turansky** [comment]
You are right
Fine solution for case with `children` - open question

Final goal - avoid redundant helper at all

**Comment by turansky** [comment]
Example with `children` support - [Autocomplete](https://github.com/karakum-team/mui-kotlin/blob/fc24a44acf724f59a316e2c3af482b50bf1c056b/local-server/src/main/kotlin/MyAutocomplete.kt#L10)

But with suppress :(

**Comment by PeredurOmega** [comment]
Thanks @turansky, this is an interisting example (it would be awesome without the suppress).

In this example, I also see that you use the [render props](https://reactjs.org/docs/render-props.html) technique instead of `children`.
Using only [render props](https://reactjs.org/docs/render-props.html) and no `children` for generic component with a helper function like [this](https://github.com/JetBrains/kotlin-wrappers/issues/1062#issuecomment-998753140) could be a workaround.
Would you recommend it as a workaround for now ?

**Comment by turansky** [comment]
It depends on your component - no silver bullet.

**Comment by turansky** [comment]
Since  `pre.283` `children` is `ReactNode`
