### ISSUE TITLE
Invalid property id in new kotlin-react-dom

### ISSUE THREAD

**Issue by PeredurOmega** [JetBrains/kotlin-wrappers#1077]
When executing `processDceKotlinJs` on a project using `kotlin-react-dom` `284` I now have an error `invalid property id`.

It seems due to the fact that JS reserved keywords are used in `@JsName` of some of the generated enum I use.

For my specific case, it comes from [Capture](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-dom/src/main/generated/react/dom/html/Capture.kt#L7) using `false` and `true` and [AriaRole](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-dom/src/main/generated/react/dom/aria/AriaRole.kt) using `switch`.

Changing Capture like below solved the issue:
```kotlin
@Suppress("NAME_CONTAINS_ILLEGAL_CHARS")
// language=JavaScript
@JsName("""(/*union*/{"false": 'false', "true": 'true', user: 'user', environment: 'environment'}/*union*/)""")
external enum class Capture {
    `false`,
    `true`,
    user,
    environment
    ;
}
```

Therefore, [JS reserved keywords](https://www.w3schools.com/js/js_reserved.asp) should probably be handled differently (e.g. by wrapping them with quotes).

**Comment by turansky** [comment]
Legacy compiler?

**Comment by PeredurOmega** [comment]
Yes, using the legacy compiler.

**Comment by turansky** [comment]
Could you try [this plugin](https://plugins.gradle.org/plugin/com.github.turansky.kfc.legacy-union) to solve problem?

**Comment by PeredurOmega** [comment]
Thanks, it's working perfectly.

**Comment by turansky** [comment]
Latest plugin version (with new group id):
`id("io.github.turansky.kfc.legacy-union") version "5.8.0"`
