### ISSUE TITLE
React: syntax to give existing Props object without calling 'child'

### ISSUE THREAD

**Issue by CLOVIS-AI** [JetBrains/kotlin-wrappers#1121]
With the new syntax, we can use:
```kotlin
SomeComponent {
  prop1 = "Hello"
  prop2 = "World"
}
```

However, we can't pass props directly. To my knowledge, this is the only way:
```kotlin
child(SomeComponent, props)
```

I think it would be better for syntax to add the following function to `ChildrenBuilder`:
```kotlin
operator fun <P : Props> ElementType<P>.invoke(props: P) {
    +createElement(this, props)
}
```
to allow this syntax:
```kotlin
SomeComponent(props)
```

**Comment by aerialist7** [comment]
Hi @CLOVIS-AI,

`ChildrenBuilder` already has `+` operator for these needs
See https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt#L17

Here you can find examples of usage this operator in my project
https://github.com/karakum-team/kotlin-react-table-sample/blob/main/src/main/kotlin/example/component/UserTable.kt#L62

**Comment by CLOVIS-AI** [comment]
I see. That's easy to read, but it's not really easy to find its existence.

I'll let you decide whether you want to close this or support both syntaxes.

**Comment by turansky** [comment]
```kotlin
operator fun <P : Props> ElementType<P>.invoke(props: P) {
    +createElement(this, props)
}
```

Such signature conficts with existed [`invoke`](https://github.com/JetBrains/kotlin-wrappers/blob/f46a1a966ce70c73553e7139590eed435da76234/kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt#L50) - that is why it was't added :(

**Comment by CLOVIS-AI** [comment]
> Such signature conficts with existed [`invoke`](https://github.com/JetBrains/kotlin-wrappers/blob/f46a1a966ce70c73553e7139590eed435da76234/kotlin-react/src/main/kotlin/react/ChildrenBuilder.kt#L50) - that is why it was't added :(

Why does it? Mine uses a normal props object, whereas the other is a lambda. It should be rare that a Props object is a lambda?

**Comment by turansky** [comment]
> Why does it?
It's because we have `Props` as input argument (`in` position)

Also important - such signature can lock future changes/more effective solutions (research required)
