### ISSUE TITLE
React: tutorial is out of date

### ISSUE THREAD

**Issue by CLOVIS-AI** [JetBrains/kotlin-wrappers#1122]
The Kotlin React tutorial uses the legacy syntax: https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/02_Setting_up

**Comment by aerialist7** [comment]
✓

**Comment by aerialist7** [comment]
Moved to https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle/issues/16
