### ISSUE TITLE
Android examples using kotlin-wrappers like kotlin-redux

### ISSUE THREAD

**Issue by ts25504** [JetBrains/kotlin-wrappers#114]
There are many front-end libs like redux writing for android development.
for example https://github.com/freeletics/RxRedux and https://github.com/ReKotlin/ReKotlin
Is it possible providing some android examples using kotlin-wrappers.

**Comment by lawik123** [comment]
I might have misunderstood your question, but, these wrappers are for JavaScript libraries, you can't apply these to Android. The libraries you linked should be compatible with Android already, the ReKotlin library even has an Android example.

**Comment by ts25504** [comment]
Alright, Thank you.
