### ISSUE TITLE
StyledButton

### ISSUE THREAD

**Issue by DryDoge** [JetBrains/kotlin-wrappers#1143]
Hello,

I have problem with creating StyledButton in Kotlin/JS project.

I did this:
`
styledButton {
                        css {
                            backgroundColor = Color("#fff")
                            color = Color("#aaa")
                            border = "none"
                            cursor = Cursor.pointer
                            padding = "15px"
                            fontSize = LinearDimension("16px")
                            hover { color = Color("#222") }
                            focus { outline = Outline.none }
                            position = Position.absolute
                            left = LinearDimension("35%")
                            top = LinearDimension("50%")
                            zIndex = 100
                            borderTopLeftRadius = LinearDimension("5px")
                            borderBottomLeftRadius = LinearDimension("5px")
                            transform { translateX(LinearDimension("-100%")) }
                        }
                        i {
                            +"Down"
                        }
                    }
        `

But i don't know how to add eventListener to this button. 
Can you help me ? 

Thank you very much.

**Comment by turansky** [comment]
* [Using legacy wrappers](https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/04_Making_It_React)
* [Using new wrappers](https://github.com/karakum-team/kotlin-react-table-sample/blob/9d6fbf38f2c03a9612432ef0e3c189ba3583a0ea/src/main/kotlin/example/component/UserTable.kt#L125)

**Comment by DryDoge** [comment]
Thank you for your response.

What do you mean by new wrappers? It is already  "stable"?

**Comment by turansky** [comment]
> What do you mean by new wrappers? It is already "stable"?

It's current default preset ([since `pre.282`](https://github.com/JetBrains/kotlin-wrappers/blob/master/CHANGELOG.md#pre282))
[Example project](https://github.com/karakum-team/kotlin-react-table-sample)

**Comment by DryDoge** [comment]
Oh, it looks nice ... also a lot of examples use react and I just want to use "plain HTML and CSS". It is better to use new wrappers even for this case  or it don't matter ?

**Comment by turansky** [comment]
It depends on your case. It will be more productive to ask this question in Slack with more detailed description

**Comment by DryDoge** [comment]
Ok, thank you for your help. 💯
