### ISSUE TITLE
Support for Hooks. (useState, useEffect)

### ISSUE THREAD

**Issue by ddeya** [JetBrains/kotlin-wrappers#116]
I think you should support this new feature calls 'hooks'.
https://reactjs.org/docs/hooks-intro.html
If you are already working on it, let me now. :)

**Comment by fletcher91** [comment]
https://github.com/JetBrains/kotlin-wrappers/issues/108#issuecomment-491585903 implies they're planning on adding them

**Comment by Leonya** [comment]
Yes, we are, but it's not the top item on the to-do list, to be honest.

**Comment by Leonya** [comment]
The hooks are now available (version `pre.79`), please give a big round of applause to @Skolotsky 👏👏👏

**Comment by tristancaron** [comment]
Thanks! Any example of how to use them?

**Comment by NorbertSandor** [comment]
> Thanks! Any example of how to use them?

I found this example: https://github.com/JetBrains/kotlin-wrappers/issues/127#issuecomment-516328066
