### ISSUE TITLE
kotlin-react: clarify whether and how server-side rendering can be arranged

### ISSUE THREAD

**Issue by dvoytenko** [JetBrains/kotlin-wrappers#1165]
All examples and docs that I could find describe the client-side rendering. But can the same components be server-side rendered? I see the corresponding imports from the JS modules (https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-dom/src/main/kotlin/react/dom/server/Imports.kt), but it looks like these are for server-side JVM execution?

**Comment by sgrishchenko** [comment]
To be honest, we don't have a lot of users who use kotlin-react for server side rendering, you need some typings for nodejs (and maybe for some server side framework, like express) to implement such a thing, you can try to use [these definitions](https://github.com/Kotlin/kotlinx-nodejs).
Functions, declared in `server/Imports.kt`, are a simple port of [typescript version](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dom/server.d.ts). They are added as experiment and probably will be changed with more strict types.
If you have some examples of server side rendering, we are open for PRs.
Thank you for feedback and notice.

**Comment by Leonya** [comment]
The presence of these types doesn't mean anything, it was never tested, as far as I know.
