### ISSUE TITLE
Support for Hover class, and Image class

### ISSUE THREAD

**Issue by nickmitchell98** [JetBrains/kotlin-wrappers#117]
I am currently building a web app, I have tried modifying the gradles, importing different classes, and even routing to the root file. The image still doesn't show, and the hower the class does not work for links. 
According to multiple websites the hover class is nested within the a(link) class
a {
hover { ]
}
Thank you!

**Comment by Leonya** [comment]
No, it doesn't work like that. Please try using kotlin-styled instead: https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-styled
