### ISSUE TITLE
Overloadable React components

### ISSUE THREAD

**Issue by just-boris** [JetBrains/kotlin-wrappers#12]
JSX allows us to pass either string or another JSX element into attribute. Both options bellow are valid

```jsx
<Container header="My header" />
<Container header={<h1>My header</h1>} />
```

I wanted to achieve the same effect in the Kotlin code:

```kt
Container(header = "My header")
Container(header = { h1 { +"My header" }})
```

I managed to make it work via two overloaded functions

```kt
fun RBuilder.Container(header: RBuilder.() -> Unit) {
  //..
}
fun RBuilder.Container(header: String) {
  //..
}
```

It works, but if I have more than one property, I will have to create bigger number of functions

```kt
fun RBuilder.Container(header: RBuilder.() -> Unit, content: RBuilder.() -> Unit)
fun RBuilder.Container(header: String, content: RBuilder.() -> Unit)
fun RBuilder.Container(header: RBuilder.() -> Unit, content: String)
fun RBuilder.Container(header: String, content: String)
```
For 3 different properties there will be 9 functions. 

Is there a way to simplify this and create only one signature that accepts both String and RBuilder types?

**Comment by Hypnosphi** [comment]
If Kotlin had union types, it would be possible, but unfortunately it doesn't (AFAIK it is intentional)

**Comment by just-boris** [comment]
Does that mean, that there is no better way than create all possible variations? For example, currently I am considering code generation. Is there existing tool to do this in Kotlin?

**Comment by Hypnosphi** [comment]
@Leonya may be familiar with some solution for code generation

**Comment by Leonya** [comment]
Well, there's https://github.com/square/kotlinpoet

I personally would stick with `fun RBuilder.Container(header: RBuilder.() -> Unit, content: RBuilder.() -> Unit)` as the most flexible method and drop the rest.

**Comment by just-boris** [comment]
@Hypnosphi, @Leonya thank you for the kind answers! Will try to come up with some solution.
