### ISSUE TITLE
Add Number wrapper

### ISSUE THREAD

**Issue by Ayfri** [JetBrains/kotlin-wrappers#1233]
Add Number class, `Number()` constructor, add methods `toExponential()`, `toFixed()`, `toLocaleString()`, `valueOf()`

Add companion object properties `Number.EPSILON`, `Number.MAX_SAFE_INTEGER`, `Number.MAX_VALUE`, `Number.MIN_SAFE_INTEGER`, `Number.MIN_VALUE`, `Number.NaN`, `Number.NEGATIVE_INFINITY`, `Number.POSITIVE_INFINITY`
Add companion object methods `Number.isFinite()`, `Number.isInteger()`, `Number.isNaN()`, `Number.isSafeInteger()`, `Number.parseFloat()`, `Number.parseInt()`

**Comment by Ayfri** [comment]
I need `Number.parseFloat/Int()` for having JS Behavior for reading number value of a form, plus `toExponential()` to display numbers in scientific mode.

**Comment by turansky** [comment]
<img width="1024" alt="Screen Shot 2022-02-21 at 10 38 15 AM" src="https://user-images.githubusercontent.com/9942723/154909505-f0b82e19-6944-4b3c-8757-f69bb54543c8.png">

**Comment by turansky** [comment]
<img width="410" alt="Screen Shot 2022-02-21 at 10 39 31 AM" src="https://user-images.githubusercontent.com/9942723/154909659-7f9ebe42-2a94-42d4-906e-6a8932477ecc.png">

**Comment by Ayfri** [comment]
Oh okay they are already equals to JS behavior, but I need `toExponential()`
