### ISSUE TITLE
Add Proxy wrapper

### ISSUE THREAD

**Issue by Ayfri** [JetBrains/kotlin-wrappers#1234]
Add the class Proxy, add the constructor `Proxy()`

Add the companion object method `Proxy.revocable()`

**Comment by turansky** [comment]
@Ayfri Create please one meta issue for all missed API, which you really need. It will be more effective

**Comment by Ayfri** [comment]
Okay sorry, I thought it was more clean to do this.

**Comment by Ayfri** [comment]
And to respond to you I need all of them right now.

**Comment by turansky** [comment]
OK. Let's use separate issues in this case
Write please your use cases in issues

**Comment by Ayfri** [comment]
For Proxy I need them to create Observers-like behavior
