### ISSUE TITLE
Display names for functional components

### ISSUE THREAD

**Issue by utikeev** [JetBrains/kotlin-wrappers#125]
Current usage of `functionalComponent` leads to the `Unknown` named components. Is it possible to add an optional argument with `displayName` for it?

```kotlin
fun mainPage() = functionalComponent<RProps> {
...
}
```

![image](https://user-images.githubusercontent.com/12977355/61910328-00a21980-af3d-11e9-83a7-7fbd01f96261.png)

**Comment by Skolotsky** [comment]
It isn't able yet without Kotlin reflection for function names. :(

**Comment by utikeev** [comment]
Is `fun functionalComponent<RProps>(displayName: String? = null)` also not possible?

**Comment by Skolotsky** [comment]
Oh, you are right! As workaround it's possible... I'll add signature.

**Comment by SalomonBrys** [comment]
Small trick while waiting for this:

```kotlin
operator fun <P> FunctionalComponent<P>.getValue(thisRef: Any?, property: KProperty<*>): FunctionalComponent<P> {
    this.asDynamic().displayName = property.name.capitalize()
    return this
}
```

Used like this:

```kotlin
val myComponent by functionalComponent<MyProps> {
    /* ... */
}
```

**Comment by Leonya** [comment]
Fixed in pre.116
