### ISSUE TITLE
How can I pass classes to styledDiv

### ISSUE THREAD

**Issue by musooff** [JetBrains/kotlin-wrappers#126]
Can you guide me how to add `classes` to `styledDiv`.

In a normal `div` I could have
```
div(classes = "row") {

}
```

How could I combine both custom `classes` and `styledDiv` when, say, I want to use bootstrap.

**Comment by Skolotsky** [comment]
for example
```kotlin
styledDiv {
    css {
       +"row"
    }
}
```

**Comment by NorbertSandor** [comment]
> for example
> 
> ```kotlin
> styledDiv {
>     css {
>        +"row"
>     }
> }
> ```

The downside of operator overloading ;)

**Comment by musooff** [comment]
So simple operation but had it been in documentation, it would have been nicer.
