### ISSUE TITLE
Feature Request: withRouter

### ISSUE THREAD

**Issue by SorenV** [JetBrains/kotlin-wrappers#128]
Perhaps its in the API, but I've missed it.

https://reacttraining.com/react-router/web/api/withRouter

The below works, but it's lacking, and I'm not sure the generics are proper or the best.  (just started with kotlin and react a little while ago)

```
@JsName("withRouter")
external fun <P, S, T : RComponent<P, S>> withRouter(
    jsConstructor: JsClass<T>,
    options: Options? = definedExternally
): FunctionalComponent<P>

@JsName("withRouter")
external fun <T> withRouter(
    jsConstructor: FunctionalComponent<T>,
    options: Options? = definedExternally
): FunctionalComponent<T>


external interface Options {
    val withRef: Boolean?
}

external interface WithRouter<T : RProps> : RProps {
    var history: RouteResultHistory
    var location: RouteResultLocation
    var match: RouteResultMatch<T>
}
```

I think it would be better to return an `Interface WithRouterComponent<??>{} `   of some kind since there are properties that are hidden due to the necessity for it to be a FuncationalComponent so that 

```
RBuilder.child(
    functionalComponent: FunctionalComponent<P>,
    props: P = jsObject {},
    handler: RHandler<P> = {}
)
```
is the resolved child function.

So either I missed the implementation again, or if not, please consider this a respectful request for a proper implementation, or feed back on how to make my hack correct/better/future proof.  

Thanks for everything!

~S

**Comment by FrancoSabadini** [comment]
Hi @SorenV, were you able to make this work? I've tried the code you shared but it hasn't worked for me, I get the error: 

```
Uncaught TypeError: Cannot read property 'params' of undefined
```

**Comment by FrancoSabadini** [comment]
After trying different things I managed to make this work.

I'll leave the code here in case it helps someone:

```kotlin
class ExampleComp : RComponent<ExampleCompProps, RState>() { ... }

interface ExampleCompProps : RouteResultProps<RProps> { ... }

fun RBuilder.exampleComp(handler: RHandler<ExampleCompProps>): ReactElement {
    child(react.router.dom.withRouter(ExampleComp::class.js), handler = handler)
}
```

Before this, I was trying to make it work by using `RouteResultProps<ExampleCompProps>` but that didn't work for some reason, so I had to implement `RouteResultProps<RProps>` from my props interface instead.
