### ISSUE TITLE
Passed in properties are missing inside functionalComponent lambda

### ISSUE THREAD

**Issue by esurijon** [JetBrains/kotlin-wrappers#131]
Bellow code is a slight modification of this [react hook example](https://github.com/JetBrains/kotlin-wrappers/pull/121#issue-299773226).

```
interface Labels : RProps {
    val counterLabel: String
    val buttonLabel: String
}

val renderCount = functionalComponent<Labels> { props ->

    val (count, setCount) = useState(0)

    useEffect {
        console.log("useEffect $count")
    }

    +"${props.counterLabel} $count"

    button {
        attrs {
            onClickFunction = {
                setCount(count + 1)
            }
        }
        + props.buttonLabel
    }
}

fun RBuilder.renderCount(labels: Labels) {
    child(renderCount, labels)
}
```
When rendering the component **props.buttonLabel** is **undefined**.

**Comment by darren-bell-nanthealth** [comment]
@esurijon have you found a workaround for this issue. It seems pretty key to using a functionalComponent!

**Comment by Goregius** [comment]
I figured out that you can use jsObject for this so in your case it would be:
```kotlin
fun RBuilder.renderCount(labels: Labels) {
    child(renderCount, jsObject {
        this.counterLabel= labels.counterLabel
        this.buttonLabel= labels.buttonLabel
    })
}
```

But this would mean your interface properties would have to be vars.

**Comment by Skolotsky** [comment]
@esurijon , how do you create `labels: Labels` for `RBuilder.renderCount`?

**Comment by turansky** [comment]
`Labels` must be `external`

@Leonya Issue can be closed
