### ISSUE TITLE
Correct inheritance for Theme (kotlin-mui)

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1317]
I noticed a deviation of the kotlin-mui wrappers from the original MUI definitions:

`BaseTheme` & `ThemeOptions` in [@mui/material/styles/createTheme](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/styles/createTheme.d.ts) should inherit from `Theme` & `ThemeOptions` from [@mui/system/createTheme/createTheme](https://github.com/mui/material-ui/blob/master/packages/mui-system/src/createTheme/createTheme.d.ts)

This leads to problems like not being able to access `breakpoints` of the theme

**Comment by hofi99** [comment]
As a quick fix: `theme.asDynamic().breakpoints.up("md")` returns the correct value :)

**Comment by turansky** [comment]
Strict WA:

```
// TEMP
inline fun Theme.asSystem(): mui.system.Theme =
    unsafeCast<mui.system.Theme>()

theme.asSystem().breakpoints.up("md")
```
