### ISSUE TITLE
Generic bounds on (R)Component are too tight

### ISSUE THREAD

**Issue by spand** [JetBrains/kotlin-wrappers#132]
Component (and RComponent) have generic bounds for props and state to be `RProps` and `RState`. This is unnecessarily tight and obviously prevents types that does not implement the interfaces from being used as props (or state for that matter although I cannot image such use case at hand).

The concrete use case I have is that my types come from another (kotlin common) module and as such cannot be made to implement `RProps`

As an experiment I have tried to do this myself and it seems that not much relies on this behavior. I have not yet verified if this is enough to solve my use case, **but I ask here because I want to know what the odds are this change to be implemented.**

```
Index: kotlin-react/src/main/kotlin/react/Imports.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- kotlin-react/src/main/kotlin/react/Imports.kt	(revision d94019ba3dae64fd4c1afb3644d8f2ffcfa3f8c1)
+++ kotlin-react/src/main/kotlin/react/Imports.kt	(date 1567069801345)
@@ -21,8 +21,8 @@
     fun toArray(children: Any?): Array<out Child>
 }
 
-abstract external class Component<P : RProps, S : RState>(
-    props: RProps = definedExternally
+abstract external class Component<P : Any, S : Any>(
+    props: P = definedExternally
 ) {
     open val props: P
     var state: S
Index: kotlin-react/src/main/kotlin/react/ReactComponent.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- kotlin-react/src/main/kotlin/react/ReactComponent.kt	(revision d94019ba3dae64fd4c1afb3644d8f2ffcfa3f8c1)
+++ kotlin-react/src/main/kotlin/react/ReactComponent.kt	(date 1567069659215)
@@ -84,7 +84,7 @@
     return fn
 }
 
-abstract class RComponent<P : RProps, S : RState> : Component<P, S> {
+abstract class RComponent<P : Any, S : Any> : Component<P, S> {
     constructor() : super() {
         state = jsObject { init() }
     }
@@ -98,7 +98,7 @@
     open fun S.init(props: P) {}
 
     fun RBuilder.children() {
-        props.children()
+        (props as RProps).children()
     }
 
     abstract fun RBuilder.render()
```

**Comment by spand** [comment]
As a workaround it seems `Boxed` can be used to handle this case for anyone else wondering.

**Comment by Skolotsky** [comment]
I see your reasonable points. But there are some extension methods and properties with RProps. And they are used not only inside wrappers but in apps too. So it looks like breaking change and explicit cast to RProps will be needed in many places.

**Comment by turansky** [comment]
`RState` - not problem for function component :)
`RProps` as marker interface required for strict/valid DSL
Props can be hidden at all by compiler plugin, like [this one](https://github.com/bnorm/kotlin-react-function)

@Leonya Looks like problem is solved

cc  @sgrishchenko
