### ISSUE TITLE
sx typed class selectors for MUI

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1323]
Currently it is only possible to select a class of an MUI component with a string receiver:
```
sx {
    " .MuiDrawer-paper" {
        width = 100.px
    }
}
```

It would be really convenient to select these known classes in a typed way:
```
sx {
    DrawerClasses.paper {
        width = 100.px
    }
}
```

**Comment by turansky** [comment]
@hofi99 Do you use custom class names or only predefined (by MUI) inside `sx` block?

**Comment by hofi99** [comment]
Only MUI classes.
Custom classes could of course be interesting, but the main advantage for me is that by using the new kotlin-mui and csstype wrappers having pretty much everything typed.

**Comment by turansky** [comment]
Syntax:

Before
```kotlin
sx {
    ".MuiDrawer-paper" {
        width = 100.px
    }
}
```

After (with #1339)
```kotlin
sx {
    MuiDrawer.paper {
        width = 100.px
    }
}
```
