### ISSUE TITLE
InputBaseComponentProps fix inheritance [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1343]
`InputBaseComponentProps` currently inherits from `HTMLAttributes` but actually needs to inherit from `InputHTMLAttributes`.

**Comment by turansky** [comment]
<img width="651" alt="Screenshot 2022-03-16 at 00 45 01" src="https://user-images.githubusercontent.com/9942723/158477911-2b1b918d-2986-4cfb-ae97-a63302abf2aa.png">

**Comment by hofi99** [comment]
Oh, my bad.
So I just have to stick to using dynamic casts, right?

**Comment by hofi99** [comment]
Sorry, my bad.
But still `HTMLInputElement` and `HTMLTextAreaElement` would need to be types of `HTMLAttributes`

**Comment by hofi99** [comment]
Since it's structurally currently not possible to adjust the inheritance for this to work out of the box, I made a small extension function that can be used to "access" the desired attributes: 
```
var InputBaseComponentProps.min: Any? // String (e.g. "123", "2022-01-01'T'13:14:00") or Number (e.g. 123)
  get() = asDynamic().min
  set(value) {
    asDynamic().min = value
  }
```
If the wrappers get an update at some point you just need to remove this extension because the code where it was used will stay the same :)
