### ISSUE TITLE
Add theme.spacing() helper [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1344]
It would be nice to have the `theme.spacing()` helper wrapped.
See: https://mui.com/customization/spacing/

Minimal effort workaround would be to just use `theme.asDynamic().spacing(<SomeNumber>)` for the time being.
Creating a custom theme is of course also a solution

**Comment by turansky** [comment]
New [`Spacing`](https://github.com/karakum-team/mui-kotlin/commit/d7610cc0fc27db154b9d6f8bb5ff0b3adb79d94c)

**Comment by hofi99** [comment]
Very nice improvement!
