### ISSUE TITLE
TextFieldProps onChange access target.value [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1346]
I noticed that the onChange function of `OutlinedTextFieldProps` and all the other variants have `HTMLElement` as the type for the `ChangeEventHandler`.
This leads to having to dynamically cast like:
```
event.target.asDynamic().value as String
```
`target` is a reference to the object of the event and therefore changing the type to `HTMLInputElement` would fix this issue.

**Comment by hofi99** [comment]
Since it's structurally currently not possible to adjust the type for this to work out of the box, I made a small extension function that can be used to "access" the desired attributes:
```
val HTMLElement.value: String
  get() = when (this) {
    is HTMLInputElement -> value
    is HTMLTextAreaElement -> value
    else -> throw IllegalArgumentException("There is no value in this HTMLElement")
  }
```
If the wrappers get an update at some point you just need to remove this extension because the code where it was used will stay the same :)

**Comment by nguyenxndaidev** [comment]
@hofi99 with the extension, it only changes from
`(event.target as HTMLInputElement).value`
to
`(event.target as HTMLElement).value`

while we want:
`event.target.value`

**Comment by nguyenxndaidev** [comment]
I do it a bit different:
```
val SyntheticEvent<*, *>.targetValue: String
  get() = target.asDynamic().value as String

val HTMLElement.value: String
  get() = this.asDynamic().value as String
```
