### ISSUE TITLE
React wrapper for forwardRef

### ISSUE THREAD

**Issue by IARI** [JetBrains/kotlin-wrappers#1347]
In order to be able to wrap native html elements React offers the `forwardRef` function that is to be used in conjunction with refs
I will not go further into detail about use-cases here, there is plenty of material available online in blogs like this one
https://blog.logrocket.com/complete-guide-react-refs/

In the Pre - pre.282 world with the RBuilder DSL there's a wrapper
```Kotlin
public fun <T : kotlin.Any, P : react.PropsWithRef<T>> forwardRef(handler: react.RBuilder.(P, react.Ref<T>?) -> kotlin.Unit): react.ComponentType<P> { /* compiled code */ }
```
available.

Currently to use forwardRef, the only way is to use `rawForwardRef`, as in this code example [kindly provided to me](https://kotlinlang.slack.com/archives/C5ZTZ6ER0/p1647286999066889?thread_ts=1647259091.810589&cid=C5ZTZ6ER0) by @turansky:
https://github.com/JetBrains/kotlin-wrappers/blob/a57d1840ad988606b83198a48daba17c0dcbeea2/examples/src/main/kotlin/example/ForwardingRefs.kt#L22

It seems like a proper wrapper for the `ChildrenBuilder` DSL is missing.

**Comment by turansky** [comment]
Draft:

```kotlin
package react

fun <T : Any, P : PropsWithRef<T>> ForwardRef(
    block: ChildrenBuilder.(
        props: P, 
        forwardedRef: Ref<T>?,
    ) -> Unit,
): ForwardRefExoticComponent<P> =
    rawForwardRef { props, ref ->
        createElementOrNull { block(props, ref) }
    }
```
