### ISSUE TITLE
Why not use UMD?

### ISSUE THREAD

**Issue by JoeHegarty** [JetBrains/kotlin-wrappers#135]
I am not super familiar with the Javascript ecosystem (which is why I'm using Kotlin) so please forgive me if I'm being idiotic.

I ran across the same issue described in #93 and I am wondering why this project targets `commonjs`?

Wouldn't it make more sense to target `UMD` so it can be consumed both by node/compile time tools as well as be consumed directly in the browser for those of us that are using pure gradle/kotlin2js build pipelines?

My understanding is that `UMD` is universal and works with both `commonjs` and `AMD` projects.

Am I missing some case where this will break? It would be great if that use case could work out of the box too.

**Comment by turansky** [comment]
`umd` is good as final target (apllication)
For modular libraries (like `kotlin-wrappers`) `commonjs` is preferred

Next step - ES6 modules

**Comment by Leonya** [comment]
Please update to `pre.122`
