### ISSUE TITLE
MUI: no way to specify Select type

### ISSUE THREAD

**Issue by xian** [JetBrains/kotlin-wrappers#1358]
[Select](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-mui/src/main/generated/mui/material/Select.kt#L194) offers no way to specify the value type. Ideally it'd allow for something like this:

```kotlin
Select<String> {
    value = "value"
    onChange = { s: String -> ... }
}
```

**Comment by xian** [comment]
Related to #1356.

**Comment by turansky** [comment]
```
Select<SelectProps<String>> {
    value = "value"
    onChange = { s: String -> ... }
}
```

**Comment by xian** [comment]
Got it, cool. The `<SelectProps<…>>' boilerplate seems a little clunky, any way to avoid exposing that?

**Comment by turansky** [comment]
For custom components you can use custom adapters (`ChildrenBuilder` extensions)

Common problem issue already exists - #1129
