### ISSUE TITLE
Issue with amp for get request parameters

### ISSUE THREAD

**Issue by vlipovetskii** [JetBrains/kotlin-wrappers#137]
kotlins-css adds amp. 

https://test.html?name1=value1&name2=value2 
-> 
https://test.html?name1=value1&ampname2=value2

import kotlinx.html.a
import kotlinx.html.body
import kotlinx.html.html
import kotlinx.html.stream.appendHTML
import org.amshove.kluent.`should contain`
import org.amshove.kluent.`should not contain`
import org.junit.jupiter.api.Test

class HtmlTests {

    @Test
    fun `when a(a&b) then a href=a&b`() {

        val getUrl = "https://test.html?name1=value1&name2=value2"

        val a = StringBuilder().apply {
            appendHTML().html {
                body {
                    a(getUrl)
                }
            }
        }

        println(a)

        a.`should not contain`("&amp")
        a.`should contain`(getUrl)

    }

}

**Comment by Leonya** [comment]
Seems like correct behaviour to me. Also it has nothing to do with this project.
