### ISSUE TITLE
kotlin-mui 5.5.2 broken due to removed BackdropUnstyled in MUI 5.0.0.alpha.74

### ISSUE THREAD

**Issue by mysticfall** [JetBrains/kotlin-wrappers#1371]
`@mui/base/BackdropUnstyled.js` has been [removed](https://github.com/mui/material-ui/pull/31923) from MUI since 5.0.0.alpha.74 which causes any project depending on `kotlin-mui` failing with an error when opening in a browser.

Apparently, the problem seems to be due to a `JsModule` referening the missing source in https://github.com/karakum-team/mui-kotlin/blob/main/mui-kotlin/src/main/kotlin/mui/base/BackdropUnstyled.kt.

**Comment by turansky** [comment]
WA for such problems - add fixed NPM dependencies.
