### ISSUE TITLE
Specify top/right/bottom/left with Length [csstype]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1372]
As far as I have seen it is currently not possible to specify all positions (`top`, `right`, `bottom`, `left`) via the `Length` prop.
Some properties like `border` are therefore not usable in a typed way:
```
border = Border(width = Width(1.px, 1.px, 0.px, 1.px), style = LineStyle.solid)
```

As a local fix I added this function to my Helper file:
```
fun Width(
  top: Length,
  right: Length,
  bottom: Length,
  left: Length,
): Length =
  "$top $right $bottom $left".unsafeCast<Length>()
```

**Comment by turansky** [comment]
Special `Border` factories [required instead](https://developer.mozilla.org/en-US/docs/Web/CSS/border#formal_definition)

**Comment by hofi99** [comment]
Nice, I did not know about the `array` function :)

**Comment by turansky** [comment]
We also discuss special common factory for `margin`, `padding` and `border` with limited parameters count (from 2 to 4)
