### ISSUE TITLE
Mui typed class [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1377]
I noticed that the base `Mui` class is missing as a typed version.
See e.g [ListItemButton](https://mui.com/api/list-item-button/)

<img width="850" alt="Screenshot 2022-03-31 at 17 07 44" src="https://user-images.githubusercontent.com/62036655/161088214-07a3edd9-c0b7-4150-8e00-37f756075b63.png">

I'm currently using it like:
<img width="629" alt="Screenshot 2022-03-31 at 17 09 23" src="https://user-images.githubusercontent.com/62036655/161088575-1ae85e64-2f1a-4f41-b3d7-876c78c14bca.png">

**Comment by turansky** [comment]
@hofi99 Doc link (like [this](https://mui.com/customization/how-to-customize/)) - requirement for such issues
