### ISSUE TITLE
How do I apply middleware?

### ISSUE THREAD

**Issue by fakheet** [JetBrains/kotlin-wrappers#139]
I'm currently trying to implement Redux Advanced Example (the one that uses Reddit API to fetch post titles) and I can'f for the life of me figure out how to add `redux-thunk` to the project (and how to work with middleware in general. My experience with JS, React, Redux and web-development in general is almost non-existent so I would greatly appreciate if you pointed me to some **_kotlin_** specific guide or gave a "for dummies" explanation. Thanks in advance.

**Comment by 21region** [comment]
Did you manage to implement it? I am also struggling with that.

**Comment by fakheet** [comment]
> Did you manage to implement it? I am also struggling with that.

I didn't, but long story short, this here is a project from which you can see how to do it. https://github.com/AltmanEA/KotlinExamples/tree/master/js/reduxAsync

So far I'm pretty dissapointed with redux in Kotlin. Everything is obtuse and almost total lack of proper documentation and examples doesn't help at all.
