### ISSUE TITLE
MUI: kotlinx.css.Color vs csstype.Color

### ISSUE THREAD

**Issue by xian** [JetBrains/kotlin-wrappers#1395]
`styled.StyleSheet`, etc., use `kotlinx.css.Color`, while `mui.material.styles` classes use `csstype.Color`, which are not mutually assignable.

Is there a reason to use `csstype.Color` at all?

**Comment by turansky** [comment]
Zero-runtime interfaces are preferred in common case.
`csstype.Color` and other interfaces from `csstype` are zero-runtime interfaces and preferred by default.

P.S. `kotlin-emotion` can be used if you need `css-in-js` library.

**Comment by turansky** [comment]
@xian Close?

**Comment by xian** [comment]
Okay, so what's the preferred way to get code like this compiling? (`withAlpha` and `blend` are methods on `kotlinx.css.Color`.)

```kt
class ThemeStyles(val theme: Theme) : StyleSheet("app-ui-controls-theme", isStatic = true) {
    val button by css {
        backgroundColor = theme.palette.secondary.main
            .withAlpha(.125).blend(theme.palette.background.paper)
}
```

**Comment by turansky** [comment]
> There are no docs or examples for `kotlin-emotion`

[Example](https://github.com/karakum-team/kotlin-react-table-sample)

> I'm assuming I'll need to do some ugly casting like this?

Not expected :)

> Why not just use the perfectly serviceable types from `kotlinx.css`?

1. Because it can work better (without redundant runtime)
2. `csstype.Properties` (with `csstype.Color`) will be used [in any case](https://github.com/JetBrains/kotlin-wrappers/blob/588d37885f0612a15bcf4b2322882d7b49de3911/kotlin-react-dom/src/main/generated/react/dom/html/HTMLAttributes.kt#L33)

**Comment by dioxic** [comment]
@turansky  For MUI, is this done better inside the `sx{}` block or the `css{}` block? Does it matter?

@xian I hacked this together:

**build.gradle.kts**
`implementation(npm("chroma-js", "2.4.2"))`

**Chroma stuff**
```kotlin
@JsModule("chroma-js")
@JsNonModule
external fun chroma(color: Color): ChromaColor

external class ChromaColor {
    fun alpha(alpha: Number): ChromaColor
    fun hex(mode: String = definedExternally): Color
}
```

**Usage**
```kotlin
val TableToolbar = FC<TableToolbarProps> { (title, selected, actions) ->

    val theme = useContext(ThemeContext)

    Toolbar {
        css {
            if (selected.isNotEmpty()) {
                backgroundColor = chroma(theme.palette.primary.main)
                    .alpha(theme.palette.action.activatedOpacity)
                    .hex()
            }
        }
   }
   ...
}
```

Seems to work 😄

**Comment by turansky** [comment]
@dioxic `sx` is preferred  according documentation

cc @aerialist7

**Comment by aerialist7** [comment]
Yep, `sx` is the recommended option for MUI.
