### ISSUE TITLE
Any intention to support Vue.js too?

### ISSUE THREAD

**Issue by wolfheart** [JetBrains/kotlin-wrappers#14]
Is there any intention to support Vue.js with an *kind of offical* kotlin-wrapper for for React.js?

**Comment by Hypnosphi** [comment]
Vue templates are valid HTML, so you can directly use [`kotlinx-html`](https://github.com/Kotlin/kotlinx.html) to produce them in Kotlin

**Comment by wolfheart** [comment]
My idea is more to combine Kotlin-JS with Vue.js, not just generating Vue.js on the server side. Or maybe I'm misunderstanding your answer?

**Comment by Hypnosphi** [comment]
kotlinx-html works in kotlin-frontend-tools as well, so you can generate your templates in runtime

**Comment by wolfheart** [comment]
Concerning the example https://github.com/ricardocanelas/vuejs2-examples/blob/master/basic/e3/index.html how would I replace the Javascript-part inside <script> with Kotlin-JS?

Can I completely replace the Javascript-part with Kotlin-JS? As far as I understood, one would need a wrapper for the ```Vue``` construct, right?

**Comment by Hypnosphi** [comment]
I'm no expert in Vue, but you should be able to use it like any other external lib: http://kotlinlang.org/docs/tutorials/javascript/working-with-javascript.html#using-ts2kt-to-generate-header-files-for-kotlin

**Comment by ScottHuangZL** [comment]
echo for add support for Vue2. Thanks.

**Comment by Hypnosphi** [comment]
@ScottHuabgZL does the above approach work for you?

**Comment by ScottHuangZL** [comment]
@Hypnosphi  it should be work if we just consider Vue2 JS as a external JS library just like JQuery.
But do you have a plan to provide **create-kotlin-vue-app**  CLI tool?  Just like create-kotlin-react-app?
As you  know Vue is quite popular in world, even in China.
You will attracting more Kotlin users if JB provide above Vue CLI.  
Thanks.

**Comment by Hypnosphi** [comment]
Is there an analogous tool for JS? We didn't build `create-kotlin-react-app` from scratch, we just forked `create-react-app`

**Comment by ScottHuangZL** [comment]
Ha, I just play Kotlin + React / Vue as hobby, no intend to build from scratch.
Anyway, thanks for your help for the input onChange issue. I just complete the todo list sample after get your hint. Thanks.

**Comment by ScottHuangZL** [comment]
You can close the issue if JB no plan add wrapper for VueJs, but I believe it will loss some potential users, especially from China, as you know Vue's author actually from China even he work is USA now.
