### ISSUE TITLE
Stability problem using react hooks

### ISSUE THREAD

**Issue by NorbertSandor** [JetBrains/kotlin-wrappers#140]
I try to implement the following React.js example in Kotlin JS:

![React.js hook sample](https://miro.medium.com/max/800/0*A25LKRTLZDF2afeQ.png)

My implementation doesn't seem to be perfect because after 2 seconds it is rendered at 0 FPS and totally kills Chrome :D
Do you have any idea what am I doing wrong?

```
fun main() {
    render(document.getElementById("container")) {
        div {
            child(MouseWatcher)
        }
    }
}

data class MousePosition(val x: Int, val y: Int)

fun useMousePosition(): MousePosition {
    val (position, setPosition) = useState(MousePosition(0, 0))

    fun handleMouseMove(e: Event) {
        e as MouseEvent // TODO It doesn't compile with parameter type of MouseEvent
        setPosition(MousePosition(e.clientX, e.clientY))
    }

    useEffectWithCleanup {
        window.addEventListener("mousemove", ::handleMouseMove);
        { window.removeEventListener("mousemove", ::handleMouseMove) }
    }

    return position
}

val MouseWatcher = functionalComponent<RProps> {
    val p = useMousePosition()
    span {
        +"${p.x}, ${p.y}"
    }
}
```

Besides, I need some help fixing the TODO as well...

**Comment by utikeev** [comment]
You may want to look here: https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect

__TL;DR__
By default, effects run after every successful rendering. So you register a new listener every time a mouse is moved, thus registering really a lot of them :)  
So, in your example they pass an empty array in the end of `React.useEffect`. The items of this array are called _dependencies_, and the effect will run again only after they changed. If that's the empty list, then the effect will run only once (similar to `componentDidMount`, but for functional components).  
`useEffectWithCleanup` takes `List<dynamic>` as its dependencies, so basically you can solve that by passing `listOf()` for its first parameter:
```kotlin
useEffectWithCleanup(listOf()) {
    window.addEventListener("mousemove", ::handleMouseMove);
    { window.removeEventListener("mousemove", ::handleMouseMove) }
}
```

**Comment by utikeev** [comment]
As for fixing TODO, nobody guarantees that this event listener will receive `MouseEvent`, so, basically, it is proper to check for the type and log if it has unexpected type:
```kotlin
fun handleMouseMove(e: Event) {
    if (e is MouseEvent) {
        // Here happens a smart cast
        setPosition(MousePosition(e.clientX, e.clientY))
    } else {
        console.log("[WARN] Received: ${e::class.js.name}, Expected: MouseEvent")
    }
}
```

**Comment by NorbertSandor** [comment]
> You may want to look here: https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect

It works perfectly, thanks for your help.
