### ISSUE TITLE
How to style react.router.dom.Link with styled components?

### ISSUE THREAD

**Issue by andrew-k-21-12** [JetBrains/kotlin-wrappers#1400]
Tried the following ways:

1. Manual introduction of a CSS class -> no dynamic CSS configurations are possible:
```kotlin
Link {
        attrs {
            className = ClassName("SomeClassName")
            // ...
        }
        // ...
}
```

2. Raw style description -> mixing with rule sets and pseudo-classes usages are not possible:
```kotlin
Link {
        attrs {
            style = CssBuilder().apply {
                visited {
                    color = Theme.palette.actionSecondary1.get(context)
                }
                // ...
            }.toStyle().unsafeCast<Properties>()
        }
        // ...
}
```

3. `css { ... }` blocks inside of `Link` -> `attrs` obviously don't work as well.

Is there any convenient solution to style `react.router.dom.Link` dynamically with styled components?

**Comment by andrew-k-21-12** [comment]
For now using just a plain styled `<a>` 😅 
Will give a try to `kotlin-emotion` as well, thanks.

**Comment by turansky** [comment]
@andrew-k-21-12 Close?

**Comment by andrew-k-21-12** [comment]
If there are no ways to do the described thing via styled components - then yes, sure, will switch to `kotlin-emotion` 🙂

**Comment by andrew-k-21-12** [comment]
And as it was expected, it can be also done pretty easily with styled components:

```kotlin
div { // can be any other RDOMBuilder scope provider
    styled(Link).invoke(this) { // "this" refers to the current RDOMBuilder, i.e. where to insert this component
        css {
            // Required styling.
        }
        attrs {
            to = "setting-attributes"
        }
        +"Link's label"
    }
}
```
