### ISSUE TITLE
MUI breakpoints

### ISSUE THREAD

**Issue by xtexChooser** [JetBrains/kotlin-wrappers#1405]
In react, we could use `sx` syntax like this: `display: { xs: 'none', md: 'flex' }`. However, there is no way to use equivalent code in Kotlin.

**Comment by turansky** [comment]
Fine function name required

Draft
```Kotlin
display = mySuperFactory { 
    xs = none
    md = Display.flex
}
```

cc @sgrishchenko @aerialist7

**Comment by aerialist7** [comment]
> Fine function name required
> 
> Draft
> ```Kotlin
> display = mySuperFactory { 
>     xs = none
>     md = Display.flex
> }
> ```
> 
> cc @sgrishchenko @aerialist7 

```Kotlin
...
sx {
  display {
    xs = none
    md = flex
  }
...
```

**Comment by turansky** [comment]
@aerialist7 Single factory required

**Comment by turansky** [comment]
@xtexChooser Do you need standard breakpoints only? 
Or custom breakpoints support also required?

**Comment by turansky** [comment]
[Solution example](https://github.com/karakum-team/mui-kotlin/blob/0b4dbba9a086e95a1fe75390502284a6aeead92d/playground/src/main/kotlin/Breakpoints.kt)
