### ISSUE TITLE
MUI: Wrapper property name invalid for JS

### ISSUE THREAD

**Issue by xtexChooser** [JetBrains/kotlin-wrappers#1406]
Look at [this file](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-mui/src/main/generated/mui/material/IconButton.ext.kt).

This file defined an enum named `IconButtonColor` with a `@JsName` annotation(`@JsName("""(/*union*/{inherit: 'inherit', default: 'default', primary: 'primary', secondary: 'secondary', error: 'error', info: 'info', success: 'success', warning: 'warning'}/*union*/)""")`).

The property name of `default` is OK in Kotlin, but not OK in JS.

When KT code referenced this enum, (legacy) compiler will output JS code like this: `var IconButtonColor$inherit = (/*union*/{inherit: 'inherit', default: 'default', primary: 'primary', secondary: 'secondary', error: 'error', info: 'info', success: 'success', warning: 'warning'}/*union*/).inherit;`.

When executing `:processDceJsKotlinJs` task, KotlinJsDce will fail because `default` is a keyword in JS.
```
error: at F:\Minecraft\toedit\build\js\packages\ToEdit\kotlin\ToEdit.js (84, 63): invalid property id

FAILURE: Build failed with an exception.
```

These wrappers should be a safe way to define these like:
```
@JsName("""((function(){var union=/*union*/{inherit: 'inherit', primary: 'primary', secondary: 'secondary', error: 'error', info: 'info', success: 'success', warning: 'warning'}/*union*/;union['default']='default';return union;})())""")
```
I have tested this way by editing cache file and build with `gradle jsBrowserDistribution -x compileKotlinJs` to keep cache not updated.

I noticed that my local NodeJS v16.2.0 can execute the old code directly, although it is not important because Kotlin with React only works on browser.

This also happens on `AriaHasPopup`.
A temp oratory fix is to use `unsafeCast` like `"inherit".unsafeCast<IconButtonColor>()` and `"menu".unsafeCast<AriaHasPopup>()`.

**Comment by turansky** [comment]
Solution is here - #1077

**Comment by xtexChooser** [comment]
> Solution is here - #1077

Oh, it works! Thanks!

**Comment by turansky** [comment]
@YuryMikhailuts Solution is here - #1077
