### ISSUE TITLE
MUI: Multi-property-type support

### ISSUE THREAD

**Issue by xtexChooser** [JetBrains/kotlin-wrappers#1408]
In [kotlin-mui/src/main/generated/mui/material/Menu.kt#L24](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-mui/src/main/generated/mui/material/Menu.kt#L24), property `anchorEl` maybe an HTML element or a provider function.

But there is only function-style provided to KT.

**Comment by turansky** [comment]
And it cover all use cases? Right?

**Comment by xtexChooser** [comment]
> And it covers all use cases? Right? :)

er, idk, but the wrapper porvided KT with `(Element) -> Element` but I found in comment that direct HTML element is also allowed.

I tested `asDynamic()['anchorEl'] = HTMLElement` works.

**Comment by turansky** [comment]
It's true, but this problem isn't unique.
Common fine solution will be possible only when unions will be supported in Kotlin.

**Comment by xtexChooser** [comment]
Yes, so this issue may put off for some time.

**Comment by turansky** [comment]
It can be closed, because it will be common change for all wrappers
