### ISSUE TITLE
How to use existing React component

### ISSUE THREAD

**Issue by jpink** [JetBrains/kotlin-wrappers#141]
It seems impossible for me to use existing React component without some "raw" method.

E.g. I try to use [Material Icons](https://material-ui.com/components/material-icons/). In JS they are used like:
```javascript
import AccessibleIcon from '@material-ui/icons/Accessible';
import React from 'react';

export function Test() {
  return <AccessibleIcon>;
}
```

but how to do it in Kotlin?
```kotlin
package test

import react.*
import react.dom.*

fun RBuilder.test() {
    raw {
        +"<AccessibleIcon>"
    }
}
```

I don't know how to define component (wrapper) for existing imported React component either. All examples create only new components.

**Comment by NikkyAI** [comment]
i tried to use

```
press("unused")
open class ALERT(initialAttributes: Map<String, String>, override val consumer: TagConsumer<*>) :
    HTMLTag("Alert", consumer, initialAttributes, null, false, false),
    HtmlBlockTag {
    var variant: String
        get() = attributeString.get(this, "variant")
        set(newValue) {
            attributeString.set(this, "variant", newValue)
        }
    var dismissible: Boolean
        get() = attributeBoolean.get(this, "dismissible")
        set(newValue) {
            attributeBoolean.set(this, "dismissible", newValue)
        }
}

inline fun RBuilder.alert(variant: String, dismissible: Boolean, block: RDOMBuilder<ALERT>.() -> Unit): ReactElement = tag(block) {
    ALERT(
        attributesMapOf(
            "variant", variant,
            "dismissible", dismissible.toString()
        ), it
    )
}
```

imitation how `kotlin-react-dom` generates te standard html tags
but this just generates the named tags and does not call into the dependency to generate the component

some pointers on how to deal with existing components like react-bootstrap would be very useful

**Comment by piacenti** [comment]
Here is my approach for adding external react components. This is an example from plotly.js (not super type safe but quick to get an idea).

Add externals definition
```
@JsModule("react-plotly.js")
external val plotly: Plotly

external interface Plotly {
    val default:dynamic
}
```
You can just look in the node_modules that react-plotly.js exports default or you can do a println(plotly) somewhere in your code and add a break point so you can examine the object, in my case it was the object `$module$react_plotly_js`. The `default` is the actual React Component definition that you would use like this in react `React.createElement(Plot, props)`
Once you have that this is how you can add it to your component inside your render
```
val props: dynamic = js("""{
    data: [
      {
        type: 'scatter',
        mode: 'lines+points',
        x: [1, 2, 3],
        y: [2, 6, 3],
        marker: {color: 'red'}
      },
      {
        type: 'bar',
        x: [1, 2, 3],
        y: [2, 5, 3]
      }
    ],
    layout: {
      width: 640,
      height: 480,
      title: 'A Fancy Plot'
    }
  }""")
            child(createElement(plotly.default, props))
```
and you get this in your component
![image](https://user-images.githubusercontent.com/7397483/73216270-89775900-410a-11ea-8f8a-cdf82aabbece.png)
