### ISSUE TITLE
Missing "component" prop [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1421]
1. The `ButtonBase` is missing the `component` property. Probably because it needs to inherit from `PropsWithComponent`
    See [ButtonBase](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/ButtonBase/ButtonBase.d.ts) & [OverridableComponent](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/OverridableComponent.d.ts) source
2. The `IconButton` should inherit props from `ButtonBase` (to access e.g. `component`)
    See [IconButton source](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/IconButton/IconButton.d.ts)

**Comment by keith-miller** [comment]
Came here to ask for the same thing

**Comment by keith-miller** [comment]
Got a work around from @turansky on the Kotlin Slack:

```
inline var ButtonProps.component: react.ElementType<*>?
    get() = asDynamic()["component"]
    set(value) {
        asDynamic()["component"] = value
    }
​
//..
	
Button {
    variant = ButtonVariant.contained
    component = react.router.dom.Link
    this as react.router.dom.LinkProps
    to = "roster/${props.position}"
    reloadDocument = false
​
    +"View"
}
```

Again, thank you!

**Comment by aerialist7** [comment]
@turansky, please assign me
