### ISSUE TITLE
fill attribute missing [kotlin-csstype]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1422]
The CSS `fill` attribute is missing.
We currently use it like this:
```
HighlightOff { sx { this.asDynamic().fill = "red" } }
```
See [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill)

**Comment by turansky** [comment]
According documentation `fill` is attribute

**Comment by hofi99** [comment]
My bad, didn't notice this. Thanks!
