### ISSUE TITLE
Flex factory for single argument [kotlin-csstype]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1423]
There's currently no factory for specifying only one argument for the [flex attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/flex).

We defined a temporary helper like:
```
/** flex: [grow], flex-shrink: 1, flex-basis: 0px */
fun Flex(
  grow: FlexGrow
): Flex =
  "$grow".unsafeCast<Flex>()
```

**Comment by turansky** [comment]
What is your use case?

**Comment by hofi99** [comment]
Well, it's quite common to just use e.g.:
```
sx {
          flex = Flex(number(1.0))
}
```
instead of 
sx {
          flex = Flex(number(1.0), number(1.0), 0px)
          // or
          flex = Flex(number(1.0), number(1.0))
}
```

**Comment by turansky** [comment]
Why not like this?

```Kotlin
flex = number(1.0)
```

**Comment by hofi99** [comment]
This would also be sufficient 👍  But is currently not possible.
`Flex` would need to be part of `NumberType` like `FlexGrow` already is.

![Screenshot 2022-04-15 at 16 23 18](https://user-images.githubusercontent.com/62036655/163582431-9ad1b743-cab9-4f9e-8ca8-7100d7a5c625.png)
