### ISSUE TITLE
Non-dynamic AutocompleteRenderInputParams [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1426]
I noticed that some `AutocompleteRenderInputParams` like `InputLabelProps`, `InputProps` and `inputProps` are defined as `dynamic` although they are typed in `Autocomplete`.

![Screenshot 2022-04-14 at 17 21 17](https://user-images.githubusercontent.com/62036655/163421753-cada9113-ebc4-4271-9715-dead66ed8d06.png)

![Screenshot 2022-04-14 at 17 19 21](https://user-images.githubusercontent.com/62036655/163421470-0ee3176e-527e-4516-a588-352595a5624f.png)

**Comment by turansky** [comment]
In your case your can use 
```Kotlin
TextField {
    +params // add all properties from params
}
```

with same effect

**Comment by hofi99** [comment]
That is true :)
These params should be typed nonetheless, right?

**Comment by turansky** [comment]
> These params should be typed nonetheless, right?

Fast check result - we **don't expect strict types** for such properties
It's because you can configure your own components and use any props in described cases

cc @sgrishchenko
