### ISSUE TITLE
Invalid CSS invalidates surrounding properties [kotlin-mui]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1443]
I noticed by accident that when specifying certain invalid CSS for one property the other properties in this layer are invalidated as well in the `sx` block.

E.g.:
```
sx {
      color = Color("(") // Invalid CSS
      paddingTop = 6.px
}
```
creates the following CSS:
```
color: (;padding-top:6px;};};
```
Expected CSS output:
```
// Discard invalid properties
padding: 6px; 
```
or
```
// Let the faulty property be invalid
color: (;
padding: 6px;
```

Note: I tried the same with a closing bracket and the CSS output was as expected:
```
// Let the faulty property be invalid
color: );
padding: 6px;
```

**Comment by turansky** [comment]
In `sx` extension we only construct css properties (JSO).
Validation and resulted CSS - not our responsibility :(
