### ISSUE TITLE
Select nested class [kotlin-csstype]

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#1448]
I noticed that there's currently no way to target nested classes.

Example where it's needed to target `Mui.selected` :
```kotlin
ListItemButton {
        this.selected = selected
        sx {
          // Own helper function
          nested(Mui.selected) {
            backgroundColor = important(rgba(0, 0, 0, 0.08))
          }
        }
        ListItemIcon {
          ...
        }
        ListItemText {
          +"Some text"
        }
      }
```

My local helper function looks like this:
```kotlin
/** Select nested class */
fun PropertiesBuilder.nested(className: ClassName, style: PropertiesBuilder.() -> Unit) {
  (Selector("&.${className}")) {
    style()
  }
}
```

**Comment by turansky** [comment]
What is problem with?
```Kotlin
ListItemButton {
    this.selected = selected
    sx {
        Mui.selected {
            backgroundColor = important(rgba(0, 0, 0, 0.08))
        }
    }
}
```

**Comment by hofi99** [comment]
Without nesting the style is applied to `.Mui-selected` which does not work, while it should be applied as a child of `MuiListItemButton-root`

With nesting:
<img width="568" alt="Screenshot 2022-04-21 at 14 03 15" src="https://user-images.githubusercontent.com/62036655/164454147-7d3a6e91-ac95-434b-a0d1-0da64d475e47.png">

Without nesting:
<img width="567" alt="Screenshot 2022-04-21 at 14 01 49" src="https://user-images.githubusercontent.com/62036655/164453918-8e9ee2e3-b184-49ab-9550-c064d336d576.png">

**Comment by hofi99** [comment]
From the MUI documentation:
https://mui.com/material-ui/customization/how-to-customize/#state-classes

<img width="872" alt="Screenshot 2022-04-22 at 09 51 09" src="https://user-images.githubusercontent.com/62036655/164642937-4797609e-133b-4c80-97af-c9f5bd9d30aa.png">

**Comment by sgrishchenko** [comment]
I guess I see your problem, but to be honest it seems your helper should not be named `nested`, examples of nested selectors:
```css
.parent .child {}
.parent > child {}
```
In your case you add modifier on the same level of component. 
We did not add any helpers for all these cases because CSS selectors has complex syntax and we did not find a was do implement good DSL for them, so you can use you solutions or just string interpolation lake that:
```kt
        sx {
          "&.${Mui.selected}" {
            backgroundColor = important(rgba(0, 0, 0, 0.08))
          }
        }
```

Other examples for nesting:
```
        sx {
          // .parent .child {}
          Mui.selected {
            backgroundColor = important(rgba(0, 0, 0, 0.08))
          }
          
          // .parent > child {}
          "> .${Mui.selected}" {
            backgroundColor = important(rgba(0, 0, 0, 0.08))
          }
        }
```

**Comment by turansky** [comment]
`and` - fine name for helper function :)
Helper is preferred for switching in future

**Comment by hofi99** [comment]
You are right, I was actually referring to compound selectors. My helper should be named `and` or `compound` :)

For common use cases like this I still think it's better to use a helper function than using String interpolation directly

**Comment by turansky** [comment]
Function is preferred in cases like this
