### ISSUE TITLE
react-redux is missing hooks

### ISSUE THREAD

**Issue by steveme** [JetBrains/kotlin-wrappers#149]
[react-redux docs about hooks here](https://react-redux.js.org/api/hooks#using-hooks-in-a-react-redux-app)

- useSelector()
- useDispatch()
- useStore()

**Comment by Leonya** [comment]
A PR would be much appreciated.

**Comment by turansky** [comment]
[Already fixed](https://github.com/JetBrains/kotlin-wrappers/commit/5e52392feaa13eaaeaae3b56e4e3a3179e79a102#diff-40f352c85c7e96b9c40026e83387f3bc9d60762be8c21c8c4fa1b5b964fe13de)

cc @Leonya
