### ISSUE TITLE
Sealed DateAdapter

### ISSUE THREAD

**Issue by lucgirardin** [JetBrains/kotlin-wrappers#1494]
muix.pickers.DateAdapter is sealed and therefore cannot be impemented. 

The problematic change has been introduced in version 337. In 336 one could pass a dynamic function { options: dynamic -> localDateTimeAdapter(options) }

**Comment by turansky** [comment]
@lucgirardin If you know/see expected signature for `DateAdapter` please share it

**Comment by lucgirardin** [comment]
Happy to contribute the Kotlin interface definition for DateAdapter. It is based on https://github.com/dmtrKovalenko/date-io/blob/master/packages/core/IUtils.d.ts (IUtils from date-io is the interface to use). However, I did manually create it so I am not sure if this is in line with the philosophy of the kotlin-wrappers packages, as they seem to be almost all automatically generated.

**Comment by turansky** [comment]
Do you want to write custom adapter?
For which library, if it's not a secret?

**Comment by turansky** [comment]
> 4. You generate the IUtils and DateIOFormats wrappers automatically

This variant + `DateAdapter` as local type alias

**Comment by turansky** [comment]
@lucgirardin Even right now you can extend `DateAdapter`
`Suppress` is preferred, because you will see contact update, when issue will be resolved

**Comment by lucgirardin** [comment]
@turansky The DateAdapter interface is sealed, so if I try to extend it I get a "Inheritance of sealed classes or interfaces from different module is prohibited"!

**Comment by turansky** [comment]
For urgent cases:
```kotlin
@Suppress(
    "SEALED_INHERITOR_IN_DIFFERENT_MODULE",
    "SEALED_INHERITOR_IN_DIFFERENT_PACKAGE",
)
object KlockDateAdapter: DateAdapter
```

:)

**Comment by turansky** [comment]
@lucgirardin Does it work for you?

**Comment by lucgirardin** [comment]
There is progress! However, DateAdapter should be a function, i.e.:
`typealias DateAdapter = dateio.core.IUtils<*>`
should be replaced with
`typealias DateAdapter = (dynamic) -> dateio.core.IUtils<*>`

**Comment by lucgirardin** [comment]
Also irritating is that the props are defined using <*>, which forces one to rely on ugly casting. As an example:
```     
        val (getDate, setDate) = useState(Date())
  
        LocalizationProvider {
            dateAdapter = AdapterDateFns
            CalendarPicker {
                date = getDate.unsafeCast<Nothing?>()
                onChange = { date, selectionState ->
                    setDate(date.unsafeCast<Date>())
                }
            }
        }
```
I think this is a limitation of Kotlin/JS, but if you know a better way this would be appreciated!

**Comment by turansky** [comment]
Say no to ugly casting!

```kotlin
CalendarPicker<CalendarPickerProps<KnockDate>> {
    date = getDate
    onChange = { date, selectionState ->
        setDate(date)
     }
}
```

**Comment by turansky** [comment]
> should be replaced with
```kotlin
typealias DateAdapter = (dynamic) -> dateio.core.IUtils<*>
```

It's looks like constructor
```kotlin
typealias DateAdapter = JsClass<dateio.core.IUtils<*>>
```

**Comment by lucgirardin** [comment]
Compiler complains with `Type argument is not within its bounds: should be subtype of 'ChildrenBuilder'` if I try to use CalendarPicker<CalendarPickerProps<KnockDate>> syntax :-(

**Comment by turansky** [comment]
[Pill](https://github.com/karakum-team/mui-kotlin/blob/6db0fa14f59e192fa96299af71215f056a9d9a89/playground/src/main/kotlin/MyAutocomplete.kt#L11)
