### ISSUE TITLE
in the input , how to capture the on change event and assign the event.target.value to state.text?

### ISSUE THREAD

**Issue by ScottHuangZL** [JetBrains/kotlin-wrappers#15]
I try to capture inputValue assign to state.text field.
However, I am not able get the event.target.value.  How to resolve it?

I try to print the it(event), the target itself is null.

The console print warning "... **Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event**."

How to resolve it? Thanks.

 ```
class Todo(props: TodoProps) : RComponent<TodoProps, TodoState>(props) {
    override fun TodoState.init(props: TodoProps) {
        items = props.items
        text = ""
    }
    override fun RBuilder.render() {
        div {

            input(type = InputType.text, name = "itemText") {
                key = "itemText"

                attrs {
                    placeholder = "Input todo text here..."
                    onChangeFunction = {
                            setState{
                                text = it.target.toString()
                            }
                            console.log(it)
                    }
                }
            }

            +state.text
```

**Comment by Hypnosphi** [comment]
Why do you use `toString()` instead of `value`?

**Comment by Hypnosphi** [comment]
Try this:
```
onChangeFunction = {
    var currentText = (it.target as HTMLInputElement).value
        setState {
            text = currentText
        }
    }
}
```

**Comment by ScottHuangZL** [comment]
IDE did not popup it.target.value , so I try every possibility  :)

**Your solution is work, thanks.**    I can continue my todo samples again.

Could you kindly provide more kotlin-react-app samples, better cover the reactJS tutorial & todo :)

**Comment by DavidWhit** [comment]
wow...  I was also scratching my head on this. I never knew about as HTMLInputElement new to kotlin DSL so I was clueless how to get to the value from target... IDE always showed it wasn't accessible even when I tried. I still thought this way was idiomatic.
```
input {
   attrs {
         // First issue: it was complaining value attrib wasn't set yet (well OF COURSE)
         value = state.textInput

         // Second issue:  value is always the same
         onChangeFunction = {
            setSate{ textInput = value }
         }
}

```
 It didnt make sense I already had access to value and could pass it, but then it never changes even 
with setState. I know in React js it's always accessed via ref callbacks I forget the newer way to do that I think createRef or something

Thanks, is there better documentation somewhere I missed? I'm really enjoying kotlin
