### ISSUE TITLE
How to use memo with functionalComponent?

### ISSUE THREAD

**Issue by gbaldeck** [JetBrains/kotlin-wrappers#151]
The `memo` function imported in kotlin-wrappers/blob/master/kotlin-react/src/main/kotlin/react/Imports.kt is used by React to optimize functional components by only rerendering them when their props change.

In React you wrap your functional component in the `memo` function and then it handles everything else. The `memo` function imported in Imports.kt specifies that it takes an HOC type not a FunctionalComponent type for its single parameter.

After reviewing the code I'm not sure if just changing the single parameter to FunctionalComponent will work. How can we use a FunctionalComponent with the `memo` function?

**Comment by gbaldeck** [comment]
So after some research, I have determined that whichever function is passed to React's `createElement` is the one that needs to be wrapped in `memo`. The `memo` definition should be changed to

```kotlin
external fun <P : RProps> memo(fc: FunctionalComponent<P>): FunctionalComponent<P>
```
I am going to test locally later today or this weekend and will do a pull request for the fix.

**Comment by Leonya** [comment]
You're right, thanks for the suggestion, I've already applied it.
