### ISSUE TITLE
backgroundImage not working properly in kotlin-styled

### ISSUE THREAD

**Issue by francos** [JetBrains/kotlin-wrappers#152]
I'm trying to set a background image on a `div` tag and the `backgroundImage` property doesn't seem to work as it should.

This is the code I have in Kotlin:

```kotlin
styledDiv {
    css {
        backgroundImage = kotlinx.css.Image("image_name.png")
    }
}
```

this is converted to the following CSS:

```css
background-image: image_name.png;
```

which is not valid.

If I change the CSS to:

```css
background-image: url("image_name.png");
```

then the image is shown properly.

A workaround for this is to use:

```kotlin
styledDiv {
    css {
        background = "url(\"image_name.png\")"
    }
}
```

however, I think that is kinda hacky.

Am I using `backgroundImage` incorrectly? I haven't been able to fund the equivalent of `url()` in the Kotlin lib.

**Comment by Leonya** [comment]
Just write `backgroundImage = Image("url('image_url')")`

**Comment by francos** [comment]
Thanks for the response @Leonya. 

That sounds like more of a workaround rather than a solution as it is not type-safe.

Since there doesn't seem to be a reason for the `kotlinx.css.Image()` to work without the `url()`, wouldn't it make sense that it adds the "url()" around the string it receives?

Or if you want to keep backwards compatibility a new `kotlinx.css.ImageUrl()` function would work.

Let me know what you think, if you approve of any of those solutions I can look into implementing them and creating a PR.

**Comment by Leonya** [comment]
> Since there doesn't seem to be a reason for the kotlinx.css.Image() to work without the url(), wouldn't it make sense that it adds the "url()" around the string it receives?

No, it wouldn't. The `background-image` property accepts all kinds of values, url is by far not the only one. See the "Formal syntax" section here: https://developer.mozilla.org/en-US/docs/Web/CSS/background-image

**Comment by francos** [comment]
Oh I see, I was not aware of that as I'm pretty new to CSS. Thanks for the info @Leonya 👍
