### ISSUE TITLE
React: No value passed for parameter 'props' when using FunctionalComponent

### ISSUE THREAD

**Issue by francos** [JetBrains/kotlin-wrappers#154]
I'm trying to use `FunctionalComponent` but when trying to use the component I get the error:

```
No value passed for parameter 'props'
```

even though I'm using `RProps` for this component and I don't want to pass any properties.

The only way I found to do this is to use `jsObject {}`

```kotlin
val exampleComp = functionalComponent<RProps> { ... }

exampleComp(jsObject { })
```

but this seems very hacky.

Is there a better way to do this?

**Comment by gonozalviii** [comment]
There is an overload of the child() function that can be used:

```
import react.child

child(exampleComp)
```

**Comment by francos** [comment]
Thanks for the info @gonozalviii :)

I totally missed that, as I had made the assumption that functional components could be built directly as if calling a normal function rather than having to use the `child()` builder like we do for class components, but now that you mentioned it I think it makes sense that they follow the same rules.
