### ISSUE TITLE
Status of kotlinjs and the future of kotlin-wrappers

### ISSUE THREAD

**Issue by frhack** [JetBrains/kotlin-wrappers#1546]
Hi,
I really like the ability to develop React applications in type safe style in Kotlin.
I'm investing time in this technology and it seems very powerful and quite mature and complete.

But I need to be shure that I'm choosing a technology that will stay. 

It's not clear to me what is the status of kotlinjs compiler and what will be the future for the kotlin-wrappers library when kotlinjs will upgrade to the new IR compiler.

What is the status ?

thanks

**Comment by Leonya** [comment]
This project is being actively maintained. Whatever updates are coming to Kotlin, we will sync up with them.
