### ISSUE TITLE
how to map TypeScript union types

### ISSUE THREAD

**Issue by frhack** [JetBrains/kotlin-wrappers#1549]
Hi,
how can we map TypeScript union types in kotlinjs ?

For example in ReactQuery there are signatures like this:

```
queryClient.setQueryData(queryKey, updater)

queryKey: QueryKey
updater: TData | (oldData: TData | undefined) => TData
```

(I asked ReactQuery to avoid such signatures: https://github.com/TanStack/query/issues/3740 )

**Comment by frhack** [comment]
In the file https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-query/src/main/generated/react/query/queryClient.core.kt we need to add another method


```kotlin
    open fun <TData> setQueryData(
        queryKey: QueryKey,
        updater: TData,
        options: SetDataOptions = definedExternally,
    ): TData
```

https://react-query.tanstack.com/reference/QueryClient#queryclientsetquerydata

**Comment by turansky** [comment]
Usually we use more flexible signature.
In described case it will be:
```kotlin
updater: (oldData: TData?) -> TData
```

**Comment by frhack** [comment]
> Usually we use more flexible signature. In described case it will be:
> 
> ```kotlin
> updater: (oldData: TData?) -> TData
> ```
> 
> In common initial signature is fine. Looks like it will work in Kotlin, when unions types will be supported.

Indeed the provided signature is more general and so to pass a simple value I just passed a lambda that returns that value

I got an answer from ReactQuery team:

> 
> in v4, the signature has been changed to:
> 
>` updater: (oldData: TData | undefined) => TData | undefined`

https://github.com/TanStack/query/issues/3740

**Comment by turansky** [comment]
@frhack Is issue can be closed?

**Comment by frhack** [comment]
> @frhack Is issue can be closed?

ok thanks

**Comment by turansky** [comment]
@frhack You can close it as author (and others, which solved for you)
