### ISSUE TITLE
Publish to JCenter

### ISSUE THREAD

**Issue by petehayes** [JetBrains/kotlin-wrappers#155]
Hi,

We would like to use kotlin-wrappers but our infrastructure team prefers open source projects that are delivered through jcenter.  Is there a reason these projects are not made available via jcenter?  It would seem bintrary offers a simple integration with jcenter so it should be easy to enable.

Thanks,
Pete

**Comment by Leonya** [comment]
I have submitted the request to publish to JCenter, hope it's approved soon.
