### ISSUE TITLE
Recommended way to implement Component#render with ChuildrenBuilder API

### ISSUE THREAD

**Issue by sanyavertolet** [JetBrains/kotlin-wrappers#1584]
In kotlin-react-legacy there is a good component `RComponent` that has an abstract method `RBuilder.render()` which allows an easy and convenient way to render a view.
While migrating to the new `ChildrenBuilder` API, we found out that a lot of methods of new API have `internal` scope and don't have any similar wrappers.

Is there any implementation of `Component#render()` that would allow to render a view with `ChildrenBuilder`?

**Comment by akuleshov7** [comment]
@turansky @Leonya if you are still there - could you please help with that?

**Comment by turansky** [comment]
> Is there any implementation of Component#render() that would allow to render a view with ChildrenBuilder?

As quick solution you can use `Fragment.create`

**Comment by sanyavertolet** [comment]
> > Is there any implementation of Component#render() that would allow to render a view with ChildrenBuilder?
> 
> As quick solution you can use `Fragment.create`

Thank you!
Is it planned to implement sort of `CComponent` that would do the same as `RComponent` but with `ChildrenBuilder` cause now it looks like a temporary workaround?

**Comment by turansky** [comment]
It's planned to remove `ChildrenBuilder` at all :)
