### ISSUE TITLE
How do i load Bootstrap CSS library in kotlin-react app

### ISSUE THREAD

**Issue by cchunduri** [JetBrains/kotlin-wrappers#162]
I want to use Bootstrap CSS library in my Kotlin-React app which I've created using 

`npx create-react-kotlin-app my-app`

I tried the way as per the below blog post 

[https://medium.com/front-end-weekly/how-to-add-sass-or-scss-to-create-react-app-c303dae4b5bc](https://medium.com/front-end-weekly/how-to-add-sass-or-scss-to-create-react-app-c303dae4b5bc)

But no use. Could you please help me to solve this issue

**Comment by gonozalviii** [comment]
Place a .js file inside a 'webpack.config.d folder in your project root. Configure your loaders there.

```
config.module.rules.push({
    test: /\.css$/,
    use: ["style-loader", "css-loader"]
});
config.module.rules.push({
    test: /\.(woff(2)?|ttf|eot|svg|gif|png|jpe?g)(\?v=\d+\.\d+\.\d+)?$/,
    use: [{
        loader: 'file-loader',
        options: {
            name: '[name].[ext]',
            outputPath: 'fonts/'
        }
    }]
});
```

Then add an import inside your main() method:
`    require("antd/dist/antd.css")
`
where antd is located inside 'node_modules'

**Comment by cchunduri** [comment]
@gonozalviii thank you very much I’m able to import css now.
