### ISSUE TITLE
Generating new libraries?

### ISSUE THREAD

**Issue by sgammon** [JetBrains/kotlin-wrappers#1645]
Hello Kotlin Wrappers authors,

I love this library, thank you for your hard work!

I was wondering, how would one go about generating a wrapper for a library which doesn't have one yet?

In some cases the libs we want are popular and might make it into this repo on their own. But in other cases we have older libraries which may or may not ship TS and which JetBrains may have no interest in supporting long term.

Is there a way we could generate wrappers for such libraries privately, or, in the case of libraries that are popular and might be supported, a way to generate wrappers for this repo?

Thank you in advance for any guidance and apologies if this has been asked before. I looked but couldn't find any PR examples or issues :)

**Comment by turansky** [comment]
Hi Samuel!

> I love this library, thank you for your hard work!

Thank you :)

> I was wondering, how would one go about generating a wrapper for a library which doesn't have one yet?

We write generator in such cases. Old generators you can find in [types-kotlin](https://github.com/karakum-team/types-kotlin) project (`buildSrc` folder).
Old style generators for `@tanstack/react-table` and `@tanstack/react-virtual` were written in previous month.

> Is there a way we could generate wrappers for such libraries privately, or, in the case of libraries that are popular and might be supported, a way to generate wrappers for this repo?

We have plans to use new generator (in development) to simplify generation for new libraries.
Node - first test target for new generator.

@sgammon In any case it has sense to provide list of libraries, which you want to use in Kotlin/JS.

cc @sgrishchenko

**Comment by sgammon** [comment]
@turansky thank you for the guidance! I will take a look at the old generators and keep an eye out for the new ones too.

with regard to specific libraries, we would be looking for:
- [Lit](https://lit.dev) (v2 - latest - likely to make it in eventually as adoption increases)
- [gRPC Web](https://github.com/grpc/grpc-web) or perhaps the newer [Connect-Web](https://github.com/bufbuild/connect-web)
- [Firebase](https://github.com/firebase/firebase-js-sdk) would be really cool

mainly, filling out the transport layer with tools like gRPC or Firebase would be a powerful addition to the Kotlin/JS ecosystem, especially considering [protobuf](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#protobuf-experimental) support in KotlinX. i am working on a [framework](https://github.com/elide-dev/v3) which plans to support gRPC-Web and Connect-Web natively which is the motivation behind those. with Kotlin/JS support for these, we would be able to exchange strongly typed objects between the server and browser in all Kotlin with very little overhead.

obviously Kotlin Data objects are an alternative, but aren't always available for older systems which haven't yet undergone a source rewrite into Kotlin.

with regard to older libraries, we'd want to generate wrappers for [Polymer](https://github.com/polymer/polymer) and the set of associated elements ([paper](https://www.webcomponents.org/collection/PolymerElements/paper-elements), [iron](https://www.webcomponents.org/collection/PolymerElements/iron-elements), and so on). i would be very surprised if these landed here naturally, and not offended by that at all, considering they are all deprecated 😅 

thank you again for your response and i'll continue to stay involved where applicable.
