### ISSUE TITLE
In kotlin-react-dom, in a Date typed Input, how can I set a min and max dates?

### ISSUE THREAD

**Issue by jfontsaballs** [JetBrains/kotlin-wrappers#1649]
In TypeScript I can do this:

```typescript
import * as React from 'react';

export default function App() {
  return (
    <div>
      <input type="date" min="2022-08-25" max="2022-08-28"/>
    </div>
  );
}
```

The `InputHTMLAttributes` interface has a `min` property, but it is of type `Double?` so I can't use it with a date.

If it happens to be a bug, please provide a workaround until a fix becomes available.

Thank-you in advance.

**Comment by jfontsaballs** [comment]
Already found a workaround:

```kotlin
var myDate : LocalDate = useState(...)
val myMinDate : LocalDate = ...
input {
    type = InputType.date
    value = myDate.toString()
    onChange = { e -> myDate = LocalDate.parse(e.target.value) }
    val t: dynamic = this
    t.min = myMinDate.toString()
}
```

Is it supposed to be done this way, or is there a better way?

**Comment by turansky** [comment]
Also you can use `valueAsDate`, whan you read selected `Date`
