### ISSUE TITLE
React: how to load components lazily for code splitting?

### ISSUE THREAD

**Issue by andrew-k-21-12** [JetBrains/kotlin-wrappers#1660]
There is [react.lazy { ... }](https://github.com/JetBrains/kotlin-wrappers/blob/6faa02c7272611ef9c9a58bb3fa3c95277296fc9/kotlin-react-core/src/main/kotlin/react/lazy.kt#L9) which seems to be exactly for this, but all my attempts to make it work do no succeed: no separate bundles are getting created.

Are there any samples on lazy loading / code splitting in React for Kotlin? Could only find a couple of issues with unclear result states. Also, there were some mentions that it's only possible to split when using multiple Gradle modules (if got it right). [[1]](https://youtrack.jetbrains.com/issue/KT-20679), [[2]](https://github.com/fluidsonic/kjs-chunks).

So is it possible at all to do lazy loading? If yes then how?

**Comment by andrew-k-21-12** [comment]
Well, the short answer is - yes, it's possible. But unfortunately it's clunky.

Did everything with minor changes in the way as it's done in https://github.com/fluidsonic/kjs-chunks. To make [react.lazy { ... }](https://github.com/JetBrains/kotlin-wrappers/blob/6faa02c7272611ef9c9a58bb3fa3c95277296fc9/kotlin-react-core/src/main/kotlin/react/lazy.kt#L9) work, we need to export components to be lazily loaded as `default`:

```kotlin
@JsExport
@OptIn(ExperimentalJsExport::class)
@JsName("default")
val myDynamicComponent = FC<Props> { ... }
```

Their dynamic loading requires something as following:

```kotlin
external fun <T> import(path: String): Promise<T>

val lazyMyDynamicComponent = lazy<Props> {
    import<dynamic>("./my-project-name-my-dynamic-module")
        .then<dynamic> { it.default }
}
```

After that it's possible to set `lazyMyDynamicComponent` to some `Route` (using `Suspense` as well).

Hope there will be easier ways to do this some day.

**Comment by turansky** [comment]
`import` method already declared in wrappers

**Comment by andrew-k-21-12** [comment]
@turansky, thanks for the hint! Will include [kotlin-js](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-js) to avoid boilerplate then (guess it won't increase the bundle size as there is DCE).
