### ISSUE TITLE
kotlin-react-beautiful-dnd not implemented

### ISSUE THREAD

**Issue by batson-j** [JetBrains/kotlin-wrappers#1721]
Hello, thank you so much for providing these libraries!

I noticed that `kotlin-react-beautiful-dnd` is not actually implemented and was wondering if it is currently being worked on or if there are plans to in the future. 

https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-react-beautiful-dnd

**Comment by Windrushfarer** [comment]
Hi @batson-j, thanks for your kind words. We have been working on them and will put all the code soon.

**Comment by batson-j** [comment]
Awesome - looking forward to checking it out. Thanks again!
