### ISSUE TITLE
"Invalid property id" when using Cursor type in CSS

### ISSUE THREAD

**Issue by AlexCouch** [JetBrains/kotlin-wrappers#1782]
When using cursor property in a 'css' block with any Cursor.* property will result in a build fail. This is because the javascript that is attached to the external class uses the property `default: 'default'` [here](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-csstype/src/main/generated/csstype/Cursor.kt#L11). `default` is a reserved word in javascript so it cannot be used. There is only one workaround that I can find which is to just link a css file to be used on top of the use of the css block, or to just use raw css in the server side html to be served.

```kotlin
fun HTML.index(){
    ...
    style{
        unsafe{
            +"""
                input{
                    cursor: pointer;
                }
            """
        }
    }

}
```

Error: `at /home/alex/ktor-samples/minimal-csstype-crash/build/js/packages/minimal-csstype-crash/kotlin/minimal-csstype-crash.js (80, 185): invalid property id`

This changes based on what code is used. Adding `cursor: Cursor.pointer` to the input -> css block in the basic react welcome example via the Intellij project generator will yield this exact error.

**Comment by turansky** [comment]
`default` is fine :)
<img width="236" alt="Screen Shot 2022-09-08 at 12 18 38 AM" src="https://user-images.githubusercontent.com/9942723/188982690-b59afdfc-52e7-48e1-baf5-7bba9e4a6283.png">

**Comment by turansky** [comment]
For Legacy DCE [`legacy-union`](https://plugins.gradle.org/plugin/io.github.turansky.kfc.legacy-union) plugin required

Related - #1077

**Comment by turansky** [comment]
For Legacy DCE [`legacy-union`](https://plugins.gradle.org/plugin/io.github.turansky.kfc.legacy-union) plugin required

Related - #1077

**Comment by AlexCouch** [comment]
> For Legacy DCE [`legacy-union`](https://plugins.gradle.org/plugin/io.github.turansky.kfc.legacy-union) plugin required
> 
> Related - #1077

Oh my bad I see it, thank you. I had looked around and must've missed that part.
