### ISSUE TITLE
Media-Queries using emotion/csstype

### ISSUE THREAD

**Issue by Patrotus** [JetBrains/kotlin-wrappers#1783]
We are currently in the progress of upgrading our porject from `kotlin-styled` and `kotlin-react-legacy` to `kotlin-emotion`  and `kotlin-react`.

Previously the CSS was defined by the CSSBuilder and we were able to include a media-query by 
```kotlin
media("(max-width: 1224px)") {
  // do stuff
 }
```

How can we achieve the same behavoiur by using the `PropertiesBuilder` from `csstype`.

**Comment by turansky** [comment]
Current plan - use `Selector`s instead.

1. With constant
```kotlin
val DESKTOP = Selector("@media(max-width: 1224px)")

...

css {
    DESKTOP {
        // your stylization
    }
}
```

2. Without constant (one time usage)
```kotlin
css {
    "@media(max-width: 1224px)" {
        // your stylization
    }
}
```

In both cases it will be possible to use language injection (CSS), provided by IDE plugin.

Example:
<img width="421" alt="Screen Shot 2022-09-13 at 3 59 58 PM" src="https://user-images.githubusercontent.com/9942723/189907540-ffa26a81-e018-44aa-8d21-c527c1232990.png">

**Comment by turansky** [comment]
Language injection, which we want provide by IDE plugin
<img width="420" alt="Screen Shot 2022-09-13 at 4 18 27 PM" src="https://user-images.githubusercontent.com/9942723/189911470-6cb1543f-a285-4488-bbfb-8db78c1d4d86.png">
