### ISSUE TITLE
Passing custom attributes to kotlin-react dsl 

### ISSUE THREAD

**Issue by p-netm** [JetBrains/kotlin-wrappers#1788]
How do I pass custom data-* attributes in `kotlin-react`. 

for instance how do I write this in `kotlin-react`-dsl

```html
<article data-index-number="12314" ></article>
```

**Comment by turansky** [comment]
Now:
```kotlin
var HTMLAttributes<*>.dataIndexNumber: Int?
    get() = asDynamic()["data-index-number"]
    set(value) {
        asDynamic()["data-index-number"] = value
    }
```

In future:
```kotlin
@JsName("data-index-number")
external var HTMLAttributes<*>.dataIndexNumber: Int?
```

**Comment by turansky** [comment]
Related discussion - #434

**Comment by edpichler** [comment]
> Now:
> 
> ```kotlin
> var HTMLAttributes<*>.dataIndexNumber: Int?
>     get() = asDynamic()["data-index-number"]
>     set(value) {
>         asDynamic()["data-index-number"] = value
>     }
> ```
> 
> In future:
> 
> ```kotlin
> @JsName("data-index-number")
> external var HTMLAttributes<*>.dataIndexNumber: Int?
> ```

Future when @turansky ?

**Comment by turansky** [comment]
It depends on Kotlin version, which you use/need.
For K2 it's possible without IDEA plugin.
For K1 IDEA plugin will be required - it's what we want to avoid.
