### ISSUE TITLE
Ability to inject and retrieve class name

### ISSUE THREAD

**Issue by matejdro** [JetBrains/kotlin-wrappers#179]
Some 3rd party react components allow user to customize their css via `className` property. I want to create the css class in `kotlin-styled` and then put the name of that class into custom component.

I've not found a good way to do this. At the moment I'm doing it like this:

```kotlin
object A  : StyleSheet("A", isStatic = true) {
    val B by css { ... }
}
```

I'm manuallying using `A-B` name and I also have to manually inoke this method to make sure it is added to css via `A.B.invoke(CSSBuilder())`.

**Comment by Leonya** [comment]
Yes, this is how you set a class name. To retrieve a class name you could write

```
A.getClassName { it::B }
```

**Comment by matejdro** [comment]
Ah I see. Thanks!

**Comment by matejdro** [comment]
Actually this does not seem to be the complete solution. While I can get the class name, css of `B` does not appear  to get injected into the site since it's never used.

**Comment by Leonya** [comment]
To override some externally-defined CSS using a Kotlin DSL you can do something like this:

```
val styles = CSSBuilder(allowClasses = false).apply {
    ".external-class-name" {
        ...
    }
}

StyledComponents.injectGlobal(styles.toString())
```

**Comment by matejdro** [comment]
No, I want to inject my own css into the page.

**Comment by Leonya** [comment]
It's done like this:

```
css {
    +A.B
}
```

Where `css` is an extension function of `StyledBuilder<*>`, `CustomStyledProps`, or `<P : CustomStyledProps> RElementBuilder<P>`

**Comment by matejdro** [comment]
Right, but I don't want to use this in any kotlin css statement. I just want to use it in custom component that only accepts `className`
