### ISSUE TITLE
Add "kotlin-extensions" to kotlin-wrappers-bom?

### ISSUE THREAD

**Issue by jschneider** [JetBrains/kotlin-wrappers#1804]
Suddenly a dependency version to "org.jetbrains.kotlin-wrappers:kotlin-extensions:1.0.1-pre.388" popped up in my versions.properties file.

Is it possible to configure the version number for `kotlin-extensions` in the `kotlin-wrappers-bom`, too?

**Comment by turansky** [comment]
It was removed form BOM specially as deprecated.
Most functionality you can find in `kotlin-js` wrappers subproject.
Which types/functions you need from `kotlin-extensions`?

**Comment by jschneider** [comment]
I see. Didn't realize the project has been deprecated.
