### ISSUE TITLE
How to use "Component"-Elements

### ISSUE THREAD

**Issue by h-mergel** [JetBrains/kotlin-wrappers#1809]
Hi,

I am upgrading my project to the current kotlin-react version and having trouble to migrate a piece of code, where I am using an external library.

Old code:
```
@file:JsModule("react-select")
@file:JsNonModule

[...]

@JsName("default")
external class RSelect : Component<RSelectProps, RSelectState> {
    override fun render(): ReactElement<RSelectProps>?
}
```

```
fun RBuilder.rSelect(handler: RSelectProps.() -> Unit) = child<RSelectProps, RSelect> {
    attrs {
        handler()
    }
}

```

Is there a way to use Components within ChildrenBuilder?

**Comment by turansky** [comment]
Do you need `react-select` declarations?

**Comment by h-mergel** [comment]
It works now. I changed the super class to ComponentClass (instead of Component).

```
@JsName("default")
external val RSelect: ComponentClass<RSelectProps>
```

**Comment by turansky** [comment]
`R` prefix is redundant in declarations
Common recomendation -  use original names where it's possible

**Comment by h-mergel** [comment]
Thank you, will do!

**Comment by turansky** [comment]
@h-mergel React Select wrappers - #1824

**Comment by h-mergel** [comment]
Thank you, @turansky, that helps a lot. 
StylesConfig is missing some attribues, though (e.g. dropdownIndicator). Was that intended?

**Comment by turansky** [comment]
> StylesConfig is missing some attribues, though (e.g. dropdownIndicator). Was that intended?

It's manual declarations - missed and outdated parts are expected.
Feel free to make a pull request.
