### ISSUE TITLE
Are components that muix.pickers has relevant?

### ISSUE THREAD

**Issue by Star-dev325** [JetBrains/kotlin-wrappers#1853]
I was trying to implement DatePicker from muix.pickers.
<img width="835" alt="Screen Shot 2022-11-17 at 2 53 12 PM" src="https://user-images.githubusercontent.com/101224191/202545803-1f08fd01-59a8-47ae-b389-d5404d1e54c1.png">

<img width="884" alt="Screen Shot 2022-11-17 at 2 53 05 PM" src="https://user-images.githubusercontent.com/101224191/202545883-a81e68e9-129e-4932-8bf2-b08e5074f841.png">

But after importing this from `muix.pickers`, I was seeing that this DatePicker component doesn't have needed props.
I got into the this source file, but it there's nothing declared props for this component.

<img width="848" alt="Screen Shot 2022-11-17 at 2 57 28 PM" src="https://user-images.githubusercontent.com/101224191/202546404-94f3aa8a-42de-44d9-94b9-58c996cf7898.png">

What I want to do is to use all of the date or time picker components without any props missing as the other components imported from `mui.material.*` work very well. But only these date or time pickers don't have expected props type in its js->kotlin libraries.

Is there anything coming soon for muix pickers components or those components are good that I didn't realize?

I tried with `TextField` component like below code.
```
TextField {
            sx {
                width = 40.pct
            }
            label = ReactNode("DatePicker lable")
            defaultValue = "placehold text"
            type = InputType.date
            variant = FormControlVariant.outlined
        }
```

But the result is ugly. The label and placeholder text are overlapped.
<img width="256" alt="Screen Shot 2022-11-17 at 3 02 54 PM" src="https://user-images.githubusercontent.com/101224191/202549443-406ca8c9-0059-4519-9991-564231a1db52.png">
(after focused)
<img width="255" alt="Screen Shot 2022-11-17 at 3 03 06 PM" src="https://user-images.githubusercontent.com/101224191/202549478-45c8caf8-95b7-4019-9d48-ed6346c8cbd9.png">

Can anyone help me regarding this one if it's possible to use pickers from muix. Or I would really appreciate any advise or any recommendations for alternative approaches.

Thank you!

**Comment by Star-dev325** [comment]
Maybe in this way it's possible.
```
TextField {
    sx {
        width = 40.pct
    }
    label = ReactNode("Start Day")
    variant = FormControlVariant.outlined
    onClick = {
        val target = it.target as dom.html.HTMLInputElement
        target.type = InputType.date.toString()
    }
    onBlur = {
        val target = it.target as dom.html.HTMLInputElement
        target.type = InputType.text.toString()
    }
}
```

But to be perfect for all mui-components, we need a corresponding proper wrapper.
Can anyone provide how to import and use `like-Picker` components from muix?

**Comment by turansky** [comment]
Current recommendation - [use extensions](https://github.com/karakum-team/kotlin-mui-showcase/blob/main/src/main/kotlin/team/karakum/common/MissedWrappers.kt)
When `Props` will be fixed it will be transparent, which extensions can be removed - you will see compilation warnings.
