### ISSUE TITLE
How to convert values for the style properties?

### ISSUE THREAD

**Issue by andrew-k-21-12** [JetBrains/kotlin-wrappers#1854]
In some cases it seems like an overkill to produce dynamic CSS to lay all elements out properly.

Looking through the issues here could not find anything what could help in avoiding clunky type casts and units hardcoding like:
```kotlin
div {
    style = jso {
        height = "${headerHeight}px".unsafeCast<Height>()
    }
}
```

The question is - are there any builders or helper functions to do the thing above in a cleaner manner? The first idea coming to mind - is to write some extension for the `LinearDimension` to convert it to the target style type shorter:
```kotlin
fun <T> LinearDimension.to(): T = value.unsafeCast<T>()

style = jso {
    height = headerHeight.px.to<Height>()
}
```

Are there any better solutions available?

**Comment by andrew-k-21-12** [comment]
Just casting the `LinearDimension`'s `value` seems to be good enough for me, no help needed.

**Comment by turansky** [comment]
It's recommended to use `csstype.px` extensions instead.
`kotlin-csstype` used in React wrappers. It's also recommended for MUI wrappers.

**Comment by andrew-k-21-12** [comment]
Yes, this seems much better rather than doing separate casting or using additional extension functions, thank you!
