### ISSUE TITLE
kotlin-react-beautiful-dnd artefacts are empty

### ISSUE THREAD

**Issue by TimLavers** [JetBrains/kotlin-wrappers#1857]
Download org/jetbrains/kotlin-wrappers/kotlin-react-beautiful-dnd/13.1.0-pre.440 sources jar.
There is a META-INF directory but no code.
None of the artefacts that I have tried to use have had any code in them.
So this library is not usable.

**Comment by mikedawson** [comment]
I have in the meantime made a React wrapper for the slightly simpler react-easy-sort library: 

https://gist.github.com/mikedawson/0cb46de72daf142bb6069b9bc8692583

It doesn't provide all the functionality of react-beautiful-dnd, but it does provide enough for a working sortable list.

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by Leonya** [comment]
Wow, thanks
