### ISSUE TITLE
How to use receivers with new Kotlin react wrapper?

### ISSUE THREAD

**Issue by piacenti** [JetBrains/kotlin-wrappers#1858]
With kotlin-react-legacy I am able to create some wrapper extensions such as this to have a simple preconfigured div
```kotlin
fun RBuilder.formGroup(classes: String = "", body: RDOMBuilder<DIV>.() -> Unit) {
    div(classes = FORM_GROUP + classes) {
        this.body()
    }
}
```
For the new wrapper I'm not sure what the approach is to do the same thing. I tried the following
```kotlin
fun  ChildrenBuilder.formGroup(classes: String = "", body: ChildrenBuilder.() -> Unit)  {
    div {
        className = ClassName(FORM_GROUP + classes)
        this.body()
    }
}
```
while that may seem like it would work it fails because you don't actually have access to all properties that are now separate between props and DOM attributes. If I try to call it like this:
```kotlin
formGroup {
    id = "test"
    +"text"
}
```
it will not resolve `id` since it is not a member of `ChildrenBuilder`. I can fix that by changing the parameter receiver to `HTMLAttributes<HTMLDivElement>`, however, I then can't use `ChildrenBuilder` functionality anymore. 

The type hint given by IntelliJ inside `div { }` is `{ChildrenBuilder & HTMLAttributes<HTMLDivElement> & Props}`. There is no straightforward way to get a parameter receiver to have that intersection of types. `ChildrenBuilder` can't be implemented because it is a sealed interface (can't be implemented outside module). I also tried to wrap the logic with a functional component but it doesn't seem to make it any better. Basically instead of one receiver parameter I'd have to pass 3, one for each type (ChildrenBuilder, HTMLAttributes<HTMLDivElement> and Props) for proper type safety in the function as well as from the caller.

What is the simplest way to accomplish something like what I did above using kotlin-react-legacy? is there any parameter receiver that could work with that type mix going on inside the div or any of the new base components api?

**Comment by piacenti** [comment]
Looks like this functional component gets close to the original intent although not quite the same
```kotlin
fun ChildrenBuilder.combinePropsWith(other: Any) {
    combineAttributes(other)
}
fun Any.combineAttributes(other: Any) {
    Object.assign(this, other)
}
val formGroup = FC<HTMLAttributes<HTMLDivElement>>{
    div {
        combinePropsWith(it)
        className = ClassName(FORM_GROUP + it.className?:"")
    }
}
```

**Comment by turansky** [comment]
1. Current recommendation - avoid `ChildrenBuilder` extensions where it's possible.
    In most cases (in your example too) it's possible.

2. To add more `Props` you can use `+` operator
https://github.com/karakum-team/mui-kotlin/blob/1f0bd483ffe2a8d71bf0da021ff56e05d4c36cbf/playground/src/main/kotlin/MyAutocomplete.kt#L18-L23
