### ISSUE TITLE
Improved changelogs

### ISSUE THREAD

**Issue by Sejsel** [JetBrains/kotlin-wrappers#1864]
**Is your feature request related to a problem? Please describe.**

Currently there are barely any changelogs (none between `pre-302` and `pre-452`, 6 months worth of changes) and it is not clear that the repository is in the middle of a massive package reorganization. When updating from `pre-332` to `pre-444` in our project, it took me a quite a bit of time to figure out what is happening with this repository, and these wrappers are fairly critical to using Kotlin/JS with react and other libraries.

There were quite a few undocumented breaking changes. Wrappers from this repository stopped accepting `org.w3c.dom` elements, many APIs now exist in a different package (timers, form data, events...). A new package structure was introduced and that introduces a need to do unsafe casts to work with Kotlin/JS wrappers that are not a part of this repository.

It is not clear whether this package structure is to be expected within the standard lib in the future, or if it's only a thing in this repository. It is also not clear whether other wrappers should use the types from this repository in the future or if that is not a good idea.

**Describe the solution you'd like**

I think having at least a short paragraph describing the state of the repository in the README (and making sure it is up-to-date) and a reasonably up-to-date changelog with breaking changes would go a long way towards improving the situation.

**Comment by turansky** [comment]
> it is not clear that the repository is in the middle of a massive package reorganization

`pre.453` (coming soon) recommended as stable 

> When updating from `pre-332` to `pre-444`

It's big migration in any case :(
More regular updates recommended

> It is not clear whether this package structure is to be expected within the standard lib in the future

`kotlin-browser` - Browser API declarations with regular updates, which can be used instead of `stdlib-js`

>  It is also not clear whether other wrappers should use the types from this repository in the future or if that is not a good idea.

It's good idea, especially for progressive libraries, which use latest Browser API! :)

**Comment by lucgirardin** [comment]
> It's big migration in any case :(

While this may look daunting on first sight, the migration of my entire codebase went pretty smoothly. The only annoyance I stumbled on was with incompatible types required by some functions, but it was easy to work around these issues using extension functions, e.g.:

 ```
val KeyboardEvent.keyCode
    get() = asDynamic().keyCode

fun SVGGeometryElement.isPointInFill(point: DOMPoint): Boolean {
    return isPointInFill(point.unsafeCast<DOMPointInit>())
}

fun SVGGeometryElement.isPointInStroke(point: DOMPoint): Boolean {
    return isPointInStroke(point.unsafeCast<DOMPointInit>())
}

fun DOMPoint.matrixTransform(matrix: DOMMatrix): DOMPoint {
    return matrixTransform(matrix.unsafeCast<DOMMatrixInit>())
}
```
