### ISSUE TITLE
Type mismatch: inferred type is org.w3c.dom.Element but dom.Element was expected

### ISSUE THREAD

**Issue by Rchrdlss3** [JetBrains/kotlin-wrappers#1865]
Hello, new Kotlin user here and I'm trying to create a React application with it. I've recently noticed updates were made yesterday and tried adjusting my code accordingly. I was using kotlinWrappersVersion 1.0.0-pre.410 and updated to 453 for the latest changes and received this error
```Type mismatch: inferred type is org.w3c.dom.Element but dom.Element was expected```
My code:
```
import kotlinx.browser.document
import react.create
import react.dom.client.createRoot

fun main() {
    val container = document.getElementById("root") ?: error("Couldn't find root container!")
    createRoot(container).render(AppRouter.create{})
}
```
[I followed this tutorial for assistance in creating my app](https://kotlinlang.org/docs/js-react.html)

I went back down 410 and used versions up all the way to .430 for I noticed version 431 is when I received the same error.

Is there anyway to work around this error?

**Comment by Exsite123** [comment]
Needs to be replaced
`import kotlinx.browser.document`
on
`import browser.document`

**Comment by ikovalyov** [comment]
Hi @Exsite123 .
At which package is this module located?
Thanks.

**Comment by realdavidvega** [comment]
> Hi @Exsite123 . At which package is this module located? Thanks.

I know it's a bit late, but just ran into this problem when using `pre.525` of `kotlin-browser` and `react-dom`.

Solved it by replacing `import kotlinx.browser.document` with `import web.dom.document`
