### ISSUE TITLE
Missing `require` and `requireAll` declarations

### ISSUE THREAD

**Issue by supertote** [JetBrains/kotlin-wrappers#1867]
**Is your feature request related to a problem? Please describe.**

Now that **kotlin-extensions** has been archived we are missing the **require** and **requireAll** declarations found in **CommonJS.kt**.
We use them in our main.kt to automatically include external CSS files from some NPM dependencies. 
An equivalent does not seem to be available in any of the other kotlin wrappers. 

**Describe the solution you'd like**

Some way to require arbitrary files to be included in the final webpack bund'e from the kotlin sources.

**Comment by turansky** [comment]
`require`, which I have locally

```kotlin
@JsName("require")
external fun requireCss(
    path: String,
): CssBundle

sealed class CssBundle {
    inline val content: String
        get() = asDynamic()[0][1]
}
```

**Comment by supertote** [comment]
Thanks.

What I did for the moment is copy the definitions from `kotlin-extensions` library into my code base.

I was just wondering if there was any plan to make these declarations available in another of the `kotlin-wrapper` libraries

**Comment by turansky** [comment]
> I was just wondering if there was any plan to make these declarations available in another of the kotlin-wrapper libraries

Current plan - use `js.import.import` instead. Experiments required. 
Probably some active users will do it! :)

**Comment by sgrishchenko** [comment]
@supertote you also can try to use dynamic import as replacement for `requireAll`
https://medium.com/front-end-weekly/webpack-and-dynamic-imports-doing-it-right-72549ff49234
https://vitejs.dev/guide/features.html#dynamic-import

In Kotlin it may look like this way:
```kotlin
suspend fun main() {  
  val name = "my-file"
  val module = import("/path/to/$name.png").await()
}
```

**Comment by supertote** [comment]
@sgrishchenko thank you for the suggestion.

I think I will stick to embarking a copy of **CommonJS.kt** from the archived **kotlin-extensions** project for now.
