### ISSUE TITLE
fs.readFileSync is missing

### ISSUE THREAD

**Issue by exaV** [JetBrains/kotlin-wrappers#1869]
The *sync functions from fs module were added in this PR https://github.com/JetBrains/kotlin-wrappers/pull/1672

However one of the most used functions `readFileSync` is still missing.
Documentation can be found here:  https://nodejs.org/api/fs.html#fsreadfilesyncpath-options

I can add it in my projects with the following snippet:
```
@file:JsModule("node:fs")
@file:JsNonModule

import node.buffer.Buffer
import node.fs.PathLike

external fun readFileSync(
    path: PathLike,
    options: Any? /*         | ({
              encoding?: null | undefined;
              flag?: OpenMode | undefined;
          } & Abortable)
        */ = definedExternally,
): Buffer

```

**Comment by turansky** [comment]
@exaV Do you use coroutines in your project?

**Comment by exaV** [comment]
I'd like to use the sync API because it is the one everyone knows about. I got the impression this project wanted to cover the whole node api and the `readFileSync` is part of it.

My situation is the following: I'm maintaining a command-line utility running on node. All of the maintainers know node and its API and most know a bit about Kotlin from developing backends with spring, but few know anything about coroutines. Therefore I'd rather not introduce them (and the weird stacktraces that come with them).
