### ISSUE TITLE
Undefined state of React - Redux on IR backend

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-wrappers#1871]
Hi!
After switching to IR Backend, my Redux state stopped working. I was able to workaround some of them, but for some reason, objects inside my State are always undefined (State itself has all objects when i print it on console). Everything works great on Legacy backend. 

In short, after connecting component to Store I can't use any objects from RootState:

```
val Feature: ComponentClass<Props> =
    rConnect<RootState, RAction, WrapperAction, Props, FeatureStateProps, FeatureDispatchProps, FeatureProps>(
        { state, _ ->
            console.log(state) // prints correct object on IR
            console.log(state.featureState) // undefined on IR
            flagState = state.featureState.flag // undefined on IR
        },
        { dispatch, _ ->
            changeFlag = { dispatch(ChangeFlagOnFeature()) }
        }
    ).renderOn(featureComponent)
```
I tested in on newest wrappers with suffix "-pre.454" and also on generated project from Intelij with wrappers "-pre.346".

I created repo that presents this bug:
[KotlinReduxIssue](https://github.com/Coneys/KotlinReduxIssue/tree/master/src/main/kotlin/redux)

There is a simple Store and RootState, one Feature with Slice and RAction, and one connected react component with Button that should show and modify state:

![image](https://user-images.githubusercontent.com/20384394/206261277-44fa450a-d374-404e-b4aa-5171b605309b.png)

I would really appreciate your help. We would love to use Kotlin on production, but Legacy based JS files are too big, so we have to switch to IR Backend. Thanks!

**Comment by turansky** [comment]
[From migration guide](https://kotlinlang.org/docs/js-ir-migration.html#convert-js-and-react-related-classes-and-interfaces-to-external-interfaces)

**Comment by Coneys** [comment]
Okay, I found the issue, but I could not found any official example using this. 
So basically, not only Component states has to be "external" but Redux "root" state should be external as well:
```
external interface RootState {
    var featureState: FeatureSlice.State
}
```
Then, default state should be created by using jso<>
It works, but I would like to be sure, is this correct way of thinking about it? 
PS I published changes on repo

**Comment by turansky** [comment]
> It works, but I would like to be sure, is this correct way of thinking about it?

If you want to describe JavaScript object contract - `external interface` is what you need.
If you want to create JavaScript object - `jso` is what you need.

IR just highlight this problem more.

**Comment by Coneys** [comment]
But how should I know if object is or is not JavaScript contract? For example, I have to use external interface for properties like this :
```
external interface FeatureStateProps : Props {
    var flagState: Boolean
}
```
but I don't have to do it for acions: 
```
class ChangeFlagOnFeature : RAction {
    fun updateState(state: FeatureSlice.State): FeatureSlice.State {
        return state.copy(flag = state.flag.not())
    }
}
```

Is there any rule, or I just have to remember and know which elements has to be external?

**Comment by turansky** [comment]
> Is there any rule, or I just have to remember and know which elements has to be external?
Rule is simple - check specification/library contract

React props - JSO // by library contract
React state - JSO // by library contract
Worker message data - JSO // by specification

Redux action - as you want, because any object can be action
