### ISSUE TITLE
adding kotlin-mui-icons makes hot reload very slow

### ISSUE THREAD

**Issue by mobiletoly** [JetBrains/kotlin-wrappers#1877]
Adding kotlin-mui-icons makes hot reload very slow. Well, not adding the dependency itself, but usage of any icons in the code

E.g. if I have a code

```
IconButton {
  size = Size.small
  edge = IconButtonEdge.start
  color = IconButtonColor.inherit
  ariaLabel = "menu"
  sx {
    marginRight = 2.px
  }

  mui.icons.material.MenuBook()
}
```

any changes to the file triggers hot reload that takes almost a minute to complete and it makes it almost unusable. While if `mui.icons.material.MenuBook()` line gets removed, then any changes to the file will enable hot reload to be fast again.

Here is a list of my gradle dependencies:
```
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react:18.2.0-pre.346")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom:18.2.0-pre.346")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-emotion:11.9.3-pre.346")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-router-dom:6.3.0-pre.346")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-mui:5.8.4-pre.346")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-mui-icons:5.8.4-pre.346")
```

**Comment by turansky** [comment]
@mobiletoly Do you use IR compiler?

**Comment by mobiletoly** [comment]
yes, IR compiler was enabled. after your question, I disabled IR usage and seems like it fixed the issue, hot reload fast again. Thank you! Is it something well-known and intended?

**Comment by turansky** [comment]
> Is it something well-known and intended?

AFAIK there are some related issues on [YouTrack](https://youtrack.jetbrains.com/issues/KT)
