### ISSUE TITLE
Missing space in CSS parent selector

### ISSUE THREAD

**Issue by alexstaeding** [JetBrains/kotlin-wrappers#1882]
The following CSS snippet seems to be missing a space between the `&` and the `.`. 

https://github.com/JetBrains/kotlin-wrappers/blob/75f258381d490344e7d32b785a3d867752475f94/kotlin-csstype/src/main/generated/csstype/RuleBuilder.kt#L41

I am following [this](https://mui.com/material-ui/react-drawer/) guide to create a drawer, which results in the following Kotlin code:

```kt
Drawer {
    sx {
        width = drawerWidth.px
        and(ClassName("MuiDrawer-paper")) {
            width = drawerWidth.px
            boxSizing = BoxSizing.borderBox
        }
    }
    // ...
}
```

Unfortunately, this does not seem to correctly select the child `MuiDrawer-paper` element.

Looking into the code, I found the selector created by the `and` method and "inlined" it into my code. This is functionally equivalent to calling the `and` method, and still does not work:

```kt
Drawer {
    sx {
        width = drawerWidth.px
        "&.MuiDrawer-paper" {
            width = drawerWidth.px
            boxSizing = BoxSizing.borderBox
        }
    }
    // ...
}
```

However, adding a space between the ampersand and the period, resulting in the following code, produces CSS code that correctly selects the child `MuiDrawer-paper` element:

```kt
Drawer {
    sx {
        width = drawerWidth.px
        "& .MuiDrawer-paper" {
            width = drawerWidth.px
            boxSizing = BoxSizing.borderBox
        }
    }
    // ...
}
```

I would've opened a pull request addressing this issue, but it targets generated source so I am unsure of how exactly to proceed.

**Comment by Leonya** [comment]
Why are you using `and ` for the child selector? It does what it's supposed to do, which is to target the element which has a class `and` another class.

**Comment by alexstaeding** [comment]
Alright, thanks for clearing it up; I'm not very familiar with all CSS concepts. The method doesn't have any documentation so I had to guess that it was semantically equivalent to using the ampersand parent selector.

**Comment by turansky** [comment]
@alexstaeding FYI - you can use predefined class names.
In your case class name constant is `MuiDrawer.paper`
