### ISSUE TITLE
How to add action to CardActionArea?

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [JetBrains/kotlin-wrappers#1887]
[CardActionArea.kt](https://github.com/JetBrains/kotlin-wrappers/blob/10cc04bdc8ce810f3cda74cf40d4ef89a5e3585e/kotlin-mui/src/main/generated/mui/material/CardActionArea.kt) mentions `inherits [ButtonBase API](https://mui.com/material-ui/api/button-base/)`
But, the code doesn't show that.

**Comment by aerialist7** [comment]
@turansky, please assign me
