### ISSUE TITLE
Support for the `@actions` libs that ease GitHub Actions developement

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#1891]
**Is your feature request related to a problem? Please describe.**
It would be nice if there were wrappers for the `@actions/...` libs that ease development of GitHub JS actions: https://www.npmjs.com/search?q=%40actions

**Describe the solution you'd like**
Wrappers for those libs

**Describe alternatives you've considered**
Dukat-generation result, but it needs some post-processing and it would be nice if there were ready-made wrappers instead

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by Leonya** [comment]
@turansky something's wrong with publishing, will try again on Monday.
