### ISSUE TITLE
`node.fs.writeFile` misses way to set other options like mode, only encoding is supported

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#1893]
With the old `kotlinx-nodejs` I could do
```kotlin
writeFileSync(assetFilePath, asset.source, jsObject<`T$45`> {
    mode = asset.permissions
})
```

WIth the `writeFile` methods here you can only set the encoding.

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
