### ISSUE TITLE
Grid columns doesn't work

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [JetBrains/kotlin-wrappers#1901]
The code below expects to have 6 grid items, each item should have a width of 2 columns.

```kotlin
  Grid {
    container = true
    spacing = responsive(1)

    repeat(6) {
      Grid {
        item = true

        columns = responsive(2)

        Typography {
          +"abc"
        }
      }
    }
  }

```

But below is the actual:
![image](https://user-images.githubusercontent.com/24372782/216825731-b4fd14b4-b055-45c5-8858-434c49e3c800.png)

Kotlin 1.7.22
wrappers-bom 1.0.0-pre.491

**Comment by turansky** [comment]
Which structure do you have in virtual DOM?

**Comment by xuan-nguyen-swe** [comment]
![image](https://user-images.githubusercontent.com/24372782/216833283-728f0bbc-6ef7-4061-81ed-a28afbf349da.png)

**Comment by turansky** [comment]
**virtual** DOM structure required

**Comment by xuan-nguyen-swe** [comment]
How can I capture the virtual dom for you?

**Comment by turansky** [comment]
[React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) can be used for capturing

**Comment by xuan-nguyen-swe** [comment]
Don't know how to capture as text. So, took a screenshot.
![image](https://user-images.githubusercontent.com/24372782/216835904-91efbb57-7406-4a4a-83ff-8ff58aea296e.png)

**Comment by turansky** [comment]
It works like in [TS example](https://codesandbox.io/s/dawn-violet-o36g20?file=/demo.tsx)

**Comment by xuan-nguyen-swe** [comment]
@turansky is it MUI bug or the code is wrong?

**Comment by turansky** [comment]
I don't know how it must work, but it works the same way in Kotlin and TS.

**Comment by xuan-nguyen-swe** [comment]
The [doc example](https://mui.com/material-ui/react-grid/#responsive-values):

```
<Grid container spacing={{ xs: 2, md: 3 }} columns={{ xs: 4, sm: 8, md: 12 }}>
  {Array.from(Array(6)).map((_, index) => (
    <Grid item xs={2} sm={4} md={4} key={index}>
      <Item>xs=2</Item>
    </Grid>
  ))}
</Grid>
```

How could we do `<Grid item xs={2} sm={4} md={4}>` with kotlin?

**Comment by turansky** [comment]
Fast fix:
```kotlin
var GridProps.xs: Int?
    get() = asDynamic().xs
    set(value) {
        asDynamic().xs = value
    }
```
