### ISSUE TITLE
Use LinearDimension in margin and padding.

### ISSUE THREAD

**Issue by Nekoyue** [JetBrains/kotlin-wrappers#191]
The following example code from [kotlin-css/README.md](https://github.com/JetBrains/kotlin-wrappers/blob/adb478e42e0157e143e65ca6109409ab6799fa95/kotlin-css/README.md) does not work correctly.
```Kotlin
margin = 0.px // type: LinearDimension
```

Instead, if I want to set all four margins to 0, I need to write code like this
```Kotlin
margin = "0px" // type: String
```
...as the type of margin is `String`.
https://github.com/JetBrains/kotlin-wrappers/blob/adb478e42e0157e143e65ca6109409ab6799fa95/kotlin-css/src/main/kotlin/kotlinx/css/StyledElement.kt#L136
It's easy to switch but the code looks inconsistent. Simply change `String` to `LinearDimension` in `StyledElement.kt` can break shorthand usages of `margin`. 

I propose to create a `marginAll` variable with type `LinearDimension` equivalent to the code above, same for `padding`. Any suggestions?

**Comment by Leonya** [comment]
Oh, I'm sorry, it's a typo. Supposed to be `margin(0.px)`.
