### ISSUE TITLE
The simplest "Hello World!" isn't working any more

### ISSUE THREAD

**Issue by jpink** [JetBrains/kotlin-wrappers#1919]
Following simple example works for version 466, but not 467 any more:
```kotlin
import react.*

fun main() {
    kotlinx.browser.document.apply {
        react.dom.client.createRoot(createElement("div")
            .also(body!!::appendChild) as dom.Element)
            .render(Fragment.create { +"Hello World!" })
    }
}
```
The build error is: `Unresolved reference: dom`.

**Comment by turansky** [comment]
[Actual example](https://github.com/karakum-team/kotlin-react-table-sample/blob/9f81caf5fc0d640e93d8a398b9e4de37a3fe99f5/src/main/kotlin/team/karakum/App.kt#L15)

**Comment by jpink** [comment]
Thanks @turansky! Now it builds and works with latest version, but IntelliJ IDEA doesn't know the syntax:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4598272/219975995-5f1bfc35-5ffd-4100-b88d-20bbc63083c9.png">

But I can live with this.

Btw. It would be nice if JetBrains can update the React project template and examples in documentation up to date.

**Comment by jpink** [comment]
Okay now the IDE fixed syntax highlight.
