### ISSUE TITLE
DragDropContext not usable in FC functional component

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-wrappers#1920]
Hello! I have issue implementing DragDropContext to application that is build with functional components by using FC function.
Why there are two different ways to create functional components (fc and FC)? Other wrappers created by Kotlin team supports only FC (react-mui for example) which makes them incompatible. 
```
val Example = FC<FindRouteProps> { props ->

    child(DragDropContext::class) { // compilation error

    }

}
```
Is there any way or hack to make code above works?

**Comment by turansky** [comment]
Looks like invalid `DragDropContext` declaration

Expected call, if `DragDropContext` declaration will be fixed
```kotlin
val Example = FC<FindRouteProps> { props ->
    DragDropContext { 
        // no compilation error
    }
}
```

> What is the difference between FC and fc?

`FC` - recommended factory for `FC`
`fc` - located in `-legacy` artifact and not recommended

> Why some wrappers like react-mui use FC and other fc?

`fc` used only in `kotlin-styled` and `kotlin-styled-next`
Both are adapters for legacy react wrappers
Recommended replacement for both - `kotlin-emotion`

**Comment by Coneys** [comment]
Is there any way to use this right now? If not, is there an approximate time when this will be in the repository?

**Comment by turansky** [comment]
> Is there any way to use this right now?

If you mean concrete `DragDropContext ` please provide any information about it

**Comment by Coneys** [comment]
Well, this is external val from wrapper of "beautiful dnd" which can be found here:
https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-beautiful-dnd/src/jsMain/kotlin/react/beautiful/dnd/DragDropContext.kt

`external val DragDropContext: Component<DragDropContextProps, *>
`

It inherits after Component from react.Component which seems to be a problem. My whole current application is using FC factory, so my only idea was to use some component created in legacy way:

```
val Example = fc<FindRouteProps> { props ->
    
    child(DragDropContext::class) {
       
    }

}
```
But this crashes with error:

```
Uncaught SyntaxError: Unexpected identifier 'Object'
    at Function (<anonymous>)
    at renderWithHooks (react-dom.development.js?f6e0:16305:1)
    at mountIndeterminateComponent (react-dom.development.js?f6e0:20074:1)
    at beginWork (react-dom.development.js?f6e0:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?f6e0:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?f6e0:4213:1)
    at invokeGuardedCallback (react-dom.development.js?f6e0:4277:1)
    at beginWork$1 (react-dom.development.js?f6e0:27451:1)
    at performUnitOfWork (react-dom.development.js?f6e0:26560:1)
    at workLoopSync (react-dom.development.js?f6e0:26466:1)
```

I have no experience with plain JS so I cannot tell if there is something wrong with library itself, wrapper, or legacy Functional Component factory.

**Comment by turansky** [comment]
@Coneys Thank you for reporting!
Fix will be available in next release (`pre.500`)

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
