### ISSUE TITLE
Droppable is not a function in react-beautiful-dnd wrapper

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-wrappers#1922]
Hello! I'm trying to implement drag and drop using wrapper "react-beautiful-dnd". I could not find any example of doing it in Kotlin, but based on JS tutorials I tried to write it like it most likely should look in Kotlin code:

```
DragDropContext {
        Droppable {
            droppableId = "someExample"
            Box {
                Draggable {
                    draggableId = "1"
                    Typography {
                        +"Test"
                    }
                }

                Draggable {
                    draggableId = "2"
                    Typography {
                        +"Test2"
                    }
                }
            }
        }
    }
```

This code generates error 

```
Uncaught TypeError: children is not a function
    at Droppable (react-beautiful-dnd.esm.js?45ab:8348:4)
    at renderWithHooks (react-dom.development.js?f6e0:16305:1)
    at mountIndeterminateComponent (react-dom.development.js?f6e0:20074:1)
    at beginWork (react-dom.development.js?f6e0:21587:1)
    at beginWork$1 (react-dom.development.js?f6e0:27426:1)
    at performUnitOfWork (react-dom.development.js?f6e0:26560:1)
    at workLoopSync (react-dom.development.js?f6e0:26466:1)
    at renderRootSync (react-dom.development.js?f6e0:26434:1)
    at recoverFromConcurrentError (react-dom.development.js?f6e0:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js?f6e0:26096:1)
```

[In docs](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#children-function) I found that "The React children of a <Droppable /> must be a function that returns a ReactElement"

I am not sure how to achieve this in Kotlin. There is "children" variable in DroppableProps:
   `var children: (provided: DroppableProvided, snapshot: DroppableStateSnapshot) -> ReactElement<HTMLAttributes<*>>`
but I still can't figure out how return my custom functional components or for example components from react-mui, because expected generic type is <HTMLAttributes> so Fragment.create{} won't work:

```
DragDropContext {
        Droppable {
            droppableId = "someExample"
            children = { _, _ ->
                Fragment.create {
                    Box {

                    }
                }
            }
        }
    }
```

**Comment by turansky** [comment]
You can use 
```kotlin
children = { _, _ ->
    Box.create {
    }
```

if `BoxProps` extends `HTMLAttributes`

**Comment by Coneys** [comment]
BoxProps does indeed extend HTMLAttributes but still I cannot use this
<img width="790" alt="image" src="https://user-images.githubusercontent.com/20384394/220166991-9ef7c1ca-845e-496a-93f5-62d1369ac6b0.png">

I am not sure why, but most likely its due to generic type inside HTMLAttributes? Anyway, if I try to use it asDynamic, then whole code doesn't crash like before, but console contains error:
> Invariant failed: provided.innerRef has not been provided with a HTMLElement.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/20384394/220166831-d9bc1c1f-c11d-4367-87d2-6ad78e1bdd2c.png">

**Comment by turansky** [comment]
I see `div` in example :)

**Comment by Coneys** [comment]
I am not sure what do you mean. Div doesn't work as well:
```
DragDropContext {
        Droppable {
            droppableId = "someExample"
            children = { _, _ ->
                div.create { // compilation error with type mismatch

                }
            }
        }
    }
```

**Comment by turansky** [comment]
Thank you @Coneys!
Fix will be available in next release.

**Comment by Coneys** [comment]
After updating to version 502 creating children with xxx.create { } does compile, but still I am not able to create simple example. Setting ref for div as provided.innerRef does not compile, its really hard to figure out how to use this library just looking at JavaScript code. 

I get to point with this:

 val items = listOf("Abc", "Xyz")

```
    DragDropContext {
        Droppable {
            droppableId = "someExample"
            children = { provided, _ ->
                div.create {
                    ref = provided.innerRef.asDynamic() // as dynamic because doesn't compile, againt type issue
                    items.forEachIndexed { itemIndex, item ->
                        Draggable {
                            index = itemIndex
                            draggableId = "id $item"
                            children = { provided, _, _ ->
                                div.create() {
                                    ref = provided.innerRef.asDynamic() //as dynamic because doesn't compile, againt type issue
                                    ListItem {
                                        ListItemText {
                                            primary = ReactNode(item)
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
```

Which **should** work like JS example:

```
function DragAndDropList() {
    return (
        <DragDropContext>  
            <Droppable droppableId="droppable" >  
                {(provided, snapshot) => (  
                    <div  
                        {...provided.droppableProps}  
                        ref={provided.innerRef}  
                    >  
                        {elements.map((item, index) => (  
                            <Draggable draggableId={item.id} index={index}>  
                                {(provided, snapshot) => (  
                                   <div  
                                     ref={provided.innerRef}  
                                     {...provided.draggableProps}  
                                     {...provided.dragHandleProps}  
                                   >  
                                    <ListItem item={item} />
                                   </div>  
                                )}  
                            </Draggable>  
                        ))}  
                    </div>  
                )}  
            </Droppable>  
        </DragDropContext>
    )
}
```

But console throws error related to drag handle:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/20384394/220983811-1b7ca611-9193-481c-a591-39be4305582f.png">

Could you please provide some working Kotlin example with the most simple list with drag and drop?

**Comment by turansky** [comment]
Why you don't use props from `provided`?
```js
{...provided.draggableProps}  
{...provided.dragHandleProps}  
```

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by Coneys** [comment]
> Why you don't use props from `provided`?
> 
> ```js
> {...provided.draggableProps}  
> {...provided.dragHandleProps}  
> ```

I have no idea how to refer to this JS syntax in Kotlin

**Comment by Coneys** [comment]
Great! Thank you. If someone else would try to experiment with dnd wrapper there is a working example:

```
val items = listOf("Abc", "Xyz")

    DragDropContext {
        Droppable {
            droppableId = "someExample"
            children = { provided, _ ->
                div.create {
                    ref = provided.innerRef.asDynamic()
                    +provided.droppableProps
                    items.forEachIndexed { itemIndex, item ->
                        Draggable {
                            key = item
                            index = itemIndex
                            draggableId = item
                            children = { provided, _, _ ->
                                div.create() {
                                    ref = provided.innerRef.asDynamic()
                                    +provided.dragHandleProps
                                    +provided.draggableProps
                                    ListItem {
                                        ListItemText {
                                            primary = ReactNode(item)
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
```

And as I understand in next versions we won't have to use "asDynamic" for innerRef

**Comment by turansky** [comment]
> And as I understand in next versions we won't have to use "asDynamic" for innerRef

Yes

**Comment by turansky** [comment]
@Coneys Looks like `innerRef` - legacy API
If it works for you in React 18+ - we will remove it at all :)

**Comment by xcporter** [comment]
Could the example in this thread be added to the readme (or somewhere else more prominent)?

This is the only working example I could find anywhere on the internet.

**Comment by turansky** [comment]
@xcporter We created separate folder `examples` for such cases.
I expect separate subproject for `react-beautiful-dnd` with examples like this.
PR is welcome.
