### ISSUE TITLE
Data router example

### ISSUE THREAD

**Issue by jpink** [JetBrains/kotlin-wrappers#1923]
How to configure the routes for the new data router? All the examples are for the legacy one.

The [tutorial](https://reactrouter.com/en/main/start/tutorial#adding-a-router) says:
```js
import { createBrowserRouter } from "react-router-dom"

const router = createBrowserRouter([
  {
    path: "/",
    element: <div>Hello world!</div>
  }
])
```

How to implement it in Kotlin?
```kotlin
import react.*
import react.router.*
import react.router.dom.createBrowserRouter

fun createRouter() = createBrowserRouter(createRoutesFromChildren(Routes.create {
    Route { // how should I create the Route?
        with (this as PathRouteProps) { // how to get access to these props?
            path = "/"
            element = Fragment.create { +"Hello world!" }
        }
    }
}))
```

**Comment by jpink** [comment]
Found one example and idea from [MUI Showcase](https://github.com/karakum-team/kotlin-mui-showcase/blob/main/src/main/kotlin/team/karakum/App.kt) but it not work either:
```kotlin
val rtr = createBrowserRouter(arrayOf(
    jso {
        path = "/" // Doesn't compile
        element = react.Fragment.create { +"Hello world!" } // Doesn't compile
    }
))
```

**Comment by jpink** [comment]
Wrappers are constantly evolving and API is constantly changing - it's good thing.

But JetBrains: WHY it's so hard to create simple examples, templates in IDE and keep the up to date and working with latest versions. Please don't modify API if you don't have time to update documentation. I'm banging my head all the time to figure out what has changed. Is there change log somewhere?

**Comment by turansky** [comment]
`kotlin-react-router-dom-legacy` is still available, you can use it if Router `6.3.0` is fine for you

> Please don't modify API if you don't have time to update documentation

Which documentation do you mean?

**Comment by jpink** [comment]
I can use legacy because most of the examples are also for it. But why it is best practice to build against legacy. Isn't the data routers stable yet?

And for the changing API I mean that I have found three different ways to configure routes and they work only for spesific version ranges.

By documentation I mean the official one: https://kotlinlang.org/docs/js-samples.html
For example https://github.com/Kotlin/react-redux-js-ir-todo-list-sample/blob/master/build.gradle.kts uses version 290 even that version 500 is currently available. We do nothing with old examples which doesn't work with latest versions of these wrappers.

I'm really balancing with Kotlin/JS vs. Vanilla JS. There is few comparisons:
- JS hot reload is fast. Kotlin hot reload takes at least 15 seconds.
- JS seems to have better documentation and examples. That is critical thing if you want that more people will adopt Kotlin/JS

I don't want to troll Kotlin/JS but these are sad facts.

**Comment by turansky** [comment]
> Isn't the data routers stable yet?

Do you mean fresh Data Routers from `react-router` `6.4.0`+?
If yes - conversion in progress, we have some open questions (#1916)

> And for the changing API I mean that I have found three different ways to configure routes and they work only for specific version ranges.

It looks like expected, because it was 2 or more `react-router` major JS API updates.
Also we aligned Kotlin wrappers logic between subprojects. 
If you want to use previous `react-router` JS API - you can use previous wrappers version.
It works the same way like in JS world :(
  
For now single up-to-date example for `kotlin-react-router` is [mui-showcase](https://github.com/karakum-team/kotlin-mui-showcase)
It's example 10 in our README

> Kotlin hot reload takes at least 15 seconds.

It looks like project configuration problem

> JS seems to have better documentation and examples

Most of them works for Kotlin as well (like in your initial request with Data Routes)

**Comment by sgrishchenko** [comment]
@jpink Unfortunately we can't support union types in react props of `Route` component, we provided special aliases for it using concrete prop types: `PathRoute`, `LayoutRoute` and `IndexRoute`. Maybe you can try one of that components. New declarations for `react-router` are fresh and maybe not polished yet, we did not updated our examples and did not documented some edge cases of new router API, but thank you for feedback and for so early adoption of new declarations. We will try to improve it soon, work in progress.

**Comment by sgrishchenko** [comment]
@jpink we improved our declarations for new `react-router` API. We also updated our [example](https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/jsMain/kotlin/example/ReactRouterDom.kt) using this API. So do not use `PathRouteProps` at all, this interface is created for legacy mode, where component based approach is used for router configuration. Type what you need is `RouteObject`, but you can just write `jso`, Kotlin is smart enough to infer this type for you, you can just write this:
```
val rtr = createBrowserRouter(arrayOf(
    jso {
        path = "/" // this should compile now
        element = react.Fragment.create { +"Hello world!" } // this should compile now
    }
))
```
If it works for you, can I close this ticket?
