### ISSUE TITLE
How to add action to CardHeader?

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [JetBrains/kotlin-wrappers#1925]
See https://mui.com/material-ui/react-card/#complex-interaction

```
<CardHeader
        // ...
        action = {
          <IconButton aria-label="settings">
            <MoreVertIcon />
          </IconButton>
        }
/>
```

Note that, this is different from CardActions.

**Comment by turansky** [comment]
Like this:

```kotlin
CardHeader {
    action = {
        IconButton.create {
            ariaLabel = "settings"
            
            MoreVertIcon()
        }
    }
}
```

**Comment by xuan-nguyen-swe** [comment]
> Like this:
> 
> ```kotlin
> CardHeader {
>     action = {
>         IconButton.create {
>             ariaLabel = "settings"
>             
>             MoreVertIcon()
>         }
>     }
> }
> ```

Thanks for your answer!
But why the API looks different than normal DSL?

**Comment by turansky** [comment]
> But why the API looks different than normal DSL?

Because you need separate DSL context.
Otherwise you will add children in `CardHeader`.

**Comment by xuan-nguyen-swe** [comment]
> > But why the API looks different than normal DSL?
> 
> Because you need separate DSL context. Otherwise you will add children in `CardHeader`.

Thanks for your explanation!

But I think, it would be nice if we could find a better DSL in this case.

Here is my idea.
```
CardHeader {
    action { // here, we pass a lambda. The method action will handle the details of creating a new context.
        IconButton {
            ariaLabel = "settings"
            
            MoreVertIcon()
        }
    }
}
```

**Comment by turansky** [comment]
Unfortunately described solution is quite limited.
In some cases it won't work at all.
Also we want to avoid `ChildrenBuilder` extensions creation as much as possible.
