### ISSUE TITLE
IR compiler support status?

### ISSUE THREAD

**Issue by TorRanfelt** [JetBrains/kotlin-wrappers#1928]
I would have asked in your chat, but I'm just told "[...] doesn’t have an account on this workspace.", and creating an account doesn't change that.

My question:
What is the status with regards to fully supporting the IR compiler? - With Kotlin 1.8.10 LEGACY has been deprecated.

**Comment by turansky** [comment]
It works with IR since August 2020 (#327)
IR usage example you can find [here](https://github.com/karakum-team/kotlin-react-table-sample)
