### ISSUE TITLE
Very long compile time using mui-icons on IR backend with Kotlin 1.8

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-wrappers#1933]
After updating to version 1.8 I noticed that compilation time became enormous. I found somewere that mui-icons library creates this issue. I tested it, and with even one icon used in project, compilation time increases 2.5 times

Without mui-icons and with change in code:

- gradle xxxBrowserDevelopmentRun --rerun took 17 seconds to open localhost
- run with continuous and change in code took 20 seconds to update changes (and its weird that it is faster to run BrowserDevelopmentRun again than use continuous)

With mui-icon and change in code:
- gradle xxxBrowserDevelopmentRun --rerun took 50 seconds to open localhost
- run with continuous and change in code took 1 minute to update changes (again, longer than running task again)

Is there any setting / gradle properties that I should use to resolve this issue? Maybe I should create wrappers for icons I use myself, and remove mui-icons wrapper from project? In this point, going back to Legacy backend is impossible because of other bugs related to react-mui, so we are totally blocked from working Kotlin JS project

**Comment by Leonya** [comment]
Forwarded to the Kotlin/JS team, let's see what they say.

**Comment by turansky** [comment]
[Compiler issue](https://youtrack.jetbrains.com/issue/KT-51712)
