### ISSUE TITLE
Frontpage README link for Quill demo is broken

### ISSUE THREAD

**Issue by mikedawson** [JetBrains/kotlin-wrappers#1934]
Hi,

I think the link for the quill demo (demo #5) on the frontpage is incorrect. It should now be:

https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/jsMain/kotlin/example/Quill.kt

It is currently this (eg it is using main instead of jsMain):

https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/main/kotlin/example/Quill.kt

Which goes to the GitHub 404.

**Comment by turansky** [comment]
Looks like non-finished PR :)
