### ISSUE TITLE
Tanstack Wrappers Missing @JsNonModule

### ISSUE THREAD

**Issue by mikedawson** [JetBrains/kotlin-wrappers#1935]
Hi,

I have been using TanStack  (with Kotlin 1.8.10, legacy compiler) that was working fine with build 494. The wrapper declarations had both @JsModule and @JsNonModule annotations. 

The latest build (502) does not have the @JsNonModule declaration, and now I get a compile error "When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule":

Current wrappers no longer have the @JsNonModule annotation - e.g.

https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-tanstack-react-query/src/jsMain/generated/tanstack/react/query/useInfiniteQuery.kt

Was this change intentional? Is there any recommended workaround?

Thanks!

**Comment by turansky** [comment]
> Was this change intentional?

Yes, migration on modular (`commonjs`) declarations in progress

> Is there any recommended workaround?

Recomendation - use `commonjs` module kind
We do it [conventions plugin](https://github.com/JetBrains/kotlin-wrappers/blob/671eb18c53c6cdda0027590c7df216d396978758/buildSrc/src/main/kotlin/kotlin-conventions.gradle.kts#L25)
