### ISSUE TITLE
Credential handlers in `actions-toolkit` need to be imported from `@actions/http-client/lib/auth`

### ISSUE THREAD

**Issue by araqnid** [JetBrains/kotlin-wrappers#1938]
I tried to create a `BearerCredentialHandler`, but got a runtime `TypeError` saying that it was not a constructor.

In fact it appears that it is not exported from the base of the package, and needs to be imported with the `.../lib/auth` suffix (see e.g. https://github.com/actions/toolkit/blob/500d0b42fee2552ae9eeb5933091fe2fbf14e72d/packages/core/src/oidc-utils.ts#L5)

I worked around by creating a local file with `@file:JsModule("@actions/http-client/lib/auth")` and declaring an external class in there.

(I ran into more problems due to `RequestHandler` being exposed as a **sealed** external interface, but `unsafeCast` came to the rescue)

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by turansky** [comment]
Fixed in `pre.504`
