### ISSUE TITLE
MUI Slider Custom Marks Not Showing. Expecting Boolean

### ISSUE THREAD

**Issue by Rchrdlss3** [JetBrains/kotlin-wrappers#1939]
I should be able to create custom marks by providing an array, but I get error 
```
Warning: Failed prop type: Invalid prop `marks` supplied to `ForwardRef(SliderUnstyled)`, expected one of type [boolean].
```
https://codesandbox.io/s/wbck98?file=/demo.tsx
<img width="844" alt="Screen Shot 2023-03-01 at 2 44 57 PM" src="https://user-images.githubusercontent.com/35810850/222248027-0f0d7280-26f9-4121-9374-9c8530b09ff0.png">

In my code I created a class called 'Mark' and have an Array called 'timeMarks' filled with Mark objects  
```
            class Mark (
                var value: Number? = 0,
                var label: String = ""
            )

 val timeMarks = arrayOf(Mark(-5.00,"Test5"),Mark(-3.00,"Test3"),Mark(-11.00,"Test11"),Mark(3,"Test3"),Mark(7,"Test7"),Mark(8.00,"Test8"))
```

This is what my Slider looks like 
```
Slider {
                                value = dayArray
                                valueLabelDisplay = "auto"
                                disableSwap = true
                                min = -24.00
                                max = 0.00
                                step = 0.25
                                marks = timeMarks
                                orientation = Orientation.vertical
}
```

My Slider still loads, but nothing pops up

**Comment by turansky** [comment]
Valid marks example:

```kotlin
sealed external interface Mark {
    var value: Number?
    var label: String?
}

 val timeMarks: ReadonlyArray<Mark> = arrayOf(
     jso { value = -5.00; label = "Test5" },
     jso { value = -3.00; label = "Test3" },
     jso { value = -11.00; label = "Test11" },
)

```

**Comment by Rchrdlss3** [comment]
> Valid `marks` example:
> 
> ```kotlin
> sealed external interface Mark {
>     var value: Number?
>     var label: String?
> }
> 
>  val timeMarks: ReadonlyArray<Mark> = arrayOf(
>      jso { value = -5.00; label = "Test5" },
>      jso { value = -3.00; label = "Test3" },
>      jso { value = -11.00; label = "Test11" },
> )
> ```

Works perfectly! Thank you
