### ISSUE TITLE
kotlin-csstype does not have auto option for Overflow

### ISSUE THREAD

**Issue by jfontsaballs** [JetBrains/kotlin-wrappers#1942]
Please see https://github.com/JetBrains/kotlin-wrappers/blob/86a1924334d32fb41a14a41c14760a16df9888c4/kotlin-csstype/src/jsMain/generated/csstype/Overflow.kt

```kotlin
sealed external interface Overflow {
    companion object {
        val clip: Overflow
        val hidden: Overflow
        val scroll: Overflow
        val visible: Overflow
    }
}
```

How can I set CSS overflow to auto in a div?

Thank-you

**Comment by turansky** [comment]
You can use common `auto`

```
import csstype.Auto.auto
```
