### ISSUE TITLE
[Regression] NavigateFunction#invoke (since pre.522)

### ISSUE THREAD

**Issue by jschneider** [JetBrains/kotlin-wrappers#1950]
Starting with 522 the method
NavigateFunction#invoke 
does no longer navigate. 

Reverting to pre.521 fixes the issue.

I assume this is the problematic commit:
https://github.com/JetBrains/kotlin-wrappers/commit/0a1360dfa8e2b41cb311bbbb394dc8ff00e71bcb

I am calling the invoke *without* NavigationOptions. Since this parameter is provided by "definedExternally" in the new implementation this might be the cause.

**Comment by turansky** [comment]
IR, `pre.524` - works fine

**Comment by turansky** [comment]
@jschneider Do you use legacy compiler?

**Comment by jschneider** [comment]
I *think* I am using the new IR compiler.
my gradle.properties file contains "kotlin.js.compiler=ir"

**Comment by jschneider** [comment]
I updated my build.gradle.kts to use IR:
`js(IR){...}`

Same behavior.

**Comment by turansky** [comment]
1. `./gradlew clean` before build
2. `pre.524`

**Comment by jschneider** [comment]
I fixed it: I used a value class as parameter for "To". Somehow this worked in the earlier versions - but does not longer...
Calling .value solves this issue for me
