### ISSUE TITLE
Missing breaking changes in changelog

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#1956]
I just updated from 498 to 526 and had 3 breaking changes that are not listed in the changelog.
- I had to remove the `js.core.get` import that I previously needed to access `process.env`
- I had to replace the import of `node.buffer.BufferEncoding.utf16le`
- I had to replace the import of `import node.process.Platform.win32`

It would be really nice if breaking changes would be fully listed in the changelog and not only some. :-)

**Comment by turansky** [comment]
@Vampire Since `pre.524` (100+ releases) we describe breaking changes.
It looks like we can close the issue :)

**Comment by Vampire** [comment]
Sure, if you added the missing ones (for example the ones I listed) and also now list all, feel free to close this. :-)
