### ISSUE TITLE
Error in kotlin-react-select when trying to define getOptionLabel with a lambda expression

### ISSUE THREAD

**Issue by AdriaVivas** [JetBrains/kotlin-wrappers#1962]
When trying to define how the getOptionLabel function should work, I get this error: getContainingDeclaration�lDeclarationType.REGULAR) must not be null: KtLambdaExpression:

I think I found a solution where Select should expect type Any? instead of Any, that may work. Found in https://youtrack.jetbrains.com/issue/KT-50520

This is my code: 
````
class SelectOption (val value: String, val label: String)

val show by Component<MyProps> { props ->

  val opcions = arrayOf(
                  SelectOption("1","Option 1"),
                  SelectOption("2", "Option 2")
              )

  Select {
                this.isMulti = true
                this.options = OptionsOrGroups(opcions)
                this.getOptionLabel = {
                    (it as SelectOption).label
                }
                this.getOptionValue = {
                    (it as SelectOption).value
                }
            }
}
````

Maybe I'm doing something wrong. 
Thank you

**Comment by AdriaVivas** [comment]
I also tried using String for the options instead of SelectOption, and getOptionLabel and getOptionValue lambdas being { it } got the same error

**Comment by turansky** [comment]
@AdriaVivas Could you provide explicit type parameter and rename your `SelectOption`?
```kotlin
Select<SelectOption<YourSelectOption>, _> {
     getOptionLabel = YourSelectOption::label
     getOptionValue = YourSelectOption::value
}
```

**Comment by AdriaVivas** [comment]
Ok that works. Thank you so much :)
