### ISSUE TITLE
Sealed interfaces without implementations

### ISSUE THREAD

**Issue by Burtan** [JetBrains/kotlin-wrappers#1973]
Hi,

there are some sealed interfaces that do not have any implementations provided. What is the use of these interfaces, they can never be implemented?
An example would be [PermissionDescriptor](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-browser/src/jsMain/generated/web/permissions/PermissionDescriptor.kt).

**Comment by turansky** [comment]
Such interfaces describe JavaScript object contract - custom implementation isn't expected.

For now you can use `jso` method to construct instances:
```
val descriptor: PermissionDescriptor = jso {
    name = "create-safe-jso"
}
```
