### ISSUE TITLE
How to use media query when defining MUI typography for the theme

### ISSUE THREAD

**Issue by andremion** [JetBrains/kotlin-wrappers#1986]
I would like to have 2 font sizes for `h1`:
- `20px` when the `max-width` is `600px`
- `40px` otherwise.

How can I do that using MUI?

This doesn't work because there's no media function in the latest version of the wrappers

```kotlin
typography = jso {
    h1 = jso {
        fontSize = 40.px
        media("(max-width:600px)", jso {
            fontSize = 20.px
        })
    }
}
```

**Comment by turansky** [comment]
@andremion Could you provide TS/JSX example?

**Comment by andremion** [comment]
> @andremion Could you provide TS/JSX example/alternative?

Sure. Something like this:

```typescript
const theme = createTheme();

theme.typography.h1 = {
  fontSize: '40px',
  '@media (max-width:600px)': {
    fontSize: '20px',
  }
};
```
Or even this way:
```typescript
theme.typography.h1 = {
  fontSize: '40px',
  theme.breakpoints.down('sm'): {
    fontSize: '20px',
  }
}
```
Thanks

**Comment by andremion** [comment]
Nop
<img width="370" alt="Screenshot 2023-04-18 at 21 16 30" src="https://user-images.githubusercontent.com/12762356/232895031-dbb8a014-261c-4314-9b0e-1df1ecf6b9f3.png">
I'm using MUI Material. I'm trying to customize its Typography...

**Comment by turansky** [comment]
It works:
```kotlin
import csstype.Properties
import csstype.PropertiesBuilder
import csstype.media.maxWidth
import csstype.px
import js.core.jso
import react.dom.html.ReactHTML.h1

val MyTypography: Properties = jso<PropertiesBuilder> {
    h1 {
        fontSize = 40.px

        media(maxWidth(600.px)) {
            fontSize = 20.px
        }
    }
}
```

**Comment by turansky** [comment]
Then I don't understand which type you want build :(

**Comment by andremion** [comment]
I want to build the MUI theme object

```kotlin
import mui.material.styles.Theme
import mui.material.styles.createTheme
//
createTheme(
    jso {
        typography = Typography
    }
)
```

**Comment by andremion** [comment]
But you gave me a really great hint.

This achieves what I want:

```kotlin
val MyTypography: dynamic = jso {
    h1 = jso<PropertiesBuilder> {
        fontSize = 40.px

        media(maxWidth(600.px)) {
            fontSize = 20.px
        }
    }
}
```

Using PropertiesBuilder on each typography variant 🎉 

Thank you so much, @turansky  🙏🏻

**Comment by turansky** [comment]
Strict builder required instead.
`dynamic` - fine for fast check, but it isn't good solution.

**Comment by andremion** [comment]
I used dynamic just because the current version of the wrappers doesn't provide anything else

```kotlin
@JsName("default")
external fun createTheme(
    options: ThemeOptions? = definedExternally,
    vararg args: dynamic,
): Theme

external interface ThemeOptions : mui.system.ThemeOptions {
    override var mixins: MixinsOptions?

    override var components: dynamic

    override var palette: PaletteOptions?

    override var shadows: dynamic

    override var transitions: TransitionsOptions?

    override var typography: dynamic

    override var zIndex: dynamic

    var unstable_strictMode: Boolean?
}
```

**Comment by aerialist7** [comment]
@andremion, you can also avoid `dynamic`s right now

``` kotlin
    val Theme = createTheme(
        jso {
            typography = jso<TypographyProps> {
                variantMapping = jso {
                    h1 = jso<PropertiesBuilder> {
                        fontSize = 40.px

                        media(maxWidth(600.px)) {
                            fontSize = 20.px
                        }
                    }
                }
            }
        }
    )
```

**Comment by andremion** [comment]
@aerialist7 unfortunately, that doesn't work.
`variantMapping` has a dynamic type and only maps the variant prop to various HTML element types, for instance, `subtitle1` to `<h6>`

**Comment by aerialist7** [comment]
@andremion, you are right, got it.

Added `TypographyOptions` support in #1987, so after merge and release you can update wrappers and the code would be like:

``` kotlin
val Theme = createTheme(
    jso {
        typography = TypographyOptions {
            h6 {
                fontSize = 40.px
    
                media(maxWidth(600.px)) {
                    fontSize = 20.px
                }
            }
        }
    }
)
```

**Comment by aerialist7** [comment]
@Leonya, could you please make a release?

**Comment by aerialist7** [comment]
@andremion, released in Kotlin Wrappers `pre.539`

**Comment by andremion** [comment]
Thanks, @aerialist7

I tested it and it's missing just one more thing in the DSL to fully cover the MUI.

When customizing the typography, we should be able to define the default font family, font weight, font size, etc.

This way doesn't work:

<img width="569" alt="Screenshot 2023-04-20 at 07 41 43" src="https://user-images.githubusercontent.com/12762356/233281875-a6fb6b5b-af6c-494f-b71a-d4a09ee0ff59.png">

Am I missing something?

**Comment by andremion** [comment]
I tried this way but I don't know if it's the recommended way and how to set the font family
<img width="599" alt="Screenshot 2023-04-20 at 07 58 03" src="https://user-images.githubusercontent.com/12762356/233285626-50521aba-0e8b-483a-b014-16249eae55e7.png">

**Comment by andremion** [comment]
It seems to work. But I still don't know how to define the `FontFamily`

<img width="558" alt="Screenshot 2023-04-20 at 11 00 44" src="https://user-images.githubusercontent.com/12762356/233332586-7d486c15-9b32-4d9a-b9f8-a9521dd63452.png">

**Comment by aerialist7** [comment]
@andremion, meanwhile, PR #1988 was merged, so after release, you can remove your local WA.
@Leonya, could you please make a release?

**Comment by andremion** [comment]
Thanks, guys! 🙌🏻

**Comment by aerialist7** [comment]
@andremion, released in Kotlin Wrappers `pre.540`
