### ISSUE TITLE
Breaking changes in non-major version bumps of mui

### ISSUE THREAD

**Issue by Yvee1** [JetBrains/kotlin-wrappers#2001]
MUI has breaking changes in non-major version bumps. See for example version @mui/base@5.0.0-alpha.127 (https://github.com/mui/material-ui/releases/tag/v5.12.2). Maybe this happens because it's still in alpha? In any case, this can cause a problem with the kotlin-mui wrappers because versions are specified with the carrot ^ symbol, so a newer npm version may be used with an API different from the wrappers.

Possible solution?: remove the ^ symbol from the mui version, at least until the mui/base etc. are out of alpha.

edit: my temporary work-around is adding the following to `build.gradle.kts`:
```kotlin
rootProject.plugins.withType<YarnPlugin> {
    rootProject.the<YarnRootExtension>().apply {
        resolution("@mui/material", "5.11.2")
    }
}
```

**Comment by waveduke** [comment]
For me **kotlin-mui-icons** was the problem. Temporary fix based in previous solution from @Yvee1:

````
rootProject.extensions.configure(YarnRootExtension::class.java) {
    resolution("@mui/icons-material", "5.11.11")
}
````

**Comment by aerialist7** [comment]
cc @aerialist7 @turansky
