### ISSUE TITLE
Emotion createCache function

### ISSUE THREAD

**Issue by andremion** [JetBrains/kotlin-wrappers#2002]
I started to review supporting RTL in the project I'm working on. So I started to follow https://mui.com/material-ui/guides/right-to-left/
I realize we have `EmotionCache` available from the wrappers but not the `createCache` function.
Not sure if you have plans to add that function in the wrappers.
In the meantime, I tried the simplest solution of declaring it as dynamic and didn't work:

```kotlin
@JsModule("@emotion/cache")
@JsNonModule
external val createCache: dynamic
````

I get an error saying the `createCache` is not a function

Any suggestions?

**Comment by turansky** [comment]
Fast pill:

```kotlin
@file:JsModule("@emotion/cache")
@file:JsNonModule

@JsName("default")
external val createCache: Function<dynamic>
```

**Comment by andremion** [comment]
@turansky , it didn't work. I printed it and gave me `undefined`.

When I do this:
```kotlin
@JsModule("@emotion/cache")
@JsNonModule
external val createCache: Function<dynamic> // or just dynamic
```
I get this when I print it:
<img width="511" alt="Screenshot 2023-04-30 at 18 48 17" src="https://user-images.githubusercontent.com/12762356/235368330-c27e2d77-6712-4a16-aa82-fd9d85f0ac7b.png">

**Comment by andremion** [comment]
@turansky , actually worked. But I had to have it declared as dynamic in order to be able to call it with a jso paramater

**Comment by turansky** [comment]
It's 4 interfaces and 1 function only!
Fine first PR for @andremion :)

**Comment by turansky** [comment]
[Types](https://www.unpkg.com/browse/@emotion/cache@11.10.8/types/index.d.ts)

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
