### ISSUE TITLE
URLSearchParams#forEach is incorrect

### ISSUE THREAD

**Issue by Leonya** [JetBrains/kotlin-wrappers#2005]
It is defined as `fun forEach(action: (item: String) -> Unit)`, but should be `fun forEach(callback: (value: String, key: String, searchParams: URLSearchParams) -> Unit)`

**Comment by turansky** [comment]
What about such replacement? // works now
```kotlin
for ((key, value) in params.entries()) {
    // action
}
```

Or even this (not implemented yet)
```kotlin
for ((key, value) in params) {
    // action
}
```

Will it be better in your case?

**Comment by Leonya** [comment]
Yes, this works.
