### ISSUE TITLE
cssom: Display missing none type

### ISSUE THREAD

**Issue by andylamax** [JetBrains/kotlin-wrappers#2023]
expected to have `Display.none` as one of the Display options, but it was missing

Reference: https://github.com/JetBrains/kotlin-wrappers/blob/0aa8158b94daff552e01be150303d4a4b9ceca6f/kotlin-cssom-core/src/jsMain/generated/web/cssom/Display.kt#L12

**Comment by turansky** [comment]
`None` - child type of `Display`
`None.none` constant can be used

**Comment by andylamax** [comment]
Thanks @turansky
