### ISSUE TITLE
Broken `RouteProps` in `kotlin-react-router`

### ISSUE THREAD

**Issue by joffrey-bion** [JetBrains/kotlin-wrappers#2024]
We can no longer use `path` and `element` properties in `Route { ... }` components because the `RouteProps` doesn't contain any props (parent interfaces are commented out):

```kotlin
sealed external interface RouteProps : react.Props /* export declare type RouteProps = PathRouteProps | LayoutRouteProps | IndexRouteProps; */
```

See https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-router/src/jsMain/generated/react/router/RouteProps.kt

**Comment by alexstaeding** [comment]
This seems to be broken since #1902 and #1903

**Comment by turansky** [comment]
Recommendation for now - use [recommended routers](https://reactrouter.com/en/main/routers/create-browser-router#createbrowserrouter).

**Comment by joffrey-bion** [comment]
@turansky do you have an example of how this looks in Kotlin?

**Comment by turansky** [comment]
`sealed external interface` - JSO marker.
To create JSO we use `jso` factory.

**Comment by turansky** [comment]
[Example](https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/jsMain/kotlin/example/ReactRouterDom.kt#L96)

**Comment by joffrey-bion** [comment]
Thanks, yeah using `jso` works, but giving up on type safety is a last resort for me, because the point of using Kotlin is mostly type safety.

Is this a temporary workaround? Is there any plan to manually fix the props in the external declaration (while waiting for the tool to be improved)?

**Comment by turansky** [comment]
> but giving up on type safety is a last resort for me, because the point of using Kotlin is mostly type safety.

Where you lose type safety? :)

**Comment by joffrey-bion** [comment]
Ah my bad, I had an incorrect understanding of `jso`. Indeed that's the direct equivalent of a JS object implementing some interface, with type-safe properties inside. Good to know, thanks!

**Comment by turansky** [comment]
Legacy (children) API removed
