### ISSUE TITLE
Browser - Missing types for Credential Management API

### ISSUE THREAD

**Issue by dcowley** [JetBrains/kotlin-wrappers#2038]
Relates to issue #2022 and [Slack discussion](https://kotlinlang.slack.com/archives/C0B8L3U69/p1686146465991229).

There are a few more missing [`web.authn`](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-browser/src/jsMain/generated/web/authn) types:
- [`PublicKeyCredential`](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential)
- [`AuthenticatorResponse`](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorResponse)
- [`AuthenticatorAssertionResponse`](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse)
- [`AuthenticatorAttestationResponse`](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse)

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
