### ISSUE TITLE
DateTimeFormat is missing resolvedOptions

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/kotlin-wrappers#2039]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions

```js
let options = Intl.DateTimeFormat().resolvedOptions()
options.locale;
options.calendar;
options.numberingSystem;
options.timeZone;
options.hour12;
options.weekday;
options.era;
options.year;
options.month;
options.day;
options.hour;
options.minute;
options.second;
options.timeZoneName;
```

I tried to find the generator to create a PR but I failed.

**Comment by turansky** [comment]
Generator fix - https://github.com/karakum-team/types-kotlin/commit/893b92a905d5c576803340e6702b550eb0f5e947

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
