### ISSUE TITLE
MUI: Missing MuiModal

### ISSUE THREAD

**Issue by hofi99** [JetBrains/kotlin-wrappers#2043]
A lot of MUI class names are already accessible in a typed way (like `MuiDialog`).
`MuiModal` is missing currently.

**Comment by aerialist7** [comment]
Hi @hofi99!

Thanks for reporting, will check.

**Comment by aerialist7** [comment]
@hofi99, it's ready! :)
https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-mui/src/jsMain/generated/mui/base/Modal.mui.kt
