### ISSUE TITLE
How to pass state with react router navigate?

### ISSUE THREAD

**Issue by mattdornfeld** [JetBrains/kotlin-wrappers#2075]
I'm using `NavigateFunction` to navigate to a new route with React Router. 
```
val navigate: NavigateFunction = useNavigate()
navigate("/sign-in")
```
This works okay. I see NavigateFunction accepts an options argument with type `NavigateOptions`, which looks like this.
```
sealed external interface NavigateOptions {
    var replace: Boolean?
    var state: remix.run.router.LocationState?
    var preventScrollReset: Boolean?
    var relative: RelativeRoutingType?
}
```
So it seems like if I want to pass around state that's the way to go, but when I try to instantiate it `NavigateOptions {}`, I get the following compiler error `Interface NavigateOptions does not have constructors`. I can't find any examples of the proper way to instantiate it. Any advice?

**Comment by turansky** [comment]
[Answer](https://github.com/JetBrains/kotlin-wrappers/issues/2024#issuecomment-1618934471)
