### ISSUE TITLE
How to create an instance of NumberFormatOptions?

### ISSUE THREAD

**Issue by overpas** [JetBrains/kotlin-wrappers#2076]
`NumberFormatOptions` is defined as `sealed interface` with no implementations. The only way to supply `NumberFormatOptions` to `NumberFormat` that I've thought of is to use something like this `options = js("{ style: 'percent', maximumFractionDigits: 2 }")`, however in this case it is limited to compile-time strings only

**Comment by turansky** [comment]
[Answer](https://github.com/JetBrains/kotlin-wrappers/issues/2024#issuecomment-1618934471)
