### ISSUE TITLE
IndexedDB initializer

### ISSUE THREAD

**Issue by aSemy** [JetBrains/kotlin-wrappers#2079]
### Is your feature request related to a problem? Please describe.

I see bindings for IndexedDB in kotlin-wrappers https://github.com/JetBrains/kotlin-wrappers/tree/pre.602/kotlin-browser/src/jsMain/generated/web/idb, but it looks like there’s no included way to initialise a database? All the classes are sealed and there’s no util extension method like 

```kotlin
public val Window.indexedDB: IDBFactory?
    get() = this.asDynamic().indexedDB as? IDBFactory
```

(from 
https://github.com/JuulLabs/indexeddb/blob/70e86cf7904918a7524a44b16241c008e35818bd/external/src/jsMain/kotlin/IDBFactory.kt#L11C2-L13)

### Describe the solution you'd like

* A way of instantiating an IndexedDB
* A brief example (be it in the README or in a test class) showing how to instantiating an IndexedDB

### Describe alternatives you've considered

Manually define the extension function above

### Additional context

https://github.com/JuulLabs/indexeddb is an alternative IndexedDB implementation, but it's entirely coroutines-based. I need more primitive bindings because I need to save data in a callback and Kotlin/JS doesn't have a way to bridge non-suspending/suspending code.

**Comment by turansky** [comment]
> All the classes are sealed

Which classes you expect as non-sealed?

**Comment by aSemy** [comment]
> > All the classes are sealed
> 
> Which classes you expect as non-sealed?

My phrasing was unclear, sorry! I meant to indicate that because the IDB classes (e.g. [IDBFactory](https://github.com/JetBrains/kotlin-wrappers/blob/pre.604/kotlin-browser/src/jsMain/generated/web/idb/IDBFactory.kt#L13))are sealed/abstract, and because there wasn't a `external val indexedDB` (which you now added, thanks!) there wasn't a clear way to create a new instance. I didn't meant to imply that the classes shouldn't be sealed or abstract.
