### ISSUE TITLE
How to instantiate web.scroll.ScrollIntoViewOptions?

### ISSUE THREAD

**Issue by mattdornfeld** [JetBrains/kotlin-wrappers#2080]
I want to supply options to this method here

https://github.com/JetBrains/kotlin-wrappers/blob/a201bb09e708cc1fcb11179c14ae7c568e82c973/kotlin-browser/src/jsMain/generated/web/dom/Element.kt#L331

However when I try to instantiate the options class `ScrollIntoViewOptions {}` I get this error here
```
Interface ScrollIntoViewOptions does not have constructors
```

**Comment by Leonya** [comment]
You can't instantiate an interface. Instead, you create a `jso` that has a shape of this interface:

```kotlin
