### ISSUE TITLE
How to use Electron wrapper?

### ISSUE THREAD

**Issue by vahidooo** [JetBrains/kotlin-wrappers#2083]
Hi Kotlin wrappers team,

I am a big fan of your project and I am very grateful for your work.
Currently, I am trying to use the Electron wrapper in my project, but I am having some trouble understanding how to do. 
Particularly, I have tried to implement an application with simple connection between the main and renderer processes, like [this tutorial](https://www.tutorialspoint.com/electron/electron_inter_process_communication.htm), but I am not able to get it working in Kotlin.
I would be very grateful if you could help me to understand how to use the Electron wrapper to create such application.

Very thanks.

**Comment by sgrishchenko** [comment]
Electron is a freshly generated wrapper, and nobody has tested it yet. I will try to test it at some point, but if you provide concrete errors or peace of code, that doesn't work, it may help to figure out what is wrong with current wrappers.

**Comment by vahidooo** [comment]
Thanks for your reply. 

Don't worry about testing. I'm testing it. :))
I am really enjoying developing an Electron/React application entirely in Kotlin, thanks to your wrappers.

And about the problem, honestly, that was my wrong. I apologize for the confusion. I was using `ipcRenderer` inside my `main` function, but it should actually be in the `preload` script. Once I made that change, everything started working as expected.


Thanks again for your help!

**Comment by tokuhirom** [comment]
Just FYI. I wrote an example code of the kotlin-electron.
https://github.com/tokuhirom/kotlin-js-electron-demo
