### ISSUE TITLE
Node.js Buffer is missing "Buffer.from(string[, encoding])"

### ISSUE THREAD

**Issue by lppedd** [JetBrains/kotlin-wrappers#2086]
Doc URL: https://nodejs.org/api/buffer.html#static-method-bufferfromstring-encoding

![image](https://github.com/JetBrains/kotlin-wrappers/assets/19871649/d783b540-e8af-4637-8d7a-6bda3f1152ea)

**Comment by lppedd** [comment]
@sgrishchenko I was just wondering what/why there are hidden methods.  
For example, the below one is exactly what this issue needs.

https://github.com/JetBrains/kotlin-wrappers/blob/fc0a3ab51a8e50007b773a86db9171d8e9e631f7/kotlin-node/src/jsMain/generatedLegacy/node/buffer/Buffer.kt#L2018-L2029

**Comment by sgrishchenko** [comment]
@lppedd Usually we omit something, not because we don't want, but because our tooling doesn't allow us to handle something or Kotlin does not provide concepts to express something from TS. 

I will generate update for `buffer` module, this signature will be included there.

**Comment by sgrishchenko** [comment]
Fix 0549aa258774e524da07ea12f3dfd60d670e9270

**Comment by sgrishchenko** [comment]
@Leonya Can we publish `kotlin-wrappers` to ship these changes?
