### ISSUE TITLE
Please Provide a way to write direct HTML & CSS in Kotlin

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/kotlin-wrappers#2094]
**Is your feature request related to a problem? Please describe.**
Currently I use typescript and tsx files to get the benefit of components
My two basic needs are when I am writing a react project are `jsx` & css in js library like `emotion` , I get typesafety using typescript but I'd like to change that to use kotlin because kotlin is being shared in my other apps of mobile and desktop, I could even go about using compose-html if "ksx" and "css in kotlin" was a thing

I have never used the CSS dsl and HTML dsl and I'm not planning to do that because I prefer raw HTML and raw CSS, Nothing can top these. If Kotlin / Js could provide these two things , I would consider kotlin to be as good as typescript for me

Since `K2` Compiler is done, I am assuming this would allow kotlin js do these type of things and its planning to do these things as well to make development experience with kotlin as good as typescript, Otherwise typescript interoperability would be required so I can share my kotlin code of common modules to typescript and write my components in tsx.

**Describe the solution you'd like**
I would like `ksx` (jsx in kotlin) and "a css in kotlin library"

I would prefer a Kotlin compiler plugin that would provide a way to separate html into components like you can do in react JSX and also a Kotlin compiler plugin that would allow me to write styled components using direct CSS instead of CSS wrappers

- JSX in Kotlin should provide an easy way to write HTML with syntax highlighting, being able to separate components
- CSS in Kotlin should provide an easy way to write styled components with direct CSS & syntax highlighting
- CSS can be validated because it would be parsed by the compiler plugin (Even Better)
- HTML can be validated because it would be parsed by the compiler plugin (Even Better)

**Describe alternatives you've considered**
I use React JSX with emotion in typescript

**Comment by wakaztahir** [comment]
```
val styles = `
   background-color : red;
`

val ksxh1 = (<h1 class={styles.class()}>I am a red heading</h1>)

function MyH1(){
   return (
       <div><ksxh1 /></div>
   )
}
```

**Comment by aerialist7** [comment]
Hi @wakaztahir, this is an interesting request, but may I ask you a question?

If you prefer jsx-syntax, why would you want to use it inside Kotlin? Why not to use it separately from Kotlin?

Kotlin has a power of idiomatic DSL which we use instead of `jsx`. And for me it's very strange to replace it with something non-natural for language... 

Probably it's just my feelings about Kotlin

**Comment by wakaztahir** [comment]
I would use it inside Kotlin because I want to be able to share Kotlin common code with my web module.

Say I want to build a full stack app, Where kotlin is shared among many different platforms. I would want to share this common code with Web as well. But I don't want to write web UI in kotlin because I prefer jsx syntax, which is very easy. This becomes a blocker for me.

I share Kotlin on JVM, Android & I write web apps using Kotlin as well in Jetpack Compose but Jetpack compose renders with Skia not HTML. When I need to write something truly native for web. I always choose React / Solid. I always use React & Solid with CSS in JS library & typescript for typesafety & I think most web devs do that.

**Comment by aerialist7** [comment]
Still don't understand why not to use native syntax.

It's absolutely easy:

```
val StyledH1 = h1.styled {
    backgroundColor = NamedColor.red
}

val MyH1 = FC {
    div {
        StyledH1 {
           +"I am a red heading"
        }
    }
}
```

With native syntax you'll have full power of Kotlin and native integration with all other Kotlin shared code.

With your variant you will always build a new bicycle while you will integrate two different languages (even 3, cause jsx is not js)
