### ISSUE TITLE
ClickAwayListener no longer accepting children

### ISSUE THREAD

**Issue by lucgirardin** [JetBrains/kotlin-wrappers#2106]
Hi there! With the recent versions of Kotlin Wrappers, I am no longer able to do:

```
Popper {
    ClickAwayListener {
        ReactHTML.img {
        }
    }
}
```

 and get the error `Unit' can't be called in this context by implicit receiver`. Seems like ClickAwayListener is no longer accepting children. Any idea on how to fix that?

**Comment by aerialist7** [comment]
/

**Comment by turansky** [comment]
Temp WA:
```kotlin
Popper {
    ClickAwayListener {
        // TODO: remove after wrappers update
        this as PropsWithChildren
        
        img {
        }
    }
}
```

**Comment by aerialist7** [comment]
@lucgirardin, thanks for the report. Now you can set `children` of `ClickAwayListener` directly.
But I will improve the behavior soon.

```
        ClickAwayListener {
            children = img.create()
        }
```
