### ISSUE TITLE
Detect the issue from onChange callback function from react components

### ISSUE THREAD

**Issue by devfront216** [JetBrains/kotlin-wrappers#2110]
**Is your feature request related to a problem? Please describe.**
Now, I am working on the integration of the recharts brush component. (https://recharts.org/en-US/api/Brush). And they are providing onChange callback function(https://recharts.org/en-US/api/Brush#onChange) to allow the handler of changing the active scope of brush.

The current issue is that when I tried to get the active scope from onChange callback function, it's only working with 1 step. But from the react project, it's working smoothly with right drug and drop events.

**Describe the solution you'd like**
I think this can be related with timeout and syncing up with timer and internal component state.
Here is react application code for brush.
https://github.com/recharts/recharts/blob/master/src/cartesian/Brush.tsx

**Comment by turansky** [comment]
Could you provide small example, where problem will be reproduced?
