### ISSUE TITLE
Kotlin-mui: The MUI Card-Component is throwing an "Unresolved reference" error for the basic props "id" and "className"

### ISSUE THREAD

**Issue by flomar77** [JetBrains/kotlin-wrappers#2111]
Using any kotlin-wrappers-version above pre.607 (including latest), the MUI Card component is missing some basic props. I am not able to use “className” or “id” on this component and the JS will not compile.

I am guessing that props from `react.dom.html.HTMLAttributes<web.html.HTMLDivElement>` are actually missing because it is not there anymore (new `PaperOwnProps`)

Errors are `Unresolved reference: className `or `Unresolved reference: id`  using f.e:
```
Card {
    className = ClassName("my-classname")
    id = "my-id"
}
```

**Comment by aerialist7** [comment]
.
