### ISSUE TITLE
ClickAwayListener woes

### ISSUE THREAD

**Issue by lucgirardin** [JetBrains/kotlin-wrappers#2123]
I am having difficulties with when I use the `ClickAwayListener` component with recent version of Kotlin Wrappers. It used to work in the past (not sure since when it stopped working), but now I get 

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. `

I use it in conjonction with `Popper`, which is getting deprecated. Can this be the cause of the problem? If yes, then the `Popup` (https://mui.com/base-ui/react-popup/) replacement is not yet available. Otherwise, any advise about the direction in which I should hunt?

`pre.618` was last working version. Problem occurs with `pre.619-625`.

**Comment by aerialist7** [comment]
👀

**Comment by aerialist7** [comment]
👀

**Comment by lucgirardin** [comment]
My problem has been resolved by `pre-690`. Many thanks!
