### ISSUE TITLE
How to properly document namespaces

### ISSUE THREAD

**Issue by lppedd** [JetBrains/kotlin-wrappers#2128]
More of a question.  
Certain type declaration files export namespaces with associated documentation, e.g.,:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3a2e6cbf0c40245af9f02b5011da2ea713cd351d/types/vscode/index.d.ts#L9546-L9582C2

How would this kind of comments be copied to Kotlin's externals, since afaik KDoc doesn't allow documenting packages like Java?

**Comment by turansky** [comment]
Synthetic object with same FQN?
