### ISSUE TITLE
Duplicated object key in JsName value

### ISSUE THREAD

**Issue by lppedd** [JetBrains/kotlin-wrappers#2134]
Is the duplicated `utf8` key on purpose?

https://github.com/JetBrains/kotlin-wrappers/blob/7fd6be26fab2c5f63dffd7a554e0be412fc4d3a4/kotlin-node/src/jsMain/generated/node/crypto/CharacterEncoding.kt#L8

If it's not, I can see it also in (+`ucs2`):

https://github.com/JetBrains/kotlin-wrappers/blob/7fd6be26fab2c5f63dffd7a554e0be412fc4d3a4/kotlin-node/src/jsMain/generated/node/buffer/BufferEncoding.kt#L10

**Comment by lppedd** [comment]
@sgrishchenko A question related to this usage of `JsName`.  
Every time this enum-like interface is used it generates code like:
```js
var tmp = ({ascii: 'ascii', utf8: 'utf8', utf16le: 'utf16le', ucs2: 'ucs2', base64: 'base64', base64url: 'base64url', latin1: 'latin1', binary: 'binary', hex: 'hex'}).binary;
```

This means a new JS object is created each time. Isn't there a more efficient alternative?

**Comment by turansky** [comment]
> Isn't there a more efficient alternative?

Terser will inline value.
For common case (Node.js for example) we prepare optimized solution.

**Comment by lppedd** [comment]
> Node.js for example

That would be my use case. Sounds good! Thanks!
