### ISSUE TITLE
useRouteMatch hook is always null

### ISSUE THREAD

**Issue by bjoernmayer** [JetBrains/kotlin-wrappers#216]
Hey,

I was trying to use react-router-dom working with hooks.

After failing for quite some time I literally copy pasted the provided example:
https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/main/kotlin/example/ReactRouterDom.kt

Same outcome.
`useRouteMatch` always returns null.

I use `pre.97-kotlin-1.3.72` versions.
Router dom dependency looks like this:
```kotlin
implementation(npm("react-router-dom", "5.1.2"))
```

The hooks were added here: #172

Any idea?

**Comment by Leonya** [comment]
@subroh0508 please take a look.

**Comment by subroh0508** [comment]
@Leonya I have created Pull Request, please check it🙏

**Comment by Leonya** [comment]
Released in pre.98
