### ISSUE TITLE
some problems when wrapper antd

### ISSUE THREAD

**Issue by iamcyw** [JetBrains/kotlin-wrappers#2167]
in js:
```
import { Layout, Menu, theme } from 'antd';
const { Header, Content, Footer, Sider } = Layout;
<Layout>
      <Header>
     </Header>
</Layout>
```
in kotlin:
```
@JsModule("antd")
@JsNonModule
@JsName("Layout")
external val Layout: FC<LayoutProps>
```

**But I don't know how to use Header in kotlin,Is there any hint??**
[antd layout code](https://github.com/ant-design/ant-design/blob/8c45c73222b4edafb1c5f8cac47cf8195d9ac77f/components/layout/index.ts)
[layout doc](https://ant.design/components/layout)

**Comment by turansky** [comment]
```kotlin
@file:JsModule("antd")

external object Layout: FC<LayoutProps> {
    val Header: FC<HeaderProps>
    val Content: FC<ContentProps>
    val Footer: FC<FooterProps>
    val Sider: FC<SiderProps>
}
```

**Comment by iamcyw** [comment]
> ```kotlin
> @file:JsModule("antd")
> 
> external object Layout: FC<LayoutProps> {
>     val Header: FC<HeaderProps>
>     val Content: FC<ContentProps>
>     val Footer: FC<FooterProps>
>     val Sider: FC<SiderProps>
> }
> ```
@turansky  I tried it, the layout is fine, but adding the header 
 has wrong.
<img width="1800" alt="image" src="https://github.com/JetBrains/kotlin-wrappers/assets/11208441/b6058d0e-75a3-4981-a12b-26d02a81e8d8">

**Comment by turansky** [comment]
1. Could you test following?
```kotlin
console.log(Layout)
console.log(Layout.Header)
```

2. Could you test following?
```kotlin
Layout {
    // I don't know why `Header` works fine, it looks like props with broken nullability
    Layout.Header {
    }
}
```

**Comment by iamcyw** [comment]
> ```kotlin
> @file:JsModule("antd")
> 
> external object Layout: FC<LayoutProps> {
>     val Header: FC<HeaderProps>
>     val Content: FC<ContentProps>
>     val Footer: FC<FooterProps>
>     val Sider: FC<SiderProps>
> }
> ```

@turansky Sorry, I made a mistake, I used the interface. When I change it to object, everything is fine

**Comment by iamcyw** [comment]
@turansky Sorry, I have a new question to ask.
Can we wrap this use kotlin?

<img width="1514" alt="image" src="https://github.com/JetBrains/kotlin-wrappers/assets/11208441/d55e4539-59e8-4737-b1cf-8b8556e8d7ec">

**Comment by turansky** [comment]
I don't know solution for generic `T`.

**Comment by leerenbo** [comment]
@citywalki Hi，I have the same problem as you.
I just spent a day wrapper the DayJS library. I'm about to wrapper the Antd library. How's your progress?
How about we wrapper together and contribute to Kotlin-wrappers?

**Comment by citywalki** [comment]
@leerenbo sorry, I gave up use kotlin
