### ISSUE TITLE
Mui Component Inhereted Parameters

### ISSUE THREAD

**Issue by lsafer-meemer** [JetBrains/kotlin-wrappers#2169]
**Is your feature request related to a problem? Please describe.**
In `mui-mterial` wrapper: `external interface CardOwnProps` does not inherit from `external interface PaperOwnProps` even though it does in npm package `@mui/material` and I think this is not the only component.

**Describe the solution you'd like**
wrapper external interfaces gets updated to include inherited interfaces. 
 
**Describe alternatives you've considered**

**Additional context**
https://github.com/JetBrains/kotlin-wrappers/blob/7d67d4dfcef76b60fe661ef831a770568de54680/kotlin-mui-material/src/jsMain/generated/mui/material/Card.kt#L19C1-L35C2

**Comment by aerialist7** [comment]
Hi @lsafer-meemer, thank you for the report! 
Will fix
