### ISSUE TITLE
Issue with importing/ using ClickAwayListener

### ISSUE THREAD

**Issue by lsafer-meemer** [JetBrains/kotlin-wrappers#2177]
**Is your feature request related to a problem? Please describe.**
Importing ClickAwayListener returns undefined at runtime due to `mui/base` does not 
export it as a default import. Instead, as a named export.

Plus: Someone should check if other `mui/base` components suffers the same issue

**Describe the solution you'd like**
Change `@JsName("default")` to `@JsName("ClickAwayListener")`

**Describe alternatives you've considered**
My correct temporary fix:

```kt
@JsNonModule
@JsModule("@mui/base/ClickAwayListener")
private external object ClickAwayListenerModule {
    @JsName("ClickAwayListener")
    val ClickAwayListener: FC<ClickAwayListenerProps>
}
```

**Additional context**
[Issue: [base-ui][ClickAwayListener] Trouble with importing it](https://github.com/mui/material-ui/issues/39142)

https://github.com/JetBrains/kotlin-wrappers/blob/8b491da103de3094690d193fdd69f25523d7e025/kotlin-mui-base/src/jsMain/generated/mui/base/ClickAwayListener.kt#L38C1-L51C65

**Comment by lucgirardin** [comment]
This may very be related to my issue, which persists since pre.618: https://github.com/JetBrains/kotlin-wrappers/issues/2123

**Comment by aerialist7** [comment]
Noted

**Comment by lucgirardin** [comment]
I believe this issue has been resolved by `pre-690`.
