### ISSUE TITLE
IR Link problem in pre.675 and pre.676

### ISSUE THREAD

**Issue by robertfmurdock** [JetBrains/kotlin-wrappers#2193]
"IrLinkageError: Function 'createHmac' can not be called: Function uses class 'Duplex' (via class 'Hmac') that simultaneously inherits from 2 classes: 'Readable', 'Writable'"

This error occurs at runtime when calling the "node.crypto.createHmac" function. Works fine in pre.674.

**Comment by turansky** [comment]
@robertfmurdock Do you use `Hmac` as `Readable` or as `Writable` after that?
What is your use case?

**Comment by robertfmurdock** [comment]
Hm, I guess I'm not sure.

calling function:

```

    private fun String.hmac256Hash() = createHmac("sha256", signingSecret)
        .update(this)
        .digest()
        .toString(BufferEncoding.hex)

```

**Comment by robertfmurdock** [comment]
AFAICT just importing the Hmac type is enough to trigger the error.

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by turansky** [comment]
@robertfmurdock Solution was released in `pre.683`. Does it work for you?

**Comment by robertfmurdock** [comment]
Just checked - looks good to me! Thanks ya'll.
