### ISSUE TITLE
unstable_useTimeout not found

### ISSUE THREAD

**Issue by lucgirardin** [JetBrains/kotlin-wrappers#2216]
I updated from 1.0.0-pre.693 to pre.700 and now get the following error:

`export 'unstable_useTimeout' (imported as 'useTimeout') was not found in '@mui/utils' (possible exports: HTMLElementType, chainPropTypes, clamp, deepmerge, elementAcceptingRef, elementTypeAcceptingRef, exactProp, formatMuiErrorMessage, getDisplayName, getValidReactChildren, globalStateClasses, integerPropType, internal_resolveProps, isGlobalState, isPlainObject, ponyfillGlobal, refType, unstable_ClassNameGenerator, unstable_capitalize, unstable_composeClasses, unstable_createChainedFunction, unstable_debounce, unstable_deprecatedPropType, unstable_detectScrollType, unstable_generateUtilityClass, unstable_generateUtilityClasses, unstable_getNormalizedScrollLeft, unstable_getScrollbarSize, unstable_isGlobalState, unstable_isMuiElement, unstable_ownerDocument, unstable_ownerWindow, unstable_requirePropFactory, unstable_setRef, unstable_unsupportedProp, unstable_useControlled, unstable_useEnhancedEffect, unstable_useEventCallback, unstable_useForkRef, unstable_useId, unstable_useIsFocusVisible, usePreviousProps, visuallyHidden)`

No need for immediate action, just wanted to bring this to your attention!

**Comment by aerialist7** [comment]
Thank you for the report

**Comment by aerialist7** [comment]
@lucgirardin, checked - no problems after updating in my case
https://github.com/karakum-team/kotlin-mui-showcase/actions/runs/8036303862/job/21949847708

**Comment by turansky** [comment]
@lucgirardin Could you please check if problem reproduced with `pre.706`?

**Comment by lucgirardin** [comment]
@turansky Tried today with `pre.708`:  everything working (very) well :-) Many thanks Victor!
