### ISSUE TITLE
Unnecessary qualification of Node.js Assert module

### ISSUE THREAD

**Issue by lppedd** [JetBrains/kotlin-wrappers#2220]
Certain functions are under a redundant qualifier, e.g.:

https://github.com/JetBrains/kotlin-wrappers/blob/29f1ef5ca4a38510aed41058ba8631138349ef3a/kotlin-node/src/jsMain/generated/node/assert/fail.kt#L4

This will throw at runtime. For example, with `fail` it will generate:
```js
var fail = $module$node_assert_strict_ghzeb6.assert.fail;
```
But the correct one is:
```js
var fail = $module$node_assert_strict_ghzeb6.fail;
```

See [all of them](https://github.com/search?q=repo%3AJetBrains%2Fkotlin-wrappers+%40file%3AJsQualifier%28%22assert%22%29&type=code).

**Comment by sgrishchenko** [comment]
Thanks a lot for your report, I tried to remove all awkward qualifiers around Node declarations.

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
