### ISSUE TITLE
node.fs.stat: overload resolution ambiguity

### ISSUE THREAD

**Issue by vlsi** [JetBrains/kotlin-wrappers#2223]
https://github.com/JetBrains/kotlin-wrappers/blob/356dd827256c6d37574b01e8101e8713524ebacf/kotlin-node/src/jsMain/generated/node/fs/stat.suspend.kt#L8

https://github.com/JetBrains/kotlin-wrappers/blob/356dd827256c6d37574b01e8101e8713524ebacf/kotlin-node/src/jsMain/generated/node/fs/stat.suspend.kt#L20

![sample error](https://github.com/JetBrains/kotlin-wrappers/assets/213894/ca263df2-a301-4628-a5db-c2163230a3d8)

1.0.0-pre.709

**Comment by lppedd** [comment]
I'm conflicted on what the better approach is:

1. use `LowPriorityInOverloadResolution`
2. rename the functions and use `@JsName`

**Comment by turansky** [comment]
It can be splinted without conflict

**Comment by turansky** [comment]
It's regression, we can fix it without annotations and renaming

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
