### ISSUE TITLE
node.fs.createReadStream: overload resolution ambiguity

### ISSUE THREAD

**Issue by vlsi** [JetBrains/kotlin-wrappers#2224]
https://github.com/JetBrains/kotlin-wrappers/blob/356dd827256c6d37574b01e8101e8713524ebacf/kotlin-node/src/jsMain/generated/node/fs/createReadStream.kt#L72-L74

```kotlin
var name: String = ...
createReadStream(name)
```

yields `overload resolution ambiguity`

1.0.0-pre.709

**Comment by sgrishchenko** [comment]
@Leonya Could you release this bugfix, please?
