### ISSUE TITLE
Add online API reference site (e.g. Dokka)

### ISSUE THREAD

**Issue by aSemy** [JetBrains/kotlin-wrappers#2228]
### Is your feature request related to a problem? Please describe.

I want to be able to look and search through at the available classes and functions on an easily accessible website.

I want to be able to create 'external links' in my own Dokka websites

### Describe the solution you'd like

Create a Dokka HTML website.

Host the API reference documentation on GitHub Pages.

### Describe alternatives you've considered

Searching the source code through GitHub (although this is not easy, and isn't pretty. It's also hard to link to. It doesn't work for external Dokka links).

### Additional context

I see that the Gradle build config for this project is well structured and follows Gradle best practices. The official Dokka Gradle Plugin would unfortunately break this. Instead, I'd be happy to create a PR that would add [Dokkatoo](https://github.com/adamko-dev/dokkatoo), which would be compatible.

**Comment by turansky** [comment]
> Host the API reference documentation on GitHub Pages.

Links to original documentations?

**Comment by aSemy** [comment]
> > Host the API reference documentation on GitHub Pages.
> 
> Links to original documentations? :)

Sorry, I don't understand, could you elaborate?

**Comment by turansky** [comment]
Which "API reference documentation" you want to collect?
In common case original (JS documentation) is what required for user
