### ISSUE TITLE
How to implement @JsPlainObject?

### ISSUE THREAD

**Issue by Eramedy** [JetBrains/kotlin-wrappers#2229]
I'm trying make POST request using fetch, also I would like to add CORS mode but can't find any example how to implement the RequestInit object.
Could someone please help to figure this out

**Comment by turansky** [comment]
To construct JSO you can use special factory function `jso` ([example](https://github.com/karakum-team/kotlin-react-table-sample/blob/4f6968d9ce91b64b79ede31142a719f4341ab4b8/src/jsMain/kotlin/team/karakum/hooks/useDeleteUser.kt#L33)).
In future we plan to provide strict factory functions.

**Comment by Eramedy** [comment]
Works, thank you @turansky
