### ISSUE TITLE
How to cast a hook? Or how to get it's value in the right type?

### ISSUE THREAD

**Issue by edpichler** [JetBrains/kotlin-wrappers#2231]
I need to pass a Double as a parameter in a method, although, the origin is from a hook.

So I have:  `var total = useState(0.0)`

How can I cast it as a Double? Or get the Double value?

I am having a hard time finding the syntax.

**Comment by turansky** [comment]
For now we support 2 syntaxes:
1. Default
```
var total by useState(0.0)
```

2. With extended setter
```
val (total, setTotal) = useState(0.0)
```

JFYI For such questions you can use official [Kotlin Slack](https://kotlinlang.org/community/) - in common case it will be faster

**Comment by edpichler** [comment]
My bad! I was using `=` instead of `by` to declare my variable.
