### ISSUE TITLE
Use kotlin-styled link is broken (404)

### ISSUE THREAD

**Issue by ellet0** [JetBrains/kotlin-wrappers#2234]
On [this](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-css/README.md) page

On the last line `When writing CSS for the browser you should probably use [kotlin-styled](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-styled) instead. It provides a user-friendly facade to kotlin-css.` the link is simply not working

**Comment by turansky** [comment]
@ellet0 thank you. Link fixed
