### ISSUE TITLE
actions-toolkit: Add JsPlainObjects, eg core/InputOptions

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/kotlin-wrappers#2242]
**Is your feature request related to a problem? Please describe.**
Some projects use the new JsPlainObjects annotation from Kotlin 2.0.0, but not actions-toolkit.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Do you have any pointer to create a PR? It's declared [here](https://github.com/karakum-team/types-kotlin/blob/main/buildSrc/src/main/kotlin/actions-declarations.gradle.kts) but I am lost.

**Comment by turansky** [comment]
Hi @hfhbd! Thank you for reporting!
We should test it at start on base libraries (where JSO interfaces marked in specifications/IDLs), when Kotlin 2.0 will be released.
After that we will continue work with compiler checks, which don't work in K1.

**Comment by hfhbd** [comment]
I updated my library to pre545 but you don't use `kotlinx.js.JsPlainObject`, do you? So there is no generated constructor function yet 🤔

**Comment by turansky** [comment]
It will be available only after migration on Kotlin 2.0
