### ISSUE TITLE
node.http.ServerResponse.writeHead overload ambiguity

### ISSUE THREAD

**Issue by vlsi** [JetBrains/kotlin-wrappers#2254]
**Is your feature request related to a problem? Please describe.**

```kotlin
res.writeHead(200, "Ok", undefined.unsafeCast<OutgoingHttpHeaders>())
```

Currently, there's no way to omit `headers` parameter as Kotlin compiler is confused between `OutgoingHttpHeaders` and `ReadOnlyArray<OutgoingHttpHeader>` overloads.

<img width="1153" alt="missing writeHead(int, string) overload" src="https://github.com/JetBrains/kotlin-wrappers/assets/213894/08692235-61b7-4438-9ecc-a86dc09da058">

**Describe the solution you'd like**

```kotlin
res.writeHead(200, "Ok")
```

**Additional context**

* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/86953d1148f231c8f1c534e4a718ac4fa7888767/types/node/http.d.ts#L841-L846
* https://github.com/JetBrains/kotlin-wrappers/blob/28da3ba19f48d2c9dc2aa78f2ef1892e396aa2aa/kotlin-node/src/jsMain/generated/node/http/ServerResponse.kt#L161-L165

**Comment by turansky** [comment]
Fixed in `pre.727`
