### ISSUE TITLE
ReactRouterDom: NavLinkProps::isActive type is wrong

### ISSUE THREAD

**Issue by bjoernmayer** [JetBrains/kotlin-wrappers#226]
Hey,

looks like the type declaration here is wrong:
https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-router-dom/src/main/kotlin/react/router/dom/routing.kt#L60

According to react[ router documentation](https://reacttraining.com/react-router/web/api/NavLink/isactive-func) it should be
```
var isActive: ((Boolean, RouteResultLocation) -> Boolean)?
```

**Comment by Leonya** [comment]
@subroh0508 would you take a look please?
