### ISSUE TITLE
Add `@actions/github`

### ISSUE THREAD

**Issue by be-hase** [JetBrains/kotlin-wrappers#2260]
I would be happy if @actions/github were available. Personally, I use this the most when creating custom actions.

**Comment by turansky** [comment]
@Leonya Could you please release these changes?

**Comment by turansky** [comment]
Feedback is welcome! :)

**Comment by turansky** [comment]
Feedback is welcome! :)

cc @vlsi

**Comment by be-hase** [comment]
thanks :)
