### ISSUE TITLE
Function types with `this` access

### ISSUE THREAD

**Issue by Coneys** [JetBrains/kotlin-wrappers#2267]
Hello

To manipulate / configure libraries written in plain JavaScript, there should be a way in Kotlin to create function types with _this_ access. 

For example, in Javascript map library "Mapbox Draw" function type is used to [configure drawing mode](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/MODES.md#writing-custom-modes):

```
LotsOfPointsMode.onKeyUp = function(state, e) {
  if (e.keyCode === 27) return this.changeMode('simple_select');
};
```
Is there any workaround to replicate _this_ access in Kotlin?

**Comment by turansky** [comment]
@Coneys `JsContextFunction` is what you need.
While `pre.755` isn't released you can copy `JsContextFunction` with adapters in your project.

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
