### ISSUE TITLE
IR Errors in node.stream

### ISSUE THREAD

**Issue by robertfmurdock** [JetBrains/kotlin-wrappers#2287]
`e: java.lang.IllegalStateException: IrTypeParameterPublicSymbolImpl for [ node.stream/StreamOptions.Companion.invoke|invoke(web.abort.AbortSignal?;kotlin.Double?;kotlin.Boolean?;kotlin.Function2<kotlin.Throwable?,kotlin.Function1<kotlin.Throwable?,kotlin.Unit>,kotlin.Unit>?;kotlin.Boolean?;kotlin.Function1<kotlin.Function1<kotlin.Throwable?,kotlin.Unit>,kotlin.Unit>?;kotlin.Boolean?){0§<node.stream.Stream>}[0] <- Local[<TP>,0|TYPE_PARAMETER name:T index:0 variance: superTypes:[node.stream.Stream] reified:false] ] is already bound: TYPE_PARAMETER name:T index:0 variance: superTypes:[node.stream.Stream] reified:false`

This was introduced recently, then fixed, then reintroduced with build 766.

Related previous issue: https://github.com/JetBrains/kotlin-wrappers/issues/2275

**Comment by turansky** [comment]
> This was introduced recently

@robertfmurdock We just add workarounds for compiler :)

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
