### ISSUE TITLE
React router. How to add server routing? 

### ISSUE THREAD

**Issue by anji-mito** [JetBrains/kotlin-wrappers#2291]
hi, I need your help with routing 

```kotlin
var appRouter = createBrowserRouter (
    arrayOf(
        jso {
            path = "/"
            element = Page.create()
        },
        jso {
            path = "/authors"
            element = AuthorTable.create()
        },
        jso {
            path = "/genres"
            element = GenreList.create()
        },
        jso {
            path = "*"
            element = ErrorPage.create()
        }
    )
)
```

When i Open http://localhost:8080/authors it says "Cannot GET /authors". What can i try to do, i wasted the whole day to try figure out, but still cant do it by myself, need your help

```kotlin
fun main() {
    val root = document.createElement("root")
        .also { document.body.appendChild(it) }
    createRoot(root)
        .render(Fragment.create {
            RouterProvider {
                router = appRouter
            }
        })
}
```

```kotlin
val GenreList = FC {
    p {
        +"Genre list"
    }
}
```

**Comment by turansky** [comment]
You have 2 options:
1. If you have server like Ktor - you should configure **server** routing, to return your `index.html` from specified ([or all](https://ktor.io/docs/server-routing.html#tailcard)) routes (like `/`, `/authors`, `/about`)
2. If you have static site - you can use hash router, [like here](https://karakum-team.github.io/kotlin-mui-showcase)

**Comment by anji-mito** [comment]
Im using Spring Boot for backed, from there Im getting data with react query, but i cant to understand how to set up routes

**Comment by turansky** [comment]
> but i cant to understand how to set up routes in react + kotlin/js as fronted

You should do it in Spring :)

**Comment by turansky** [comment]
> but i cant to understand how to set up routes in react + kotlin/js as fronted

For all routes, which you have you should return your `index.hml` - it's server configuration (Spring configuration)

**Comment by anji-mito** [comment]
Thanks for quick answers:)

What if I want to use a third party API just to get data in JSon format, how can I set up navigation in my react + kotln/js application

**Comment by turansky** [comment]
> What if I want to use a third party API just to get data in JSon format

No problem - you can do this

> how can I set up navigation in my react + kotln/js application

Please read [my first answer](https://github.com/JetBrains/kotlin-wrappers/issues/2291#issuecomment-2213012892)
Short answer - it depends on your server (static/Spring/Ktor/...)
Instruction for Ktor - https://ktor.io/docs/server-routing.html

**Comment by anji-mito** [comment]
Im trying to do [like here](https://karakum-team.github.io/kotlin-mui-showcase), but it wont work for me and I dont understand why, also is this [example](https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/old/src/jsMain/kotlin/example/ReactRouterDom.kt) wont work in latest version of react route?

**Comment by anji-mito** [comment]
[example](https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/old/src/jsMain/kotlin/example/ReactRouterDom.kt)
Oh, actually this example worked for me, thanks a lot for answerings!!!
