### ISSUE TITLE
Web Audio

### ISSUE THREAD

**Issue by aaziz993** [JetBrains/kotlin-wrappers#2292]
Hi. Can you please help me to understand how I can register AudioWorkletProceccor inside kmp project. I dont want to use separate js file to implement and register it.

**Comment by turansky** [comment]
Options:
1. Separate subproject + Gradle configuration (like `jsModuleImplementation`)
2. File to file compilation

**Comment by aaziz993** [comment]
> Options:
> 
> 1. Separate subproject + Gradle configuration (like `jsModuleImplementation`)
> 2. File to file compilation

I didn't understand. I already have KMP with jsMain and there is AudioWorkletProcessor implementaion like this:
```
public class AudioInputProcessor : AudioWorkletProcessorImpl {
    override fun process(
        inputs: ReadonlyArray<ReadonlyArray<Float32Array>>,
        outputs: ReadonlyArray<ReadonlyArray<Float32Array>>,
        parameters: Record<String, Float32Array>,
    ): Boolean {
        val input = inputs[0]
        if (input[0].length > 0) {
            port.postMessage(input)
        }
        return true
    }
}
```
The only thing I cannot understand how to register it using registerProcessor method of AudioWorkletGlobalScope class from kotlin-wrappers. Where to get instance of AudioWorkletGlobalScope.

**Comment by turansky** [comment]
```kotlin
val audioContext = AudioContext();
audioContext.audioWorklet.addModule("separate-file-with-processor-and-fine-global-scope.js");
```

[Source](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletGlobalScope)
