### ISSUE TITLE
Error in react-select when trying to set value with multiple values (isMulti enabled)

### ISSUE THREAD

**Issue by avivas-teg** [JetBrains/kotlin-wrappers#2295]
I have this Select component with isMulti set to true, I need to set the value property when building it with a list of values because this is part of a configuration page and I need the old selected values to get displayed so I can remove some values that I don't want anymore and add some new values too. It works fine if I delete the line value = Value(...) but when I reload obviously I lose the values I selected previously, and what I need is to set the value property with that values I selected before. I save them when onChange event is triggered and then give them back to the component by using props in linesSelected var, but I get an error beacuse I have a list of values (as isMulti is enabled) and it seems I only can set one value to the value property.

```
class SelectOption(val value: String, val label: String)

//This are props given to component where I use Select
var linesSelected: List<String>?
var onSelectLines: suspend (List<SelectOption>?) -> Unit
var lineNames: List<SelectOption>
//End of props

//Select component: SelectLines by Component<SelectLiniesProps> { props ->
Select<SelectOption, Nothing> {
            isMulti = true
            options = OptionsOrGroups(props.lineNames.toTypedArray())
            getOptionLabel = SelectOption::label
            getOptionValue = SelectOption::value

            value = Value(props.linesSelected?.map { SelectOption(it, it) }) //**Here I have the error: Type mismatch. Required: SelectOption Found: List<SelectOption>**

            onChange = { newValue, _ ->
                mainScope.launch {
                    if (newValue != null)
                    {
                        props.onSelectLines(newValue.asArray().map { it })
                    }
                    else
                    {
                        props.onSelectLines(emptyList())
                    }
                }
            }
        }
```

Anyone knows how to do this?

Thank you in advice :)

**Comment by turansky** [comment]
```kotlin
val linesSelected = props.linesSelected
val selectedValue = useMemo(linesSelected) {
    val values = if (linesSelected != null) {
        // array required, not List
        linesSelected.map { SelectOption(it, it).toTypedArray()
    } else emptyArray()
    
    Value(value = values)
}

Select<...> {
    value = selectedValue
} 
```

**Comment by avivas-teg** [comment]
That's it, now it's working fine. Thank you very much! Would be great to have some examples about the libraries and how to use them :)
