### ISSUE TITLE
React/EffectBuilder problems

### ISSUE THREAD

**Issue by robertfmurdock** [JetBrains/kotlin-wrappers#2297]
Recent builds seem to have some IR problems with react... haven't done much research but looks to have started with build 772

`IrLinkageError: Expression can not be evaluated: Expression uses unlinked class symbol 'react/EffectBuilder|null[0]'`

**Comment by turansky** [comment]
In `pre.773` `EffectBuilder` [was removed](https://github.com/JetBrains/kotlin-wrappers/blob/df545d59092dff13c3666664466c9e31975ef41c/CHANGELOG.md#pre773)

Do you use it directly?
If yes - probably incremental compilation problem - `./gradlew clean` should help.

**Comment by robertfmurdock** [comment]
Ah, unexpected further upstream change resulted in mismatching versions of wrappers, which became this problem. Root cause appears to be the change to the useEffect {cleanup(sldkfjsdlf)} API

**Comment by robertfmurdock** [comment]
I'll close this here then - thanks for the additional brain power
