### ISSUE TITLE
GitHub Actions: setFailed uses kotlin.Error but should use js.Error => kotlin.Throwable

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/kotlin-wrappers#2298]
https://github.com/actions/toolkit/blob/1db73622df8a649a01cb12b8a217c903419009fa/packages/core/src/core.ts#L220
```typescript
export function setFailed(message: string | Error): void {}
```

is wrongly mapped to 
```kotlin
fun setFailed(error: kotlin.Error) {}
```
But kotlin.Error inherits from kotlin.Throwable that is marked as `@JsName("Error")`, and many exceptions actually inherit kotlin.Exception inheriting kotlin.Throwable, not kotlin.Error.

So it should be:
```kotlin
fun setFailed(error: kotlin.Throwable) {}
```

**Comment by hfhbd** [comment]
Maybe it does affect other `Error` usage as well

**Comment by turansky** [comment]
@Leonya Could you please release these changes?
