### ISSUE TITLE
I found that the kotlin-redux library has been deleted in the master branch.How does the Kotlinjs team handle global state management?

### ISSUE THREAD

**Issue by leerenbo** [JetBrains/kotlin-wrappers#2385]
I found that the kotlin-redux library has been deleted in the master branch.

For React projects, when it comes to sharing props across hierarchical components, global state management is still necessary. How does the Kotlinjs team handle global state management? Not Redux. Any other implementation solutions are fine.

**Comment by turansky** [comment]
1. [TanStack Query](https://tanstack.com/query/latest) - for server state. Contexts - for clients state
  It's what I personally use. With React 19 and `use` for `Context` it will be even more useful.
2. Probably [Zustand](https://github.com/pmndrs/zustand) - if you are ready to write simple wrappers for yourself

Fallback - you can continue use Redux. Wrappers for Redux still work :(
```kotlin
dependencies {
    implementation("org.jetbrains.kotlin-wrappers:kotlin-redux:4.1.2-pre.785")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-redux:7.2.6-pre.785")
}
```

**Comment by leerenbo** [comment]
Considering the data flow ideology of Flux and the difficulty of wrapper.
Using React's reducer + context and customizing useXXX Hook is easier [doc](https://react.dev/learn/scaling-up-with-reducer-and-context)

A solution for integrating asynchronous HTTP requests is also needed ,Ktor?. 

**I really hope there is a document on best practices.**

**Comment by turansky** [comment]
> A solution for integrating asynchronous HTTP requests is also needed ,Ktor?.

Suspend `fetch` is fine

**Comment by joffrey-bion** [comment]
It would be nice to at least mention the removal in the release notes of the relevant release. I went through all of them to find it, to no avail :(

**Comment by turansky** [comment]
Changelog [updated](https://github.com/JetBrains/kotlin-wrappers/commit/afa2eb11403ebddae081d9fa4b39333380ad0e73)
