### ISSUE TITLE
kotlin-react  can't render  Component Element And dynamic Component .

### ISSUE THREAD

**Issue by leerenbo** [JetBrains/kotlin-wrappers#2390]
I know that the principle of JSX is that webpack, through plugins, compiles .jsx into .js ReactJS APIs, like nesting with createElement.

I don't understand the principles and implementation methods of kotlin ReactDsl.  There are two situations where I think it should be able to render, but it doesn't.

```kotlin
package npms.antd

import react.ForwardRefExoticComponent
import react.PropsWithChildren
import react.PropsWithRef

@JsModule("antd")
@JsNonModule
external val ANTD: dynamic;

@JsModule("antd")
@JsNonModule
external class Antd {
    interface ButtonProps : PropsWithRef<Any>, PropsWithChildren {
    }

    companion object {
        val Button: ForwardRefExoticComponent<ButtonProps>
    }

}

```

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/92257eca-c052-434c-afac-d521538b06fb">

Why the two buttons don't render?
What documents should I read to understand the principles and mechanisms of the react-wrapper?

**Comment by turansky** [comment]
1. `target = "es2015"` to avoid redundant `@JsNonModule` ([example](https://github.com/turansky/kfc-plugins/blob/a59ab971019ed2da48762313ca655300aba7b727/kfc/kfc-gradle-plugin/src/main/kotlin/io/github/turansky/kfc/gradle/plugin/KotlinMultiplatform.kt#L62))
2. `@file:JsModule("antd")` on file, without `Antd` object is what you need
3. `createElement` create element, if you want to connect it with parent - use `+` operator
4. Why you don't want to use DSL? Please check [examples 9 and 10](https://github.com/JetBrains/kotlin-wrappers?tab=readme-ov-file#examples) for more information

**Comment by leerenbo** [comment]
@turansky When set `target = "es2015"`  ,browser source maps disappear.
like this
<img width="1635" alt="image" src="https://github.com/user-attachments/assets/16902b4e-45c9-48e5-8f1e-3d6486ee3f20">

settings:
```kotlin
tasks.withType(Kotlin2JsCompile::class.java).configureEach {
    compilerOptions {
        target.set("es2015")
        freeCompilerArgs.addAll(
            "-Xdont-warn-on-error-suppression",
            "-Xgenerate-polyfills=false",
            // TODO: Enable after resolving
            //  https://youtrack.jetbrains.com/issue/KT-67355
            // "-Xir-generate-inline-anonymous-functions",
        )
    }
}
```
or
```kotlin
kotlin {
    js() {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            target = "es2015"
        }
...
```

When set sourceMapEmbedSources, it comes back.  but not default setting. i don't know what's going on here.
---
```
kotlin {
    js() {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            target = "es2015"
            sourceMap = true
            sourceMapEmbedSources = JsSourceMapEmbedMode.SOURCE_MAP_SOURCE_CONTENT_ALWAYS
        }
```

**Comment by leerenbo** [comment]
> * `@file:JsModule("antd")` on file, without `Antd` object is what you need
> * `createElement` create element, if you want to connect it with parent - use `+` operator. It's low level API for rare cases

It works.


> 4\. Why you don't want to use DSL? Please check [examples 9 and 10](https://github.com/JetBrains/kotlin-wrappers?tab=readme-ov-file#examples) for more information

I want to use DSL , but i don't want to wapper ui jslib.  or  I want auto generated useable wapper without modify.
Dynamic module button still don't work.   Dynamic module aimed no wrapper.

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/59ed5eaa-6292-47bd-9d59-41a902fefe68">

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/b7181508-3472-463b-a66c-a3b6877d84b9">

**Comment by turansky** [comment]
`Buttion` -> `Button`?

**Comment by leerenbo** [comment]
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/a2376c45-ba2d-4204-827b-5ee97f5bec24">

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/5dc0b287-aec2-4d02-b6f0-cdaaca98dab1">

<img width="1507" alt="image" src="https://github.com/user-attachments/assets/de0ac1e0-0067-4b0a-9430-31638cfc9240">

Fixed spelling errors.  Problem still.  ANTD.Button  translate as a function . not addChild as an ReactNode.

**Comment by turansky** [comment]
And it's expected. `dynamic` can't be used as receiver

**Comment by leerenbo** [comment]
Reasonable. 
As there is a lambda method following it which serves as an input parameter for a Button method, it is recognized as a method. At least I can use  `+ createElement`.

Wrapper a whole UI jslib is a huge workload.

I really appreciate your help @turansky .

close issure.
