### ISSUE TITLE
Tic-Tac-Toe example can't run perfectly. how to import .css?

### ISSUE THREAD

**Issue by leerenbo** [JetBrains/kotlin-wrappers#2393]
According to the Tic-Tac-Toe example [code prompts](https://github.com/JetBrains/kotlin-wrappers/blob/2cf4001fe85d579acf290537959c3aea7f338007/examples/old/src/jsMain/kotlin/example/TicTacToe.kt#L122), I added   require("TicTacToe.css")   in fun main(){...}, but there is no require(String) method available and thus it can't be compiled. 

```
        browser() {
            commonWebpackConfig() {
                cssSupport {
                    enabled.set(true)
                }
            }
        }
```
Webpack support is open, how to compile to import xxx.css in  compiled.js file?
How can I properly import the CSS styles?

**Comment by turansky** [comment]
Looks like question for [#javascript](https://kotlinlang.slack.com/archives/C0B8L3U69) slack channel ;)

**Comment by leerenbo** [comment]
@turansky    NO,it's not react example.
it's kotlin-wrappers example with  .kt

https://github.com/JetBrains/kotlin-wrappers/blob/2cf4001fe85d579acf290537959c3aea7f338007/examples/old/src/jsMain/kotlin/example/TicTacToe.kt#L122
