### ISSUE TITLE
Typesafe interop with JavaScript constructors

### ISSUE THREAD

**Issue by BernhardPosselt** [JetBrains/kotlin-wrappers#2400]
I need to interop with JavaScript APIs that expect certain constructors to exist. For instance sub types of https://foundryvtt.com/api/v12/classes/foundry.applications.api.ApplicationV2.html require a constructor that accepts a Configuration record, so that the subclass can be registered as a settings window like this:

```js
game.settings.registerMenu({
    type: ApplicationV2Subclass  // framework creates a new instance using a predefined Configuration object
})
```

Another subclass https://foundryvtt.com/api/v12/classes/foundry.applications.api.DocumentSheetV2.html requires a Configuration record with an additional document parameter (a Fat Model to handle Database I/O). 

All of these classes are also available as properties on these subclasses so that you can create new instances if you need to. Right now, there is no way to define that sub classes need to have a certain constructor, nor a way to define that a property on a JS class must have that signature and can be instantiated with a certain constructor call

Implementation discussions - #2399

**Comment by turansky** [comment]
@BernhardPosselt I added 2 additional adapters. Looks like they will be available only in next release (`pre.793`)
