### ISSUE TITLE
Older versions of react-wrappers missing from maven repository

### ISSUE THREAD

**Issue by TorRanfelt** [JetBrains/kotlin-wrappers#2423]
We use old versions of the kotlin react-wrappers:
org.jetbrains:kotlin-react:16.13.1-pre.124-kotlin-1.4.10
org.jetbrains:kotlin-react-dom:16.13.1-pre.124-kotlin-1.4.10
org.jetbrains:kotlin-react-router-dom:5.1.2-pre.125-kotlin-1.4.10

For some reason they are no longer in the maven repository. At some point in the future we will update our react libraries and react-wrapper libraries, but even when we have done this we still need these old versions to be in the maven repository.

The reason is that we have a version of our software for each year and users need to be able to use older versions (it doesn't matter why; they just do). These old versions we don't really do much with unless there is a breaking bug or something about the communication to our server that has changed. We don't get to update libraries and handle breaking changes.

We really hope you will return these older versions in your maven repository.

**Comment by turansky** [comment]
Unfortunately old versions (before `pre.213`) were published on [Bintray, which is unavailable :(](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
Sorry, but it doesn't look like any restoring is possible - not all dependencies of Kotlin Wrappers `pre.124` available on Maven Central :(
