### ISSUE TITLE
Router. Type parameter for `useLoaderData()`

### ISSUE THREAD

**Issue by leerenbo** [JetBrains/kotlin-wrappers#2452]
```kotlin

val ContactFC = FC {

    val contact: Contact = useLoaderData().asDynamic()

...
}
```

This is more concise.

```kotlin
val contact = useLoaderData<Contact>()
```

**Comment by turansky** [comment]
It's what we have in original definitions.
In your case cast to `Contact` expected.
```
val contact = useLoaderData() as Contact
```

Also you can create custom hook with additional check in your project:
```kotlin
inline fun <reified T : Any> useSafeLoaderData(): T {
    return useLoaderData() as T
}
```

**Comment by leerenbo** [comment]
Contact is a kotlin  class.  useLoaderData() looks like return a jso.  The "as" operation will cause an exception.

<img width="2007" alt="image" src="https://github.com/user-attachments/assets/df18c1de-8569-4405-a38c-ae4c06885225">

**Comment by turansky** [comment]
You have 2 options at least:
1. Declare `Contact` as JSO (`@JsPlainObject` will be helpful)
2. Use serialization for this loader data
  * It's better to serialize data in loader function to avoid redundant serialization on every hook call
  * Serialization from String and JSO supported by `kotlinx.serialization`

**Comment by leerenbo** [comment]
> * It's better to serialize data in loader function to avoid redundant serialization on every hook call

This suggestion is helpful.

I am going through document [https://reactrouter.com/en/main/start/tutorial](https://reactrouter.com/en/main/start/tutorial) and trying to rewrite the examples in Kotlin. 

The data is mock data from js wrapper. If it were a real HTTP request, this type of problem probably wouldn't occur.

**Comment by leerenbo** [comment]
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/75c16d83-b89d-4e8b-b8be-ff0d0ead8d1a">

I tried @JsPlainObject.  Gradle build well, but idea got a compile error.

```kotlin
plugins {
    kotlin("multiplatform")
    id("io.github.turansky.seskar") version "3.20.0"
    kotlin("plugin.serialization")
    kotlin("plugin.js-plain-objects")
//    id("io.github.turansky.kfc.application")
}
```

**Comment by turansky** [comment]
Option for IDEA: 
![image](https://github.com/user-attachments/assets/8ef12a12-7061-479d-bcf5-0d272c91e7f7)

and it's Alpha
