### ISSUE TITLE
Separate coroutines-enabled code

### ISSUE THREAD

**Issue by lppedd** [JetBrains/kotlin-wrappers#2478]
I've noticed that many modules, including the most basic `kotlin-js` one, add a dependency on coroutines.

https://github.com/JetBrains/kotlin-wrappers/blob/e2f670d37f75d03fe74415cc18674fa838464eb9/kotlin-js/build.gradle.kts#L6

I think it's surprising to see kotlinx-coroutines in a JS wrappers project, so I'd like to propose splitting the code.  
For example:

- `kotlin-js` - pure wrappers
- `kotlin-js-coroutines` - build on top of `kotlin-js` and adds coroutines support

The same concept could be applied to other modules.  
This could favor better dependency management from a consumer perspective, and encourage kotlinx libraries to adopt kotlin-wrappers types. For example, see [discussion](https://github.com/Kotlin/kotlinx-io/pull/386#discussion_r1746129658) in kotlinx-io PR.

---

[Related discussion](https://kotlinlang.slack.com/archives/C0B8L3U69/p1725613643489669)

**Comment by turansky** [comment]
1. Our current strategy is to enforce `suspend` calls over `Promise` calls.
2. Solution for `kotlinx-io` and similar libraries - exclude `coroutines` [from transitive dependencies](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps).
3. Additional changes from Kotlin Wrappers isn't expected.
