### ISSUE TITLE
Please reconsider the naming in `kotlin-wrappers-catalog` and the readme example

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#2497]
The readme example for the usage of `kotlin-wrappers-catalog` shows using `libs` as catalog name.
But most often this name is already occupied with the default version catalog in `gradle/libs.versions.toml`.
Only in projects where exclusively the Kotlin wrappers are coming from a catalog, this example and the naming applies.

Given that `libs` is already occupied, what would be a good naming for the catalog?

`kotlin`, so that you have `kotlin.wrappers.node`?
Yes, awesome, just that it conflicts with the `kotlin` extension already present on the project.
So it is not just confusing which is which where, but just does not compile.

`wrappers`?
Well, then we have `wrappers.wrappers.node` which seems a bit weird.

How about this suggestion:
- remove the `wrappers.` prefix in the catalog entries
- change the readme to use `kotlinWrappers` as catalog name, matching the project name

This way you end up with `kotlinWrappers.node` and so on which seems quite nice and fitting.
`kotlinWrappers.wrappers.node` again is somewhat strange.
Or `theKotlin.wrappers.node`.

Or do you have another nicely fitting idea that does not feel weird with the current aliases? :-)

**Comment by Vampire** [comment]
> In that case you probably will declare all versions in .toml file ;)

No, why should I?
You already provide all the coordinates and versions in the ready-made catalog.
It does not make much sense to redeclare them in another catalog.
That's one of the reasons you can register multiple version catalogs, so that you can consume version catalogs provided by other projects like this one.

> It works fine [in Gradle DSL](https://github.com/turansky/seskar/blob/master/settings.gradle.kts), where you can use multiple version catalogs in libs.

No, it does not.
You can never use multiple version catalogs in the same version catalog.
You can call `from` multiple times, but that will fail at runtime as only one is allowed.

What you do in the linked snippet is, that you use **one** version catalog and add some things programmatically.
But you cannot import multiple version catalogs.
And even if you only have the wrappers catalog and some own entries, you can do it in the DSL, but using the DSL has significant drawbacks when you could use a TOML catalog instead.

The only way to combine multiple catalogs into `libs` is to use the DSL, retrieve and parse the catalogs in your own code and combine them. But there is no support by Gradle to do so.

> Even if you have main catalog in toml - you can merge with additional catalogs via internal Gradle API

Not really as described. And even if it would be possible, using internal API is of course not a good idea. ;-)

**Comment by turansky** [comment]
As result - if we will have version catalogs for Kotlin libraries (coroutines, serialization) - it won't be possible to build "single company catalog", which will contains all versions and accessors.

It was't expected for me - I wanted "one ring".
Versions won't be declared in one place - it's sad :(

> This way you end up with `kotlinWrappers.node` and so on which seems quite nice and fitting.

With described limitations this variant looks like best.

**Comment by turansky** [comment]
@Leonya could you, please, release these changes?

**Comment by turansky** [comment]
> What about a CHANGELOG entry?

Ready ;)
