### ISSUE TITLE
`OutgoingHttpHeaders` quirks

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#2504]
I'm upgrading from 529 to 806.

`OutgoingHttpHeaders` used to be `typealias OutgoingHttpHeaders = Dict`, so it was used like
```kotlin
additionalHeaders = recordOf(
    "Content-Type" to "application/x-www-form-urlencoded",
    "User-Agent" to "Setup WSL GitHub Action"
)
```
Now it is a `sealed external interface OutgoingHttpHeaders : Dict` without `JsPlainObject` annotation.
So right now you have to do
```kotlin
additionalHeaders = jso {
    this["Content-Type"] = "application/x-www-form-urlencoded"
    this["User-Agent"] = "..."
}
```

Even if it would have `JsPlainObject`, it would not really help in my case as `user-agent` is only there as comment and `content-type` not even as comment.

So if I got it right I think:
- the class misses `JsPlainObject`
- the properties with dash need handling
- `content-type` needs to be added

**Comment by turansky** [comment]
@Leonya could you, please, release these changes?

**Comment by turansky** [comment]
> the class misses `JsPlainObject`

Kotlin `2.1.0` required before :(
