### ISSUE TITLE
`IncomingMessage.statusCode` breaking type change

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#2505]
I'm upgrading from 529 to 806.

`node.http.IncomingMessage.statusCode` used to be `Number?`.
Now it is `Double?`, which seems to be wrong to me.

I had `if (response.message.statusCode != 200)` which does not compile anymore.

I guess it should either be `Number?` or even `Int?`.

Or maybe even `HttpCodes?`
Which should probably be renamed to `HttpCode`.

Right now I try to do
`if (response.message.statusCode != HttpCodes.OK.unsafeCast<Double>()) {` as a replacement.
Would be nice if it in the end were just
`if (response.message.statusCode != HttpCodes.OK) {`.

**Comment by sgrishchenko** [comment]
Fixed by baae242ec8852e337e69cfebeed1e94c662284bb
