### ISSUE TITLE
`Process#exit` arguments type change

### ISSUE THREAD

**Issue by Vampire** [JetBrains/kotlin-wrappers#2506]
I'm upgrading from 529 to 806.

I used to call `process.exit(1)` (which I just learned is bad anyway, but that's not the point :-) )

Now `exit` expects a `Double` or `String`.

I guess it should be `Number` or `Int`, not `Double`.

**Comment by sgrishchenko** [comment]
Fixed by 176aa870ce865accc82898a5382d86cd4be439d5

**Comment by turansky** [comment]
@Leonya could you, please, release these changes?
