### ISSUE TITLE
Missing `js.intl.NumberFormatOptions` parameters

### ISSUE THREAD

**Issue by Bruno-me** [JetBrains/kotlin-wrappers#2559]
Commit [8ba2734](https://github.com/JetBrains/kotlin-wrappers/commit/8ba2734967d835c4fc6f388ddaab22c003d31c58) removed `var style: String?` from the definition of `external interface NumberFormatOptions`, making it impossible to use the `currency`, `percent`, and `unit` styles. The `currency`, `useGrouping`, and most of the digit options were removed as well.

`typealias NumberFormatOptionsStyle = String` was introduced in the same commit. It feels like this should be an enum with constants for decimal, currency, percent, and unit ([ecma402 15.4](https://tc39.es/ecma402/#sec-properties-of-intl-numberformat-instances)) and be used in `NumberFormatOptions`

**Comment by turansky** [comment]
Fixed in 410f569ad64e04e410a0951bdd928ea6366a29a2

**Comment by turansky** [comment]
Fix released in `pre.816`
