### ISSUE TITLE
Kotlin-wrapper-506 does not work redux (IR compiler)

### ISSUE THREAD

**Issue by bruimafia** [JetBrains/kotlin-wrappers#2569]
I updated the version of theKotlin-wrappeк from 505 to 506 and changed the legacy compiler to the ir compiler. I started getting an redux error in browser.
`Uncaught TypeError: state.get_userState_dy2db1_k$ is not a function`
My code:
```
data class State(
    val summaryState: SummaryState = SummaryState(),
)

fun <S, A, R> combineReducers(reducers: Map<KProperty1<S, R>, Reducer<*, A>>): Reducer<S, A> {
    return redux.combineReducers(reducers.mapKeys { it.key.name })
}

fun reducers() = combineReducers(
    mapOf(
        State::summaryState to ::summaryReducer,
    )
)

val store = createStore(
    reducers(), State(), compose(
        rThunk(),
        rEnhancer(),
        js("if(window.__REDUX_DEVTOOLS_EXTENSION__ )window.__REDUX_DEVTOOLS_EXTENSION__ ();else(function(f){return f;});") as Function1<Function2<Function2<State, Action, State>, State, Store<State, Action, Action>>, Function2<Function2<State, Action, State>, State, Store<State, Action, Action>>>
    )
)
```

```
fun summaryReducer(state: SummaryState = SummaryState(), action: RAction): SummaryState {
    return when (action) {
        is UpdateKeyspaceSchema -> {
            state.copy(
                schemaFrame = SchemaFrame(action.schema), model = Model(action.schema)
            )
        }
    }
}
```
![zet](https://github.com/user-attachments/assets/6b90a609-6e09-4817-9a47-b27598addfe8)

**Comment by turansky** [comment]
Root cause - state must be external interface (not data class)

**Comment by bruimafia** [comment]
Can you give examples, please? I don't really understand how to pass the interface object then (А можешь дать примеры, пожалуйста? Я не очень понимаю как тогда передавать объект интерфейса)

**Comment by turansky** [comment]
In latest Kotlin you can use `@JsPlainObject` [annotation](https://github.com/JetBrains/kotlin/tree/master/plugins/js-plain-objects).
Alternative - `jso` [factory function](https://github.com/JetBrains/kotlin-wrappers/blob/17b4a81e8ae4067ad5e5a4859ed1c0e87014056c/kotlin-js/src/jsMain/kotlin/js/objects/jso.kt#L10) - isn't recommended for described case.

JFYI - https://github.com/JetBrains/kotlin-wrappers/blob/master/CHANGELOG.md#pre786

**Comment by bruimafia** [comment]
I don't have the latest version of kotlin. I have now switched to version 506 only. I am raising library versions gradually and I cannot immediately install the latest one, as there are a lot of errors, and the project is very large. I would like such a solution to work on version 505 or the next. Will `@JsPlainObject` work on 506?

**Comment by turansky** [comment]
> Will @JsPlainObject work on 506?

User with `pre.506` can check ;)
