### ISSUE TITLE
Replaced with import kotlinx.browser.window

### ISSUE THREAD

**Issue by bruimafia** [JetBrains/kotlin-wrappers#2571]
If I understood correctly, then libraries `import org.w3c.dom.*` need to be replaced by` import web.*.*`. It is also necessary to replace `import kotlinx.browser.document` with `import web.dom.document`. I don't understand what needs to be replaced with import `kotlinx.browser.window`?  I have a type mismatch error in `stream`:
```
Type mismatch.
Required: web.media.streams.MediaStream
Found: org.w3c.dom.mediacapture.MediaStream
```

```
GlobalScope.launch {
            
            window.navigator.mediaDevices.getUserMedia(MediaStreamConstraints(video = false, audio = true))
                .then { stream ->
                    val context = AudioContext()
                    val analyser = context.createAnalyser()
                    val src = context.createMediaStreamSource(stream)
                    val mediaRecorder = MediaRecorder(stream)

                    src.connect(analyser)

                    mediaRecorder.ondataavailable = {
                        val track = it.asDynamic().data as Blob
                        val fileUrl =
                            URL.createObjectURL(track)    //todo воспроизведение аудио для тестов вместо отправки на сервер
                        Audio(fileUrl).play()
                        dispatch(SetStatus(StatusVoiceAssistant.WAIT_COMMAND))
//                        dispatch(sendTrackToServer(track)) todo отправка записи на сервер, раскоментировать, когда будет готов сервер

                    }

                    val historyVolume = mutableListOf(0)

                    dispatch(SetStatus(StatusVoiceAssistant.LISTENING))
                }
                .catch { error ->
                    console.error("$error")
                    dispatch(SetStatus(StatusVoiceAssistant.NOT_WORK))
                }
        }
```

**Comment by turansky** [comment]
> If I understood correctly, then libraries `import org.w3c.dom.*` need to be replaced by import `web.*.*`

Yes

> It is also necessary to replace import `kotlinx.browser.document` with import `web.dom.document.`

Yes

> I don't understand what needs to be replaced with import `kotlinx.browser.window`?

`web.window.window` is what you need

**Comment by bruimafia** [comment]
But there are no different methods in this library that I had. For example, `window.navigator `and `window.alert`

**Comment by bruimafia** [comment]
What confuses you, why did you set such a reaction?
One question more: `import kotlinx.browser.localStorage` What should I replace it with?

**Comment by turansky** [comment]
> One question more: import kotlinx.browser.localStorage What should I replace it with?`

Please use [API Reference](https://jetbrains.github.io/kotlin-wrappers/)

**Comment by turansky** [comment]
> What confuses you, why did you set such a reaction?

It must be fixed, but fix will be available only in new version :(

**Comment by bruimafia** [comment]
I am slowly carefully increasing the libraries :)

**Comment by turansky** [comment]
Recommendation for now - add following local function:
```kotlin
inline <T, R> fun R.magicCast(
    value: T,
): R  = 
    value.unsafeCast<R>()
```

and report all such cases (in 1 issue) after migration.
