### ISSUE TITLE
ChildrenBuilder Instead of RBuilder

### ISSUE THREAD

**Issue by bruimafia** [JetBrains/kotlin-wrappers#2573]
First question:
What to use instead `import org.w3c.dom.events.MouseEvent`?
`import react.dom.events.MouseEvent` or `import web.uievents.MouseEvent`

Second question:
What to use instead `RBuilder`? I understand correctly what is needed `ChildrenBuilder`? Is there a method in it `render() ` and `RHandler`?

**Comment by turansky** [comment]
@bruimafia It's highly recommended to join Kotlin Slack and [javascript](https://kotlinlang.slack.com/archives/C0B8L3U69) channel, where more people can answer questions like this.
