### ISSUE TITLE
Class component and ir compiler

### ISSUE THREAD

**Issue by dagistanSilaBrat** [JetBrains/kotlin-wrappers#2577]
Can I use class components and the ir compiler together ? 
as I understand it, override fun Builder.render() can no longer be used.

**Comment by turansky** [comment]
If you use `kotlin-react-legacy` - no changes expected

**Comment by dagistanSilaBrat** [comment]
Now I'm using kotlin react without legacy, how can I use class component?

**Comment by turansky** [comment]
As **temp** solution for migration you can use following:
```kotlin
class A : Component {
    override fun render() = Fragment.create {
        // your code
    }
}
```
