### ISSUE TITLE
Please add module filter to the API docs

### ISSUE THREAD

**Issue by reubenfirmin** [JetBrains/kotlin-wrappers#2584]
**Is your feature request related to a problem? Please describe.**

By default, the docs search should be module specific. 

For example, search "transform" in:

https://jetbrains.github.io/kotlin-wrappers/kotlin-css/kotlinx.css.properties/-transform/index.html

**Comment by turansky** [comment]
@reubenfirmin Please report [Dokka feature request](https://github.com/Kotlin/dokka/issues)
