### ISSUE TITLE
kotlin-css - please clarify animation docs

### ISSUE THREAD

**Issue by reubenfirmin** [JetBrains/kotlin-wrappers#2586]
This is a followup to : https://github.com/JetBrains/kotlin-wrappers/issues/2583 (which I can't reopen).

The docs look promising. However, how would this work in the context of a CssBuilder?

I have this adapter function for kotlinx-html:

```
fun CommonAttributeGroupFacade.css(block: CssBuilder.() -> Unit) {
    style = CssBuilder().apply {
        block()
    }.toString().removeSuffix("\n")
}
```

which lets me write dsl like this to get inline css:

```
    div("w-full") {
        css {
            height = 100.pct
            borderRadius = 10.px
            overflow = Overflow.hidden
            ...
```

(If I'm using this wrong, please let me know!)

The animation property is an Animations, so it appears to need a +=, i.e.:

```
            animation += Animation(
                name = "gradient",
                duration = 10.s,
                timing = Timing.linear,
                iterationCount = IterationCount.infinite
            )
```

...and I don't see a way to add keyframes as you described in the docs (https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-css/README.md). I also don't see the animation() extension function available in the Animation class as transform() is available in Transform.

**Comment by Leonya** [comment]
The animation extension function is defined in `kotlin-styled-next`, not in `kotlin-css`, because it needs to inject keyframes.

**Comment by reubenfirmin** [comment]
@Leonya Hm, but kotlin-styled-next pulls in a bunch of react dependencies (and other stuff). What if I am not working with react?

Can we turn this into a feature request for kotlin-css, then? I like that this library is so focused on one thing.

**Comment by reubenfirmin** [comment]
One other thought - you probably shouldn't say that kotlin-css supports css animations if keyframes aren't supported. Right?

**Comment by Leonya** [comment]
I think you should not be using `kotlin-css` at all. It's a legacy library meant to be used in conjunction with `kotlin-styled-next` and `kotlin-react-legacy`. What you need is `kotlin-emotion`.

**Comment by reubenfirmin** [comment]
@Leonya kotlin-emotion doesn't work in context with kotlin-html-js:

![2024-10-17_14-44](https://github.com/user-attachments/assets/ee1a749e-b074-4b7e-a544-f1c8f559f650)

kotlin-css is perfect for what I'm trying to do, because it can generate styles as a string, which can be plugged into the style attribute of kotlin-html tags.

**Comment by Leonya** [comment]
Unfortunately, we don't have a solution for generating full stylesheets without React.

**Comment by reubenfirmin** [comment]
@Leonya not asking for full stylesheets to be generated. Inline styles are fine (see this for example: https:// danielnagy. me/ posts/ Post_tsr8q6sx37pl) -- although I can definitely do the wiring to support class base output with kotlin-css too.

But how about full support for animations (this ticket)? I think the main thing missing is just keyframes. It's so close.

**Comment by Leonya** [comment]
But... keyframes don't work in inline styles.

**Comment by reubenfirmin** [comment]
@Leonya Interesting. Well, here's support for css classes which are hoisted into the head:

https://github.com/reubenfirmin/kdemo.cc/blob/main/src/jsMain/kotlin/org/example/framework/interop/Css.kt#L27

And, demonstrated here:
https://github.com/reubenfirmin/kdemo.cc/blob/main/src/jsMain/kotlin/org/example/pages/home/StyleCard.kt#L66

Very simple (which is why I really like this library).

So, how about support for keyframes now? :)
