### ISSUE TITLE
kotlin-css - are class name rules possible? 

### ISSUE THREAD

**Issue by reubenfirmin** [JetBrains/kotlin-wrappers#2587]
**Is your feature request related to a problem? Please describe.**

As mentioned in another ticket, I'm using a small adapter function to add inline styles to kotlinx-html:

```
fun CommonAttributeGroupFacade.css(block: CssBuilder.() -> Unit) {
    style = CssBuilder().apply {
        block()
    }.toString().removeSuffix("\n")
}
```

I can see that element name based rules are doable (although this would produce incorrect css in my context, since I'm adding them inline -- but that's fine):

```
css() {
                        body {

                        }
                    }
```

...but how do I add style rules based on classnames? 

Please add to the documentation, and/or turn this into a feature request.

**Comment by Leonya** [comment]
It's not a feature of `kotlin-css`, no. You need to use `kotlin-styled-next` for that.
