### ISSUE TITLE
kotlin-emotion - please add basic example in README

### ISSUE THREAD

**Issue by reubenfirmin** [JetBrains/kotlin-wrappers#2589]
**Is your feature request related to a problem? Please describe.**

I was recommended to use kotlin-emotion rather than kotlin-css in another ticket. Please if possible provide a basic example in README. (Since I'm using this in conjunction with kotlinx-html, I would ideally need it to be able to output a string so I can attach to the style property).

I'm assuming https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-emotion/src/jsMain/kotlin/emotion/css/css.kt is the entrypoint corresponding to https://emotion.sh/docs/introduction, but I don't see how it's meant to be used in kotlin.

**Comment by turansky** [comment]
https://github.com/JetBrains/kotlin-wrappers/blob/master/docs/guide/emotion.md
