### ISSUE TITLE
HTML Input: how assign the autoComplete attribute?

### ISSUE THREAD

**Issue by edpichler** [JetBrains/kotlin-wrappers#2655]
After upgrading `kotlinWrappersVersion` `1.0.0-pre.840 ` to `1.0.0-pre.840` I am not understanding how to use the autocomplete attribute of the HTML input anymore.

![image](https://github.com/user-attachments/assets/c4a73018-53e8-43f5-b010-a9ef39b2e9e7)

I just want to let the browser autocomplete. How to make the browser understand which field must be used for the autocomplete now? 

Is there any documentation on how to use it?

Thanks.

**Comment by edpichler** [comment]
I found way to set `tel`.
![image](https://github.com/user-attachments/assets/424fdc3b-c2b5-4208-a69c-d8fd3d7405e8)


How to do the same for name, street name, and other fields?

**Comment by edpichler** [comment]
Excellent. Thanks.

@turansky and for telephone? `AutoFillNormalField.tel` does not exist.

![image](https://github.com/user-attachments/assets/02290424-d83e-462d-b049-bacf9915e03e)

**Comment by turansky** [comment]
`AutoFillContactField.tel`?

**Comment by edpichler** [comment]
Ops, I need more coffee here...

Thanks!
