### ISSUE TITLE
Code with kotlin-react-dom doesn't compile without kotlinx-html

### ISSUE THREAD

**Issue by ilgonmic** [JetBrains/kotlin-wrappers#268]
Now `react-dom` doesn't have transitive dependency on `kotlinx-html`
Now if I use `kotlin-react-dom`, I must use `kotlinx-html`
Otherwise I get compilation error, because `kotlin-react-dom` uses `kotlinx-html` in API 
For example this - https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMTags.kt#L49

Sample - https://github.com/ilgonmic/full-js-wizard/tree/react-hooks
And I get compilation error for button - https://github.com/ilgonmic/full-js-wizard/blob/react-hooks/src/main/kotlin/org/example/Ticker.kt#L34

Is it expected?

**Comment by Skolotsky** [comment]
Looks like it because of that https://github.com/JetBrains/kotlin-wrappers/pull/265

**Comment by ilgonmic** [comment]
It is not because this particular one.
It is because changing `compile` configuration on `implementation` configuration for `kotlinx-html`. And #265 preserve configuration `implementation`, so it is ok.
But because `kotlinx-html` is used in public api of `kotlin-react-dom`, `api` configuration should be used instead of `implementation`
Same can affect `kotlin-styled`

**Comment by turansky** [comment]
@Skolotsky 
No configuration changes in #265
Before - `implementation`
After - `implementation`

**Comment by Skolotsky** [comment]
I wasn't very attentive. So i was wrong about it.

**Comment by Leonya** [comment]
@turansky it's about one of your earlier changes. There are no more transitive dependencies, and it's not so clear whether it's a good thing or not.

**Comment by turansky** [comment]
> But because `kotlinx-html` is used in public api of `kotlin-react-dom`, api configuration should be used instead of implementation

At the same time:
1. `kotlin-react-dom` use `kotlin-react`
2. `kotlin-react-dom` api use declarations from `kotlin-react` (`ReactElement` for example)
3. `react` [is peer dependency](https://github.com/facebook/react/blob/master/packages/react-dom/package.json#L25) of `react-dom` in NPM

> There are no more transitive dependencies, and it's not so clear whether it's a good thing or not.

Current dependency scheme
1. Synchronous for both Gradle & NPM (`implementation` ~= `peer`)
2. Safer
2.1. No possibility forget dependency declaration => **final app dependency versions will be used** (important for bug fix updates - `kotlinx-html` for example)

**Comment by ilgonmic** [comment]
> Is kotlin-react api dependency of kotlin-react-dom?

In fact it can be, yes. In npm it is done to prevent multiple react runtimes.
Even more, if you make these dependency, you make safer, because there is no possibility to mix versions of `kotlin-react` and`kotlin-react-dom`. But it can be discussed separately because it is npm world, which completely different with Gradle one.
At least there is actual reason, why it is as is. Because original `react` and `react-dom` force user
 to declare both `kotlin` and `kotlin-react`.

> Synchronous for both Gradle & NPM (`implementation` ~= `peer`)

There is no strict mapping here. It is really different things, and it is not called synchronous. It is synchronous only for modules which fully related with npm stuff (`react`, `react-dom` etc) because it is their rules.
But `kotlinx-html` is not basic npm dependency, it is just Gradle dependency, which should be applied with Gradle rules. And rule is "used in API = `api` configuration".
Otherwise you have valid code which does not compile.

> No possibility forget dependency declaration => final app dependency versions will be used (important for bug fix updates - kotlinx-html or kotlin-extensions for example)

I am afraid, that this kind of dependency management leads to manual management of dependencies. Because it leads to term where you need to know full dependency tree of your project and manually manage versions of it.
And even more, if you don't explicitly use API from `kotlinx-html` you can miss necessity of this dependency and somebody can remove it because redundant. And build will be broken. So build will be kind of secret magic.

> Easy to support

IMO it shouldn't be done at the cost of correctness, which I consider Gradle rules.

Common rules is good, but now we have in my opinion important problem, that code with only call to `button` (without explicit declaration from `kotlinx-html`) doesn't compiled. And users may not have red code, but have uncompiled code.
Other modules can be discussed (especially `kotlin-react` - `kotlin-react-dom`), but I see that particular `kotlinx-html` has incorrect configuration right now, and leads to real problems. And it should be fixed asap.

**Comment by turansky** [comment]
> And rule is "used in API = api configuration".

> Other modules can be discussed (especially kotlin-react - kotlin-react-dom)

Rule or rule with "can be discussed"?

**Comment by ilgonmic** [comment]
It is common rule, and it is good point to starts with. And in fact, exceptions from this rule should be argued. Better to argue it before changes, not after, when some things are broken already :)
And by common rule it is ok to depends react-dom to react with api. Until there is no npm dependencies inside these modules, it even doesn’t broke npm dependencies with their peer dependencies.

But now we already have situation with implementation everywhere. So we have several ways
We can revert change of configuration to api everywhere, and change it to implementation only when it will be argued

Or more flexible imo way: we can fix point by point places, where it is incorrect without additional argumentation.
