### ISSUE TITLE
Add Vue.js wrapper (kotlin-vue)

### ISSUE THREAD

**Issue by cyparu** [JetBrains/kotlin-wrappers#27]
With [Vue.js](https://vuejs.org/) more & more popular, adding some **Kotlin** _spices_ to it should provide a very powerful combo 🚀. 

Some wrappers exists already (ex: https://github.com/gbaldeck/vue.kt) but having it properly & idiomatically supported by Jetbrains (as with **ReactJS->kotlin-react**) is IMO the way to go.

Since Vue.js v2.5 comes with great **TypeScript** support [[link-1]](https://medium.com/the-vue-point/vue-2-5-released-14bd65bf030b) [[link-2]](https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08) , some insights from its [type definitions](https://github.com/vuejs/vue/blob/dev/types/vue.d.ts) might be useful as well.

**Comment by Leonya** [comment]
Do the existing wrappers have known shortcomings? We provide kotlin-react because we use it extensively ourselves, unlike Vue. It's probably better to have wrappers developed by someone who actually uses them ;)

**Comment by cyparu** [comment]
IMO the few existing Vue.js wrappers address just syntax issues (the mentioned one being the more actual/advanced) and are just sort of starters/experiments and doesn't have the _feel_  of both idiomatic Kotlin & Vue.js.  Additionally, a proper wrapper should IMO also have full Kotlin support into SFC **.vue** based components (similar to TypeScript) and who can better provide all of these than the Kotlin/JS creators ?

So with more and more Angular & React developers migrating to Vue.js maybe is time for JetBrains to test the water 🏊 as well ;)

**Comment by cyparu** [comment]
In [Developing Multiplatform Projects in Kotlin 1.2 - Webinar](https://blog.jetbrains.com/kotlin/2017/12/webinar-recording-developing-multiplatform-projects-in-kotlin-1-2/) @yole mentioned that JetBrains is developing a Kotlin alternative to the TypeScript based [DefinitelyTyped](http://definitelytyped.org/) thus addressing generic TypeScript -> Kotlin conversion using [ts2kt](https://www.kotlinresources.com/library/ts2kt/). 
Anyhow, while this will solve the static typing & language syntax part, it may not solve Vue.js specifics (ex: SFC/.vue support).

**Comment by galex** [comment]
@cyparu Any updates since then? This is IMHO what could give Kotlin JS the big boost it needs!

**Comment by cyparu** [comment]
> @cyparu Any updates since then? This is IMHO what could give Kotlin JS the big boost it needs!

I'm also interested a lot into **Kotlin/Everywhere** (JVM, JavaScript = Node/Browsers/WebAssembly, Native=LLVM, IoT/ARMx ... even CLR/.NET if possible) ... but I see no real progress in JavaScript arena for sometime :( ... It look like JetBrains is currently focused on other (otherwise important as well) directions (coroutines, multi-plat, native ...) .

**Comment by SorenV** [comment]
https://github.com/SorenV/kotlin-vue
