### ISSUE TITLE
"Invalid hook call" occurred when add kotlin-styled to dependencies

### ISSUE THREAD

**Issue by yt8492** [JetBrains/kotlin-wrappers#275]
I wrote functional component using hooks like this 

```kotlin
val component = functionalComponent<RProps> {
    val (inputText, setText) = useState("")
    textArea {
        attrs.onChangeFunction = {
            val target = it.target as HTMLTextAreaElement
            setText.invoke(target.value)
        }
    }
    div {
        + inputText
    }
}
```

This code works, but when I add `kotlin-styled` dependency, this code crashed.

Here is a sample code. You can check by comment-out `kotlin-styled` dependency and running `./gradlew browserRun`.
https://github.com/yt8492/kotlin-react-hooks-sample

**Comment by pillimoj** [comment]
Please see #147 
It should be fixed by installing a versio of styled components lower than 5. e.g. `implementation(npm("styled-components", "4.4.0"))`

**Comment by yt8492** [comment]
I see. Thank you!

**Comment by yt8492** [comment]
1 more thing. That solution works at `org.jetbrains:kotlin-styled:1.0.0-pre.102-kotlin-1.3.72`, but version `1.0.0-pre.103-kotlin-1.3.72`, still occurred "Invalid hook call". I think this is another problem.

**Comment by Leonya** [comment]
@turansky will you take a look please?

**Comment by turansky** [comment]
Yes, I will.

**Comment by turansky** [comment]
Dependency sync (`pre.103` for all) resolve the problem:
```
dependencies {
    implementation(kotlin("stdlib-js"))
    implementation("org.jetbrains:kotlin-react:16.13.0-pre.103-kotlin-1.3.72")
    implementation("org.jetbrains:kotlin-react-dom:16.13.0-pre.103-kotlin-1.3.72")
    implementation("org.jetbrains:kotlin-styled:1.0.0-pre.103-kotlin-1.3.72")
}
```

No more dependencies required for example. Compatible NPM dependencies already declared for wrappers.

**Comment by yt8492** [comment]
@turansky Thank you. Your solution works on my first code, but when I use styled-component, "Uncaught Error" the same as #147 occurred.

```kotlin
val component = functionalComponent<RProps> {
    val (inputText, setText) = useState("")
    styledTextArea {
        css {
            borderWidth = 3.px
        }
        attrs.onChangeFunction = {
            val target = it.target as HTMLTextAreaElement
            setText.invoke(target.value)
        }
    }
    div {
        + inputText
    }
}
```
<img width="567" alt="スクリーンショット 2020-04-30 22 09 43" src="https://user-images.githubusercontent.com/39693306/80714056-58565c80-8b2f-11ea-8804-e5c2b298d747.png">

https://github.com/yt8492/kotlin-react-hooks-sample

Should I open another issue or reopen #147 ?

**Comment by yt8492** [comment]
According to #147 , the problem caused by using a newer version of styled-components (newer than 5.x), but kotlin-styled uses version 5.0.1 so I think this code cause this error.
https://github.com/JetBrains/kotlin-wrappers/blob/b04657e7d43348865e209eeca84479e48750fcae/kotlin-styled/build.gradle.kts#L16

**Comment by turansky** [comment]
> Should I open another issue or reopen #147 ?
No open/reopen required

**Comment by turansky** [comment]
@yt8492 Has this problem resolved for you in `pre.104`?

**Comment by yt8492** [comment]
@turansky I confirmed this problem resolved. Thank you!

**Comment by turansky** [comment]
You can close ticket as author
