### ISSUE TITLE
Kotlin-React-Redux is lacking Documentation

### ISSUE THREAD

**Issue by bjoernmayer** [JetBrains/kotlin-wrappers#277]
I think you should explain `rConnect` in detail instead of just providing a very cryptic example.

I never worked with JS react/redux, but I somehow understand what the function *should* do. Still the example confuses me, and after one day of playing around with it, I still do not understand what the example tries to explain.

At least explain the purpose of all the types. That's what I understood of it:

```
// S State
// OP Ownprops, properties of the resulting HOC
// P Properties of the connected component
// A ActionType
// SP Type of mapStateToProps Context
// DP Type of mapDispatchToProps Context
// R ?!?!? 
```

**Comment by sgrishchenko** [comment]
duplicated by #53
