### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by abelkov** [JetBrains/kotlin-wrappers#279]
Feedback from user:

We would like to use Kotlin/React for our new project, but unfortunately our company does not allow access to the https://kotlin.bintray.com/kotlin-js-wrappers/ repository as noted in your tutorial. We already spoke to the team managing our internal repository, and this will not happen.

Do you have any plans to upload the artifacts to Maven central in the near future? Otherwise we will have to choose something else for our UI development.

**Comment by Leonya** [comment]
I have submitted the request to publish to JCenter which is a prerequisite for publishing to Maven Central, hope it will be approved soon.

**Comment by vlsi** [comment]
The issue is still relevant since jcenter would [sunset soon](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by Leonya** [comment]
The artifacts are now being published (as of pre.149) to a JetBrains Space installation at kotlin.jetbrains.space, see coordinates in corresponding README files.

**Comment by vlsi** [comment]
@Leonya , unfortunately, when users add new repositories, the build system starts looking up all the artifacts there which might create security issues and cause build slowness (it takes time to probe a repository for an artifact).

Would you please suggest the repository [content filtering block](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) configuration?

**Comment by Leonya** [comment]
I guess you could filter by `org.jetbrains` but that's gonna match lots of artifacts as well.
