### ISSUE TITLE
I can not create animation

### ISSUE THREAD

**Issue by fordogtrainers** [JetBrains/kotlin-wrappers#288]
### Gradle:
```
 implementation("org.jetbrains:kotlin-styled:1.0.0-pre.94-kotlin-1.3.70")
 implementation(npm("styled-components"))
 implementation(npm("inline-style-prefixer"))
```
### Code:
```
css{
       animation {
              rules.addAll(listOf(
                        0.invoke {
                            top = 0.px
                        },
                        100.invoke {
                            top = 50.px
                        }
              ))
       }
}
```
### Error:
>  It seems you are interpolating a keyframe declaration (bmaQuw) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper which ensures the styles are injected correctly

**Comment by Leonya** [comment]
The correct syntax is

```
