### ISSUE TITLE
kotlin-react-dom: class attribute should not always be renamed to classname

### ISSUE THREAD

**Issue by KotlinStack** [JetBrains/kotlin-wrappers#29]
The `fixAttributeName` function replaces the `class` attribute name by `classname`. This correct for most use cases.

However, there are scenarios, when really the `class` attribute is needed, e.g. when using web components. See https://reactjs.org/docs/dom-elements.html

> **className**
> To specify a CSS class, use the `className` attribute. This applies to all regular DOM and SVG elements like `<div>`, `<a>`, and others.
> If you use React with Web Components (which is uncommon), use the `class` attribute instead.

Can you provide some option to access the `class` property?

**Comment by Hypnosphi** [comment]
Oh I see. I think we should make `attrs[key] = value` assign attribute directly, without processing

**Comment by kocheick** [comment]
Why this isn't working anymore ? Using kotlin-react-wrapper v18
