### ISSUE TITLE
fontFace only renders once

### ISSUE THREAD

**Issue by IARI** [JetBrains/kotlin-wrappers#292]
/commonMain/kotlinx/css/CSSBuilder.kt contains these:
```kotlin
// https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule
fun media(query: String, block: RuleSet) = "@media $query"(block)
fun supports(query: String, block: RuleSet) = "@supports $query"(block)
fun fontFace(query: String, block: RuleSet) = "@font-face $query"(block)
```
All of them in css are typically provided multiple times within the same context.
StringBuilder.buildRules however only creates a single CSSBuilder per 'selector'.
I guess with media and supports that works, because there's the 'query' parameter, which makes it a different selector.

Looking at the [css spec](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-face-rule), we find the `@font-face` grammar rule:

> font_face_rule
>   : FONT_FACE_SYM S* '{' S* descriptor_declaration? [ ';' S* descriptor_declaration? ]* '}' S*
>   ;
> 

So for `@font-face` there is no query parameter allowed (the `S*` is just whitespace)
there should not be a `query` parameter in the api.

That aside, in its current state it seems to be unusable for the commmon use case of defining multiple fonts within se same root block.

If you want to define two @fontFace bodys, they all end up in the same body and values are just overwritten. @turansky this looks like a bug to me.

**Comment by Leonya** [comment]
Yes, you're right. I'm not sure how to fix this.

**Comment by IARI** [comment]
I can make a PR - you can look at it, and see if you see a problem with it.

**Comment by Leonya** [comment]
Cool! Could you please write a test for it? `kotlin-css` has some.

**Comment by IARI** [comment]
I fixed some stuff and added a test as requested - please have a look at it :)
