### ISSUE TITLE
css animation in production mode

### ISSUE THREAD

**Issue by IARI** [JetBrains/kotlin-wrappers#295]
Using kotlin-styled, I am trying to get a simple css rotation animation to work within a react component.
So in my code i have this:
```kotlin
animation(1.s, Timing.linear, iterationCount = IterationCount.infinite) {
                                    from {
                                        transform {
                                            rotate(0.deg)
                                        }
                                    }
                                    to {
                                        transform {
                                            rotate(360.deg)
                                        }
                                    }
                                }
```
It works on the dev server. However, when i open the production build, I get a runtime error:

> Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#12 for more information. Additional arguments: gbLFjP

where that link states:

> It seems you are interpolating a keyframe declaration (%s) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css`` helper which ensures the styles are injected correctly. See https://www.styled-components.com/docs/api#css

**Comment by Leonya** [comment]
Can't reproduce. Are you using the latest version of `kotlin-styled`?

**Comment by andb3** [comment]
Hi, I'm having this same bug using `org.jetbrains:kotlin-styled:1.0.0-pre.110-kotlin-1.3.72`: animations work on dev server but throw the error in production. Sample code from where the error is thrown: 
```kotlin
fun CSSBuilder.shimmer(){
    background = "linear-gradient(to right, #eff1f3 4%, #e2e2e2 25%, #eff1f3 36%);"
    backgroundSize = "1000px, 100%"
    animation(duration = 2.s, iterationCount = IterationCount.infinite){
        0 { backgroundPosition = "-1000px 0" }
        100 { backgroundPosition = "1000px 0"}
    }
}
```

**Comment by Leonya** [comment]
Make sure you use styled-components 4.4.1, not 5.x
