### ISSUE TITLE
kotlin-react forwardref

### ISSUE THREAD

**Issue by IARI** [JetBrains/kotlin-wrappers#297]
Looking at forwardref:

```kotlin
fun <P : RProps> forwardRef(handler: RBuilder.(RProps, RRef) -> Unit): RClass<P> =
    rawForwardRef { props, ref ->
        buildElements { handler(props, ref) }
    }
```
How can this be used, in particular, with a functional component - is there any code example?
Why is the first handler parameter of type `RProps` and not of `P` - is that intentional?

**Comment by Skolotsky** [comment]
Looks like mistake. There should be P.

**Comment by IARI** [comment]
I'm not an expert, but I think so too.
I can offer to make a PR.

**Comment by Leonya** [comment]
Thanks, fixed!
