### ISSUE TITLE
Support contexts

### ISSUE THREAD

**Issue by Leonya** [JetBrains/kotlin-wrappers#3]
https://reactjs.org/docs/context.html

**Comment by Hypnosphi** [comment]
Not really sure we should do it here, at least before context API becomes stable

**Comment by chadmorrow-fd** [comment]
A new Context API is currently being worked on and (if I'm understanding right) should bring stability to this feature once finished. Details on this can be found at the [official proposal](https://github.com/reactjs/rfcs/pull/2) and in the [corresponding pull request](https://github.com/facebook/react/pull/11818).

This new API for Context has been merged and is set behind a feature flag at the moment.

**Comment by chadmorrow** [comment]
A new Context API is currently being worked on and (if I'm understanding right) should bring stability to this feature once finished. Details on this can be found at the [official proposal](https://github.com/reactjs/rfcs/pull/2) and in the [corresponding pull request](https://github.com/facebook/react/pull/11818).

This new API for Context has been merged and is set behind a feature flag at the moment.

**Comment by neworld** [comment]
The new Context API was released with [16.3.0 version](https://github.com/facebook/react/releases/tag/v16.3.0).

**Comment by chadmorrow** [comment]
There's an open pull request to add Typescript definitions for this API on Definitely Typed waiting to be merged; this is what it looks like: 
```
import * as React from "react";

declare module "react" {
  type Provider<T> = React.ComponentType<{
    value: T;
    children?: ReactNode;
  }>;
  type Consumer<T> = ComponentType<{
    children: (value: T) => ReactNode;
    unstable_observedBits?: number;
  }>;
  interface Context<T> {
    Provider: Provider<T>;
    Consumer: Consumer<T>;
  }
  function createContext<T>(defaultValue: T, calculateChangedBits?: (prev: T, next: T) => number): Context<T>;
}
```

but when I run that through ts2kt the output isn't usable because it leaves the Provider and Consumer undefined. Here's the output I get:
```
@file:Suppress("INTERFACE_WITH_SUPERCLASS", "OVERRIDING_FINAL_MEMBER", "RETURN_TYPE_MISMATCH_ON_OVERRIDE", "CONFLICTING_OVERLOADS", "EXTERNAL_DELEGATION", "NESTED_CLASS_IN_EXTERNAL_INTERFACE")
@file:JsModule("react")
package react

import kotlin.js.*
import kotlin.js.Json
import org.khronos.webgl.*
import org.w3c.dom.*
import org.w3c.dom.events.*
import org.w3c.dom.parsing.*
import org.w3c.dom.svg.*
import org.w3c.dom.url.*
import org.w3c.fetch.*
import org.w3c.files.*
import org.w3c.notifications.*
import org.w3c.performance.*
import org.w3c.workers.*
import org.w3c.xhr.*

external interface Context<T> {
    var Provider: Provider<T>
    var Consumer: Consumer<T>
}
external fun <T> createContext(defaultValue: T, calculateChangedBits: ((prev: T, next: T) -> Number)? = definedExternally /* null */): Context<T> = definedExternally

```

I've spent some time trying to torture this into compiling but haven't been successful. I don't have much experience doing this type of thing though.

**Comment by Leonya** [comment]
Context API is supported as of 16.3.1-pre.26: https://github.com/JetBrains/kotlin-wrappers/commit/77098726039acf2e95b9b97e8bd998f3049b78c9, enjoy!

**Comment by chadmorrow-fd** [comment]
Woohoo! Thanks so much!
