### ISSUE TITLE
Not upgrade to Kotlin-M1? 

### ISSUE THREAD

**Issue by cpdyj** [JetBrains/kotlin-wrappers#308]
Are there any plan for it? Thank you

**Comment by Leonya** [comment]
There are builds for both M1 and M2 on bintray.

**Comment by cpdyj** [comment]
I preferred we can add a notice for repository `kotlin-dev`. I didn't
know this repository. It makes me waste tons of time...

Thank you for your reply

在 2020/6/3 18:15, Leonid Khachaturov 写道:
