### ISSUE TITLE
Cant create redux store

### ISSUE THREAD

**Issue by wi4er** [JetBrains/kotlin-wrappers#312]
build.gradle
```
plugins {
    id 'org.jetbrains.kotlin.js' version '1.3.72'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    maven { url "https://kotlin.bintray.com/kotlin-js-wrappers/" }
    mavenCentral()
    jcenter()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-js"
    implementation(npm("redux"))

    implementation 'org.jetbrains:kotlin-redux:4.0.0-pre.109-kotlin-1.3.72'
}

kotlin.target.browser { }
```

main.kt
```
package main.kotlin

import redux.Action
import redux.createStore

data class Increase(override val type: String = "INCREASE") : Action
data class Decrease(override val type: String = "DECREASE") : Action

fun reducer(state: Int, action: Action): Int {
    return when(action) {
        is Increase -> state + 1
        is Decrease -> state - 1
        else -> state
    }
}

fun main() { createStore(::reducer, 10) }
```

Getting this error when trying to build

```
/mnt/Projects/Kotlin-react/app/src/main/kotlin/main.kt: (17, 14): When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule
```

Gradle 6.1
JVM:          11.0.7 (Ubuntu 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OS:           Linux 5.3.0-59-generic amd64

**Comment by AKJAW** [comment]
I had the same problem and wanted to create an issue, but you beat me to it. Every external function in the [Imports](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-redux/src/main/kotlin/redux/Imports.kt) file will case this error. 

The workaround that worked for me was creating my own imports:
```js
@file:JsModule("redux")
@file:JsNonModule

package mypackage

external fun <S, A, R> createStore(
    reducer: Reducer<S, A>,
    preloadedState: S,
    enhancer: Enhancer<S, Action, Action, A, R>
): Store<S, A, R>
```
This leads me to believe that adding the **@file:JsNonModule** in the Imports file would fix this issue. But i'm not sure if this would cause problems with backwards compatibility.

**Comment by turansky** [comment]
Fixed [here](https://github.com/JetBrains/kotlin-wrappers/commit/380278c651505bc9ef5be94358deff3d7ce44f78#diff-25db8b92a99f43af802c8be715c765d1a3147a427edd95f6bfaee284784f7d80)

cc @Leonya
