### ISSUE TITLE
useRef

### ISSUE THREAD

**Issue by abond** [JetBrains/kotlin-wrappers#315]
Hi!

When I try to create ref by calling `useRef()` I get error message:

When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule.

**Comment by nunocastromartins** [comment]
Getting the same error when using `createRef`.

```
> Task :some-project:compileKotlinJs FAILED
e: /path-to-project/src/jsMain/kotlin/SomeFile.kt: (1, 1): When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule
```

- Kotlin version `1.4.10`.
- Kotlin React and React-DOM versions `16.13.1-pre.110-kotlin-1.4.10`.

**Comment by nunocastromartins** [comment]
Just noticed that this is probably fixed in `master` with the usage of `@file:JsNonModule`.

Is there any released version with the fix? If not, when can we expect a new version?

Thank you!

**Comment by nunocastromartins** [comment]
A bit of a hackeroo until the next version is released:
```kotlin
@Suppress("UNCHECKED_CAST_TO_EXTERNAL_INTERFACE")
private val inputRef = js("require('react').createRef()") as RReadableRef<HTMLInputElement>
```

**Comment by Leonya** [comment]
Please update to `pre.122`
