### ISSUE TITLE
How to use Mocha?

### ISSUE THREAD

**Issue by eugenio1590** [JetBrains/kotlin-wrappers#316]
I am trying to use mocha for testing but I am not sure how to write the tests. Of course, the Mocha syntax is very clear, this is the following example:

````
describe("test match", function(){
  it("4 = 2 * 2") {
    // 4 == 2*1
  }
}) 
````

But when I translate this to a Kotlin class, I need to add a @Test annotation and return the 'describe' value in a function, something like that:

````
class UnitTest {
    @Test
    fun test1() = describe(description = "test match") {
        it(description = "4 = 2 * 2") {
            assertEquals(4, 2*1)
        }
    }
}
````

I think It is not a good idea to do this. But I do not find any documentation about that.

**Comment by turansky** [comment]
No Mocha declarations anymore

cc @Leonya

**Comment by eugenio1590** [comment]
I am using [Kotest.io](https://kotest.io/) for testing. There is not support for mocks yet but it worked for tests.
