### ISSUE TITLE
Can't create keyframe animations: 1.0.0-pre.105-kotlin-1.3.72

### ISSUE THREAD

**Issue by andylamax** [JetBrains/kotlin-wrappers#321]
using: org.jetbrains:kotlin-styled:1.0.0-pre.105-kotlin-1.3.72
As stated in the heading, when I run my code 
```kotlin
css {
        position = Position.relative
        animation(duration = 0.5.s) {
            0 {
                top = 50.vh
            }

            100 {
                top = 0.vh
            }
        }
}
```

My package.json resolves to use `"styled-components": "^5.1.0",` and when I run my code I get
```
Uncaught Error: It seems you are interpolating a keyframe declaration (lbMCNJ) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper which ensures the styles are injected correctly
```

I have browsed to see some people are able to do this in development but still troubles them in production environment. What am I doing wrong?I can't get it to work even in a dev environment

**Comment by turansky** [comment]
Current supported version - [`4.4.1`](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-styled/build.gradle.kts#L16).
Please use latest stable version for check

**Comment by andylamax** [comment]
Thank you so much. using 4.4.1 works
