### ISSUE TITLE
Wrapper for Enzyme for unit testing React components

### ISSUE THREAD

**Issue by epabst** [JetBrains/kotlin-wrappers#325]

**Comment by epabst** [comment]
I have generated and adjusted bindings for Enzyme here: https://github.com/epabst/kotlin-showcase/tree/5d5129e556c8b168b0a0b838eec694664af37902/src/jsTest/kotlin/enzyme.

Here is a sample test: https://github.com/epabst/kotlin-showcase/blob/5d5129e556c8b168b0a0b838eec694664af37902/src/jsTest/kotlin/todo/ToDoScreenTest.kt.

**Comment by Leonya** [comment]
https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl
