### ISSUE TITLE
ClassCastException on ReactElement props - Best practice alternative?

### ISSUE THREAD

**Issue by Lezzio** [JetBrains/kotlin-wrappers#326]
I'd like to read the props given to a child without having to actually store them elsewhere when I need to iterate them in the parent at some point :

Child.kt
interface MyProps: RProps {
    var value: String
}
val myElement = functionalComponent<MyProps> { ... }

Parent.kt (in a RElementBuilder)
val element = child(myElement) { 
 attrs.value = "My value"
} 
val props = element.props as MyProps //Causes the ClassCastException

Otherwise is there a way to detect the component type of a children in the childList ?

Thanks for your insight in advance,

**Comment by sgrishchenko** [comment]
1) `MyProps` should be external 
1) use `buildElements` or `createElement` instead of `child` to create element
1) use `unsafeCast` instead of `as MyProps`
