### ISSUE TITLE
backgroundImage Broken?

### ISSUE THREAD

**Issue by winthrop-polk** [JetBrains/kotlin-wrappers#337]
```
`backgroundImage = Image("//localhost:8080/img/team1.jpg")`
or
backgroundImage = Image("http://www.birds.com/wp-content/uploads/home/bird4.jpg") 
```

Is this correct? The link does show the image, but the site doesn't appear to download the image unless it is included as kotlinx html src value. Tried every conceivable variation.

This works fine though in kotlin JS w/ kotlinx-html
```
                        img(classes = "badge-avatar") {
                            src = "img/team1.jpg"
                        }
```

**Comment by Leonya** [comment]
You forgot the `url()` part. Should be backgroundImage = Image("url(//localhost:8080/img/team1.jpg)")
