### ISSUE TITLE
Working with checkboxes always produces warning in console

### ISSUE THREAD

**Issue by ogalimov** [JetBrains/kotlin-wrappers#35]
To reproduce the problem add something like this in a kotlin-react app. The state needs to have a var myBoolean, that has an initial value of false:
```
input(InputType.checkBox) {
  attrs.onChangeFunction = { event ->
    val newValue = (event.target as HTMLInputElement).checked
    setState { myBoolean=newValue }
  }
  attrs.checked = state.myBoolean
}
```
Then open the app in the browser and click on the checkbox. The following warning will appear in the console of the browser:
"A component is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component."

I have investigated the issue myself and I suspect that the problem is due to the setter of the checked property of the input removing the checked attribute when the value is false.

**Comment by Hypnosphi** [comment]
> input removing the checked attribute when the value is false.

Yeah, that‘s coming from kotlinx.html. We need to find a way to override this behaviour

**Comment by TorRanfelt** [comment]
Is any work being done on this? We have a lot of checkboxes, and it undermines the warnings.

**Comment by Hypnosphi** [comment]
Currently not, so you're free to give it a try

**Comment by TorRanfelt** [comment]
@Hypnosphi Sadly, as three developers in a startup we don't have resources for that kind of thing.

**Comment by forando** [comment]
As a temporary workaround I'm using this solution inside my functional component:
```
val checkboxEl = useRef(Any().unsafeCast<INPUT>())

useEffect( listOf() ) {
        checkboxEl.current.checked = it.enabled
}

input( InputType.checkBox ){

  attrs {
    ref = checkboxEl
    onChangeFunction = { event ->
      val switch = event.target.unsafeCast<INPUT>()
      
      //Pass the state of this checkbox (but don't reset it)
      checkBoxStateChanged(switch.checked)
    }
  }
}
```
Since I only need initial checkbox state update (with external prop) that's working just fine.

**Comment by fluidsonic** [comment]
I also ran into this.

Workaround:

```kotlin
val isChecked: Boolean = …
// attrs.checked = isChecked
attrs["checked"] = isChecked
```

**Comment by sgrishchenko** [comment]
@aerialist7

**Comment by aerialist7** [comment]
Will check it

**Comment by aerialist7** [comment]
Not reproduced
Tested on Kotlin Wrappers v.0.0.1-pre.268-kotlin-1.6.0

Code snippet
![image](https://user-images.githubusercontent.com/32072831/142752573-22f032be-1381-445e-bd3d-c8f7013c06dd.png)
