### ISSUE TITLE
Angular wrapper

### ISSUE THREAD

**Issue by theromis** [JetBrains/kotlin-wrappers#350]
Trying to use kotlin in combination with angular, seems like react only currently actively supported.
Is is possible to add angular wrapper?

PS: As initial step coul be used something from here
https://github.com/gbaldeck/angular-kotlin-starter/tree/master/src/kotlin/io/angular/sample/wrapper

**Comment by Skolotsky** [comment]
We don't work with angular and will not create wrappers for it in nearest future. But you can create your own.

**Comment by theromis** [comment]
@Skolotsky thank you for quick reply, sounds like I'll follow you guys and will use react in my current web interface refactoring of this https://www.lonje.com/chat/ :)
