### ISSUE TITLE
Add Aria Attributes to List of ReactDOMAttributes that need name fixing

### ISSUE THREAD

**Issue by bjoernmayer** [JetBrains/kotlin-wrappers#354]
Heyho,

it would be cool if you could add all aria HTML attributes to the list of ReactDomAttributes that need name fixing in [ReactDOMAttributes.kt](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react-dom/src/main/kotlin/react/dom/ReactDOMAttributes.kt).

This stops me currently from having something like this:
```kotlin
interface FancyProps : RProps {
    var ariaDisabled: Boolean?
    var tabIndex: Int?
}

val someFancyElement: ReactElement
val aListOfChildren: Any

child(
    cloneElement<FancyProps>(someFancyElement, Children.toArray(aListOfChildren) {
        ariaDisabled = true // does not work
        tabIndex = -1 // works
    }
)
```
While `tabIndex` gets corrected into `tabindex`, `ariaDisabled` does not get corrected and is rendered as `ariaDisabled` in HTML.

Disclaimer: The example is far from being complete. Also: Do not ask what I am doing there ^^

**Comment by Leonya** [comment]
This should be added to kotlinx-html, not here.
