### ISSUE TITLE
externals for all of the JS builtins

### ISSUE THREAD

**Issue by DetachHead** [JetBrains/kotlin-wrappers#355]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference

looks like currently only `Function` and `Object` are supported https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-extensions/src/main/kotlin/kotlinext/js

i'm interested in doing this myself, but should it be a separate package?

**Comment by Leonya** [comment]
Have you looked at https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/?

**Comment by DetachHead** [comment]
there seems to be many things missing from the stdlib such as `Object`, `Function`, `encodeURIComponent`, etc just to name a few. should they be added to the stdlib or kotlin wrappers? it seems weird that some of the builtins are there and others are here

**Comment by Leonya** [comment]
Those should be added to stdlib, if necessary. Please vote for existing issues in https://youtrack.jetbrains.com/issues/KT or file a new one.

It is also very easy to define missing externals in your own code.

**Comment by DetachHead** [comment]
I don't think it should be necessary to have to manually define a bunch of externals that are built in on the target. Raised https://youtrack.jetbrains.com/issue/KT-42808
