### ISSUE TITLE
Enable creating styled components from outside render functions

### ISSUE THREAD

**Issue by fluidsonic** [JetBrains/kotlin-wrappers#356]
I have a `styledLi` in one of my components:
```kotlin
styledLi {
    key = "item-${item.id}"

    css {
        margin(0.px, 0.px, 0.px, (8 * props.depth).px)
        padding(0.px)

        if (!props.isVisible)
            display = Display.none
    }

    // …
}
```

I keep getting warnings like this:
```text
The component styled.li with the id of "sc-AxiKw" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
```

Looking at the [docs](https://styled-components.com/docs/basics#adapting-based-on-props) I have to do the following (in JS) in order to avoid the creation of styled component from within a render function:
```jsx
const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => props.primary ? "palevioletred" : "white"};
  color: ${props => props.primary ? "white" : "palevioletred"};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

render(
  <div>
    <Button>Normal</Button>
    <Button primary>Primary</Button>
  </div>
);
```

This does not seem possible with `kotlin-styled`.

There are two functions that come close:
```kotlin
fun <P : WithClassName> styled(type: RClass<P>): RBuilder.(StyledHandler<P>) -> ReactElement
```
This one however needs an existing `RClass`. And it merely creates another `RBuilder`-based factory that like would cause the same issue. It's still dynamic and provides no way .

Then there is:
```kotlin
fun Styled.createElement(type: Any, css: CSSBuilder, props: WithClassName, children: List<Any>): ReactElement
```
This seems to be low-level API for creating styled `ReactElement`s rather than read-to-use DSL.

---

**Please provide a way to create reuse styled components [as possible in `styled`](https://styled-components.com/docs/basics#adapting-based-on-props).
If it's already possible then please provide an example in the README.**

**Comment by Leonya** [comment]
This was fixed a while ago, please update to the latest version of the wrappers.

**Comment by fluidsonic** [comment]
I'm using `5.2.0-pre.124-kotlin-1.4.10` which is the latest one available.

If you refer to #351 then that's unrelated. The change there is to ignore an intentional warning by `styled` in case a static global style is added.

As I'm writing dynamic non-global style in my example this doesn't ally and the issue is still open.

And the ability to write styled components outside of rendering isn't there either.

**Comment by fluidsonic** [comment]
First shot:

```kotlin
fun <P> styled(component: FunctionalComponent<P>, handler: StyledHandler<P>): FunctionalComponent<P> where P : RProps, P : WithClassName {
    val buildStyled = styled(component.unsafeCast<RClass<P>>())
    val styledComponent = { props: P ->
        buildElement {
            buildStyled {
                val dynamicAttrs = attrs.asDynamic()
                val dynamicProps = props.asDynamic()
                props.getOwnPropertyNames().forEach { propertyName ->
                    dynamicAttrs[propertyName] = dynamicProps[propertyName]
                }

                handler()
            }
        }
    }

    if (js("process.env.NODE_ENV !== 'production'") as Boolean) {
        val displayName = component.asDynamic().displayName as String?
        if (displayName != null)
            styledComponent.asDynamic().displayName = "styled.$displayName"
    }

    return styledComponent
}
```

Usage:
```kotlin
val funComp = functionalComponent<FunCompProps> { props ->
    div {
        props.className?.let { attrs.classes += it }
    }
}

interface FunCompProps : RProps, WithClassName

val styledFunComp = styled(funComp) {
    css {
        backgroundColor = Color.red
    }
}
```

The usage is still annoying.
- I have to extend my props from `WithClassName` to access `className`.
- `className` is `nullable` so `props.className?.let { attrs.classes += it }` is needed. Maybe it should be an empty string by default.
- When styling components from other files you run into this issue: https://youtrack.jetbrains.com/issue/KT-25796

**Comment by Leonya** [comment]
Could you please share a larger code example? `styledWhatever` with `css` is omnipresent in our codebase, but we aren't getting such warnings.

**Comment by fluidsonic** [comment]
I can make it smaller:

```kotlin
val HelloWorld = react.functionalComponent<RProps> {
    styledDiv {
        css.backgroundColor = Color.red

        +"Hello World"
    }
}

fun main() {
    render(document.getElementById("root")) {
        child(HelloWorld) {}
    }
}
```

>The component styled.div with the id of "sc-AxjAm" has been created dynamically.
You may see this warning because you've *called styled inside another component*.
To resolve this only *create new StyledComponents outside of any render method and function component*.

The warning is pretty clear and `kotlin-styled` doesn't support using the correct approach.

**Comment by Leonya** [comment]
Fixed in https://github.com/JetBrains/kotlin-wrappers/pull/363

**Comment by fluidsonic** [comment]
You've effectively removed the warning instead of fixing the actual issue 🤔

**Comment by Skolotsky** [comment]
It's not so easy to solve base design of that library. We are compensating problem of creating styles in render by caching it ourselves. So that warning isn't that actual for us. But it's still problem that that wrapper has so many differences with original library intentions.

**Comment by renaudcerrato** [comment]
I've just been bitten by this. Can you provide an example of style caching @Skolotsky? I've not so much experience in styled-components, I'm evaluating Kotlin for frontend development.

**Comment by andrew-k-21-12** [comment]
Have the same (seems like) question / issue. Want to assign readable class names for styles which are created dynamically. Thinking about style caching as well, but it doesn't seem to be very effective - especially if a style contains only small dynamic parts.

Here is what I mean:

```kotlin
private object NotificationHeaderStyles : StaticStyleSheet() {

    // A named class is created without problems.
    val titleAndDescriptionRows: RuleSet by css { flexGrow = 1.0 }
    
    // A dynamic class name is used obviously as there are no CssHolders added to the style sheet,
    // I want to have some readable names for such dynamic styles as well (╥_╥)
    fun container(context: Context): RuleSet = {
        display         = Display.flex
        backgroundColor = Theme.palette.backSpecial1(context)
    }
    
}
```
