### ISSUE TITLE
React-Redux 5.0.7 isn't actively maintained anymore. 

### ISSUE THREAD

**Issue by renaudcerrato** [JetBrains/kotlin-wrappers#357]
Hi folks! Is there any reason the React-Redux wrapper sticks to 5.0.7? That version has been released in Feb. 2018.

**Comment by Leonya** [comment]
react-redux wrapper was created by an external contributor, who is no longer actively maintaining it. We don't have anyone using redux internally, therefore this package hasn't been updated. Contributions are very welcome.

**Comment by renaudcerrato** [comment]
Got it, thanks. Will look into it.

**Comment by renaudcerrato** [comment]
Here we go: https://github.com/JetBrains/kotlin-wrappers/pull/359

**Comment by Leonya** [comment]
Fantastic, thank you!
