### ISSUE TITLE
Attribute selector in CSS

### ISSUE THREAD

**Issue by Just-A-Nerd** [JetBrains/kotlin-wrappers#360]
I am working on a project and would like to use the CSS attribute selectors.

Example CSS: 
```CSS
a[href="example"] {
  //CSS Code
}

a[href~="example"] {
  //CSS Code
}
```

I looked through some of the code and couldn't find any mention of them and was wondering if there is a way to use them.

**Comment by Leonya** [comment]
You can do the following:

In the stylesheet:

```kotlin
val container by css {
    "a[href=\"example\"]" {
        // CSS
    }
}
```

In the render function:

```kotlin
styledDiv {
    css {
        +container
     }

     styledA(href = "example") {}
}
```
