### ISSUE TITLE
react: label prop "for" should be called "htmlFor" instead

### ISSUE THREAD

**Issue by fluidsonic** [JetBrains/kotlin-wrappers#365]
Setting the prop `htmlFor`
```kotlin
label { attrs.htmlFor = "foo" }
```

leads to a React warning:
> Warning: Invalid DOM property `for`. Did you mean `htmlFor`?

React expects the **prop name** `htmlFor` but `kotlinx-html` uses the **attribute name** `for`.
`kotlin-react` must override the name to fix this issue.

### Workaround

```kotlin
label { attrs["htmlFor"] = "foo" }
```

**Comment by aerialist7** [comment]
Hi,

I've also reproduce this issue.
Here is my sample repo - https://github.com/aerialist7/reaktjs-sample

Note: It reproduces only in Development mode (all is ok in Production).

Run `./gradlew browserDevelopmentRun --continuous`

**Comment by aerialist7** [comment]
Also I fixed this issue in kotlinx.html - https://github.com/Kotlin/kotlinx.html/pull/170

**Comment by CLOVIS-AI** [comment]
Still broken in `17.0.2-pre.214-kotlin-1.5.20`

**Comment by turansky** [comment]
Fixed for `react.dom.ReactHTML.label` ([attributes](https://github.com/JetBrains/kotlin-wrappers/blob/6b44988220332a2f826c44be38b5ea19e38d53f4/kotlin-react-dom/src/main/generated/react/dom/LabelHTMLAttributes.kt#L9))

```Kotlin
import react.dom.ReactHTML.label

label {
    attrs.htmlFor = "foo"
}
```

**Comment by sgrishchenko** [comment]
Fixed in new intrinsic API

**Comment by Leonya** [comment]
Speaking of the new API: what about the documentation? Migration path?

**Comment by turansky** [comment]
> what about the documentation?

Free hands wanted :)
Non-implementers preferred for additional API check

> Migration path?

It's theme for the next maintainer's discussion

cc @SebastianAigner
