### ISSUE TITLE
Add wrapper for redux

### ISSUE THREAD

**Issue by Jamdan2** [JetBrains/kotlin-wrappers#37]
I've already wrote a very basic wrapper in a project, but I think it would be useful to anyone using kotlin react. Would something like this be a welcome pull request?

**Comment by Hypnosphi** [comment]
Sure, go for it. Please start with just `redux` package, typing `react-redux` must be a lot more tricky because of all the prop merging stuff

**Comment by Jamdan2** [comment]
I got started on the wrapper and I tried to push to a new branch, but I don't have permission (403 error) Is there a workaround for this?

**Comment by Hypnosphi** [comment]
You need to fork the repo first

**Comment by AnkBurov** [comment]
@Jamdan2 hello. Have you had any success with redux wrapper?

**Comment by Jamdan2** [comment]
@AnkBurov its coming along. I haven't tested it with middleware yet, and I still need to create type declarations for some parts of it.

**Comment by Jamdan2** [comment]
Well, its done! Thanks @Hypnosphi for helping out.

**Comment by Jamdan2** [comment]
I'll start working on a kotlin-react-redux
