### ISSUE TITLE
How to use programming style to switch routes

### ISSUE THREAD

**Issue by qiuquanwu** [JetBrains/kotlin-wrappers#382]
How to use programming style to switch routes,Not use Link or Navlink
```javascript
this.props.history.push("xxxx")
```

**Comment by qiuquanwu** [comment]
Can you submit the latest package to NPM official warehouse,The package of NPM warehouse has not been updated for a year。

**Comment by spand** [comment]
You can get a history object from a RouteResultProps, then pass that down to your component that needs it.

**Comment by qiuquanwu** [comment]
> You can get a history object from a RouteResultProps, then pass that down to your component that needs it.


thank you

**Comment by qiuquanwu** [comment]
thanks
