### ISSUE TITLE
Passing an int to unaryPlus fails silently

### ISSUE THREAD

**Issue by StokeMasterJack** [JetBrains/kotlin-wrappers#4]
Given the following code:

`div { +33 }`

i would expect one of two outcomes:

1. Convert the int to a string and display it
2. Fail, with a nice message explaining that unaryPlus only permits strings

Instead it just renders nothing with no errors or warnings.

**Comment by Hypnosphi** [comment]
Actually, we can't do the conversion, because unaryPlus is a built-in function for numbers (it converts them to positive), so when I try to overload it, I get the following warning:
```
Extension is shadowed by a member: public final operator fun unaryPlus(): Int
```

I don't think we can forbid it, either, because you may need it for some calculations

**Comment by Hypnosphi** [comment]
since `kotlin-react-dom@16.0.0-pre.7`, you can do any of the following:

```
attrs.jsStyle = js {
  width = "100px"
}

attrs.jsStyle {
  height = "100px"
}

attrs.jsStyle.backgroundColor = "red"
```
