### ISSUE TITLE
assign not work in InternetExplorer

### ISSUE THREAD

**Issue by gnefedev** [JetBrains/kotlin-wrappers#40]
@JsModule("core-js/fn/object/assign") must be used instead of @JsModule("core-js/library/fn/object/assign") 
Related conversation:
https://github.com/zloirock/core-js/issues/239

**Comment by Hypnosphi** [comment]
But here it isn't used as a global polyfill

**Comment by gnefedev** [comment]
Let's reformulate. I used clone() method, that used assign(). And it doesn't work in IE. For fix this I wrote version of assign with @jsmodule("core-js/fn/object/assign") and it works.
May be there is another solution, I don't very good in JS, but the fact is that clone() and assign() is not crosplatform in main version.

**Comment by Hypnosphi** [comment]
Can you please create a GitHub repo with minimal reproduction of your issue?

**Comment by gnefedev** [comment]
It doesn't reproduce any more. May be some it's caused by changes in base kotlin version. I will use main version.
Sorry for wasting you time.
