### ISSUE TITLE
event.target.value is not a property in KotlinJS

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [JetBrains/kotlin-wrappers#404]
Hi, I was experimenting with KotlinJS and was trying to create a simple app. I want to get the text from an input every time the user enters something into the input. Here's my code so far.

```kotlin
import kotlinx.browser.document
import kotlinx.browser.window
import org.w3c.dom.HTMLElement

fun setListener() {
    val input = document.getElementById("input")
    val text = document.getElementById("text")
    input?.addEventListener("keyup", {
        event -> val target = event.target as HTMLElement
        // target.value is not a property
    })
}

fun main() {
    window.onload = fun (event) {
        console.log(event)
        setListener()
    }
}
```

Is there anything that I'm doing wrong here?

**Comment by Leonya** [comment]
`HTMLElement` doesn't have a `value` property, `HTMLInputElement` does. Please ask general questions in Slack (https://surveys.jetbrains.com/s3/kotlin-slack-sign-up), this repository is not the best place for them.
