### ISSUE TITLE
form submit using kotlin-react example

### ISSUE THREAD

**Issue by abangkis** [JetBrains/kotlin-wrappers#420]
Hi. I'm a backend engineer that have no prior knowledge about react. I like to use kotlin-react for my simple front end project because I know kotlin. 

I've been able to show html and even navigate between component using kotlin-react-router example, but I can't seem to find any example about submitting input using a form with kotlin-react and then navigate away using kotlin-react-router. Can you kindly add it or maybe direct me to the right example. Thanks

**Comment by turansky** [comment]
[Related discussion](https://stackoverflow.com/questions/39809943/react-preventing-form-submission)
```kotlin
val history = useHistory()

form {
    attrs.onSubmit = {
        history.push("/new/path")
    
        it.preventDefault()
    }
}
```
