### ISSUE TITLE
Please sign releases for Software Supply Chain Security

### ISSUE THREAD

**Issue by vlsi** [JetBrains/kotlin-wrappers#427]
It looks like the signatures are missing for https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-js-wrappers/org/jetbrains/kotlin-react/17.0.1-pre.149-kotlin-1.4.31/

The signatures along with the upcoming https://sigstore.dev/what_is_sigstore/ are vital for Software Supply Chain Security.

**Comment by Leonya** [comment]
Versions starting with pre.201 are signed.
