### ISSUE TITLE
Manual for using e.g. @jetbrains/kotlin-react-router-dom as a package.json dependency

### ISSUE THREAD

**Issue by LittleLightCz** [JetBrains/kotlin-wrappers#43]
Hello there,

when I tried to use kotlin-react-router-dom wrappers as a package.json dependency in my project, e.g. by running `yarn add @jetbrains/kotlin-react-router-dom`, I ran into several issues:

1. IDEA couldn't find it (I resolved it by adding the @jetbrains/kotlin-react-router-dom as a library manually from the node_modules folder)
2. When I ran `yarn start`, it didn't compile (This I resolved by hacking the webpack.config.dev.js file in the react-scripts-kotlin folder by adding it to the libraries: [...] part of the KotlinWebpackPlugin)
3. When it finally compiled and development server started, it failed on some weird cryptic error (note that I also added react-router-dom dependency manually)

After 2 days of desperation I just copy-pasted the source files of kotlin-react-router-dom wrappers into my project's src directory and it worked like a charm!

I apparently did something wrong, because wrappers (as they are) work just fine, so my question is, is there any guide how to properly add these wrappers as a dependecies without the need to copy-paste them into the project directly?

Thanks a lot!

**Comment by Hypnosphi** [comment]
Looks like latest version of KotlinWebpackPlugin should handle it, see https://youtrack.jetbrains.com/issue/CRKA-75

CC @huston007

**Comment by huston007** [comment]
@LittleLightCz Could you check what version of react-scripts-kotlin did you use? 
You could get it by running `npm ls -g react-scripts-kotlin`, please send output here

**Comment by LittleLightCz** [comment]
@huston007 with that command I get "npm ERR! code 1", but when I remove the "-g" flag, I get: react-scripts-kotlin@2.1.5

So maybe I could try updating to 2.1.7 as @Hypnosphi mentioned in the CRKA ticket.

**Comment by Leonya** [comment]
That's right, with the latest version it should work flawlessly.

**Comment by LittleLightCz** [comment]
I've tried updating to 2.1.9 straight away, but weird thing is that now I am getting:
```
multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/react
-scripts-kotlin/config/polyfills.js kotlinApp
Module not found: Can't resolve 'kotlinApp' in ...
```

I created a [branch](https://github.com/LittleLightCz/TaskMan/tree/react-scripts-kotlin%402.1.9) in my project, so you can eventually try it out.

First I go to `taskman-frontend` directory, run `yarn install`, then `yarn start` and the error should pop up. I also tried to generate fresh project using `create-react-kotlin-app` and that works fine. It seems that just changing the number of the `react-scripts-kotlin` version in my project doesn't do all the tricks to make it run :-).

**Comment by LittleLightCz** [comment]
**Resolved!** I found out that some import errors occured in my own react router wrappers copy when I switched to `react-scripts-kotlin@2.1.9` , but I had to go and open every single .kt file in IDEA to see if there is anything wrong. The error yielded by yarn didn't really tell me anything at all ... which is pity. Also I can't do "Build project" as in Java - it tells me there is no SDK defined. 

It would be good either if IDEA could check all .kt files for errors on demand (same as build/rebuild project in Java) or if yarn could show corrupted source files with line numbers etc. when such error happens ... anyway thanks for your help guys! Now I am going to try adding the wrapper dependencies into the package.json file and I will see if it will work out.

**Comment by KirkBushman** [comment]
Hi, I'm using 2.1.11 and the same error appears: 
 
      multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/react-scripts- 
      kotlin/config/polyfills.js kotlinApp
      Module not found: Can't resolve 'kotlinApp' in ...

Can I ask you to be more specific about how you solved the issue @LittleLightCz ? 

I see reacts imports been flagged for unresolved reference and the project is full of errors, but it was fine until yesterday, I dunno what happened...

**Comment by LittleLightCz** [comment]
Hi @KirkBushman, it's been some time ago, but from what I can read from my last comment, try to open every single .kt file in IDEA and wait for a little while if there aren't any compile errors. My problem was that these compile errors didn't show up when I ran build using yarn.

**Comment by LittleLightCz** [comment]
If you already found import errors, try to delete those lines and run auto-import which should (perhaps) put there the correct ones.

**Comment by KirkBushman** [comment]
I found and corrected any imports errors I could find but it's not going away...

**Comment by TTransmit** [comment]
@KirkBushman I created a file `.env` at the same level as `package.json` containing the following single line: 
```
NODE_PATH=./src
```
This turns on absolute imports, which fixed the problem for me. I then ran `npm install` and `npm start`. I'm not familiar with node and npm so I don't really understand if this is a good thing to do. 
I could then use imports like 
```kotlin
import react.router.dom.*
```
