### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by joffrey-bion** [JetBrains/kotlin-wrappers#431]
It is inconvenient to have to declare 2 different custom repos to consume even just one of the dependencies (kotlin-js-wrappers + kotlinx-html maven repos on Space).

Is there any plan to publish all of this in the same place? (preferably maven central)

**Comment by NiematojakTomasz** [comment]
https://kotlin.jetbrains.space/ is not even public...

**Comment by joffrey-bion** [comment]
@NiematojakTomasz The Space server itself is not public, but the maven package repository inside is in fact accessible publicly.

You have to go directly to the maven repository:
https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-js-wrappers/org/jetbrains/

For `kotlinx-html` it's a different maven repository:
https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven

**Comment by turansky** [comment]
`kotlinx-html` now available in Maven Central

**Comment by joffrey-bion** [comment]
@turansky Awesome! Do you know if there are plans for kotlin js wrappers to follow suit?

**Comment by turansky** [comment]
[Related Slack discussion](https://kotlinlang.slack.com/archives/C5ZTZ6ER0/p1615980908000700?thread_ts=1615911674.010100&cid=C5ZTZ6ER0)

**Comment by Leonya** [comment]
Waiting for approval: https://issues.sonatype.org/browse/OSSRH-69043

**Comment by Leonya** [comment]
Finally: https://repo1.maven.org/maven2/org/jetbrains/kotlin-wrappers/

search.maven.org doesn't list the new packages yet, I am told it takes a while for it to update.

Note that group ID was changed from `org.jetbrains` to `org.jetbrains.kotlin-wrappers` and the version number was bumped to `pre.200+` to reflect this change. Please refer to README.md for more details.
