### ISSUE TITLE
[kotlin-react-table] Uncaught TypeError: functionalComponent is not a function

### ISSUE THREAD

**Issue by javavirys** [JetBrains/kotlin-wrappers#433]
fun <P : RProps> functionalComponent(displayName: String? = null, func: RBuilder.(props: P) -> Unit): FunctionalComponent<P> - returns an error: functionalComponent is not a function

![image](https://user-images.githubusercontent.com/10163172/113574663-37db3000-9625-11eb-84d0-b74308e78414.png)

**Comment by turansky** [comment]
Looks like local cache problem

**Comment by turansky** [comment]
@javavirys Could you check it on latest version?
