### ISSUE TITLE
Why thisRef: Nothing? in RStateDelegate<T> ?

### ISSUE THREAD

**Issue by IARI** [JetBrains/kotlin-wrappers#436]
I have recently updated kotlin-react - and I noticed that some of my code is now broken.
Apparently, the getValue operator for State Delegates now does not accept This a value anymore, but enforces `thisRef: Nothing?`
https://github.com/JetBrains/kotlin-wrappers/blob/85f144361eeb723732009a0a66ada9a4c5bac101/kotlin-react/src/main/kotlin/react/hooks.kt#L26

Why this restriction? Why Can't it just be `Any?`?
The broken code looks like this - why should that not work anymore?

```Kotlin
val LoginContextProvider = functionalComponent<LoginContextProviderProps> { props ->
    // ...
    val loginContextData = object : LoginContextData {
        override var user: BackendUser? by userSDel
        override var auth: Authentication? by useState(null)
        // ...
    }
    // ...

    LoginContext.Provider(loginContextData) {
        props.children()
    }
}  
```

**Comment by turansky** [comment]
Looks like you create new `loginContextData` **every** render. 
Is it expected? 
Looks like error
