### ISSUE TITLE
Missing executing `npm run gen-idea-libs` requirement after including a new kotlin-wrapper dependency

### ISSUE THREAD

**Issue by Buckstabue** [JetBrains/kotlin-wrappers#48]
I spent at least a half of an hour to figure out, that I need to execute `npm run gen-idea-libs` after I include kotlin-react-router by executing
`npm i @jetbrains/kotlin-react-router-dom`
Please specify that in the documentation or automate it somehow.

**Comment by Leonya** [comment]
Fixed.
