### ISSUE TITLE
"When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule" error when using useState(...)

### ISSUE THREAD

**Issue by THEAccess** [JetBrains/kotlin-wrappers#488]
When using `var selected by useState(false)` the `:compileKotlinJs` task throws the following error:
```
When accessing module declarations from UMD, they must be marked by both @JsModule and @JsNonModule
```
Im using the latest version `pre.211` and the `LEGACY` compiler

**Comment by Leonya** [comment]
Sorry about that, fixed in pre.212
