### ISSUE TITLE
A standalone example is missing

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#49]
It is not clear now one create/use the library in the Gradle/NPM project. A fully-dedicated example and setup instructions are really nice to have

**Comment by Kabbura** [comment]
I tried the following:
- Added maven repo and kotlin-css, kotiln-css-js as dependencies.
- Code compiles successfully.
- However, in the browser it cannot find module.export. 
Anyway to overcome this?

**Comment by androidovshchik** [comment]
Any update? Non gradle way doesn't resolve kotlin code for me

**Comment by mkraynov** [comment]
There is [an example](https://github.com/Kotlin/kotlin-full-stack-application-demo) now from Kotlin team.

**Comment by turansky** [comment]
One more [standalone example](https://github.com/aerialist7/kotlin-react-table-sample)
