### ISSUE TITLE
Implement ErrorBoundary (getDerivedStateFromError)

### ISSUE THREAD

**Issue by THEAccess** [JetBrains/kotlin-wrappers#493]
How can I implement an error boundary with ` getDerivedStateFromError` according to the [react docs](https://reactjs.org/docs/error-boundaries.html) with Kotlin React Wrappers?

Since `getDerivedStateFromError` is a `static` function in React.js my first attempt was to implement it as `companion object`
```
class ErrorBoundary : RComponent<ErrorBoundaryProps, ErrorBoundaryState>() {
 
  companion object {
        fun getDerivedStateFromError(error: Throwable): RState? {
            return object : ErrorBoundaryState {
                override var error: String? = error.message ?: "<unknown>"
            }
        }
    }
[...]
}
```
That doesn't work unfortunately. In the source code I can see that  ` RComponentClassStatics` which is inherited by `RClass` [has a getDerivedStateFromError function](https://github.com/JetBrains/kotlin-wrappers/blob/372110875523cd0dbbec2b11707142ee96d96ee8/kotlin-react/src/main/kotlin/react/ReactComponent.kt#L56) but I don't know how to access it from `RComponent`.

**Comment by turansky** [comment]
[Instruction](https://github.com/JetBrains/kotlin-wrappers/blob/49c199f5a029ec0e9c45c13458357683a04ea5a8/kotlin-react/src/main/kotlin/react/React.kt#L44)

**Comment by turansky** [comment]
@Leonya Issue can be closed

**Comment by THEAccess** [comment]
I have tried out the[ implementation suggested by @turansky](https://github.com/THEAccess/kotlin-react-errorboundary-example/blob/9126523ea50e19f0eedd56be072773908b940cb2/src/main/kotlin/ErrorBoundary.kt#L18) but it doesn't seem to be working for me. [I have wrapped `BuggyComponent` in `ErrorBoundary`](https://github.com/THEAccess/kotlin-react-errorboundary-example/tree/main/src/main/kotlin) but the error isn't caught by ErrorBoundary. 
Console:
```
The above error occurred in the <BuggyComponent> component:

BuggyComponent@webpack-internal:///./kotlin-dce-dev/kotlin-react-errorboundary.js:60:20
ErrorBoundary@webpack-internal:///./kotlin-dce-dev/kotlin-react-errorboundary.js:108:20

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```
Am I missing something here or is it a bug?

**[Reprodicible Example](https://github.com/THEAccess/kotlin-react-errorboundary-example)**

**Comment by turansky** [comment]
> Am I missing something here or is it a bug?

You don't use `init` like in example :(

**Comment by THEAccess** [comment]
> 
> 
> > Am I missing something here or is it a bug?
> 
> You don't use `init` block like in example :(

In addition to that, I had to use ` jsObject { ... }` instead of `object : ErrorBoundaryState { ... } `. I didn't know that since I come from the Android World.

[Git repo as reference for anyone having the same problem](https://github.com/THEAccess/kotlin-react-errorboundary-example)
