### ISSUE TITLE
Type safe CSS

### ISSUE THREAD

**Issue by StokeMasterJack** [JetBrains/kotlin-wrappers#5]
Some way to do type-safe css. GWT had this. I would check that out for an example.

**Comment by StokeMasterJack** [comment]
Here is what I am doing now:

`attrs.style = Css(display = "flex").toJs()`

Where Css looks like this:

```
data class Css(
    val width: String? = null,
    val height: String? = null,
    val padding: String? = null,
    val margin: String? = null,
    val marginRight: String? = null,
    val marginTop: String? = null,
    val marginLeft: String? = null,
    val marginBottom: String? = null,
    val background: String? = null,
    val display: String? = null
    //remaining props omitted
) {

  fun toJs(): dynamic = this
}

```
It seems to me that this pattern could be improved upon with a few tweaks to the wrapper.

Why does attrs.style have String as it's type? In the underlying React, it is an object.  It would be elegant to make it of type Css (using a class similar to the one I showed above). Then you could just do this:

`attrs.style = Css(padding = "1rem", margin = "1rem")`

**Comment by Hypnosphi** [comment]
> Why does attrs.style have String as it's type
Actually that's only because of kotlinx.html

We have an internal solution for type-safe CSS internally, I'll try to find out which part of it can be open-sourced.

For now, I think I'll just add something like `jsStyle: dynamic` attribute to fix #6

**Comment by StokeMasterJack** [comment]
> Actually that's only because of kotlinx.html

Does this and kotlinx.html share some common base class?

> I think I'll just add something like jsStyle: dynamic

Then I should be able to omit the toJs(), right?

```
attrs.style = Css(display = "flex").toJs()
attrs.jsStyle = Css(display = "flex") //like this?
```

**Comment by Hypnosphi** [comment]
> Does this and kotlinx.html share some common base class?

We use it to avoid hard-coding all the attributes available for different tags

> Then I should be able to omit the toJs(), right?
yep

**Comment by deviant-studio** [comment]
https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-styled
is this the thing?

**Comment by Hypnosphi** [comment]
Yes, but not really ready for use yet

**Comment by Leonya** [comment]
See https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-styled
