### ISSUE TITLE
Style is not applied when the function registered in useEffect is called

### ISSUE THREAD

**Issue by nosix** [JetBrains/kotlin-wrappers#506]
I tried to get the height of the element after the drawing was completed using `useEffect`. However, the style was not applied when the function registered in `useEffect` was called.

Therefore, using the following sample, I checked the state of the element by breaking when the function registered in `useEffect` was called.

```kotlin
val Sample = functionalComponent<RProps> {
    useEffect {
        console.log("useEffect")
        MainScope().launch {
            console.log("nextTick")
        }
    }
    val styles = object : StyleSheet("SampleStyles", isStatic = true) {
        val root by css {
            height = 100.vh
            backgroundColor = Color.green
        }
    }
    styledDiv {
        css { +styles.root }
    }
}
```

As a result, there was no style at the timing of `useEffect`, and there was the following style at the timing of `nextTick`.

```html
<style data-styled="active" data-styled-version="5.3.0">.SampleStyles-root{height:100vh;background-color:green;}</style>
```

When I read the code to see why this is the result, I found that it was due to the `Promise` being used by `injectGlobal`.

https://github.com/JetBrains/kotlin-wrappers/blob/5dd19be8a91b3130679a6f9b507fbbf36b28a6a6/kotlin-styled/src/main/kotlin/styled/StyledComponents.kt#L164-L169

I think the reason for using `Promise` is to avoid calling `render` during `render` processing.

https://github.com/JetBrains/kotlin-wrappers/blob/5dd19be8a91b3130679a6f9b507fbbf36b28a6a6/kotlin-styled/src/main/kotlin/styled/StyledComponents.kt#L152-L158

I think I understand the cause, but I don't have a good idea to solve it. I understand that the function registered in `useEffect` is called after the drawing is completed, but is the current situation where the style is not applied as expected?

> the function passed to useEffect fires after layout and paint, during a deferred event.

https://reactjs.org/docs/hooks-reference.html#useeffect

version: 5.3.0-pre.213-kotlin-1.5.20

**Comment by Leonya** [comment]
@Skolotsky any suggestions?

**Comment by Skolotsky** [comment]
Have you tried useLayoutEffect?

**Comment by nosix** [comment]
Yes. I have tried useLayoutEffect. The result was the same as useEffect.

I tried experimenting without the render call of readt-dom. I tried to run it with the following code.

```kotlin
open class StyleSheet(var name: String, val isStatic: Boolean = false) {
    // ... snip ...

    fun inject() {
        if (isStatic && staticStyle == null) {
            val keys = holders
                .flatMap { cssHolder ->
                    cssHolder.properties.map { it to cssHolder }
                }

            val builder = CSSBuilder(allowClasses = false).apply {
                keys.forEach {
                    ".${getClassName(it.first)}" {
                        for (r in it.second.ruleSets) {
                            r()
                        }
                    }
                }
            }
            components.add(createGlobalStyle(builder.toString())) // change this
            holders.clear()
        }
    }

    // Add the following
    private val components = mutableListOf<Component<RProps, RState>>()

    val component = functionalComponent<RProps> {
        components.forEach {
            child(it, jsObject {}, emptyList())
        }
    }
}
```

```kotlin
val Sample = functionalComponent<RProps> {
    useEffect {
        console.log("useEffect")
        MainScope().launch {
            console.log("nextTick")
        }
    }
    val styles = object : StyleSheet("SampleStyles", isStatic = true) {
        val root by css {
            height = 100.vh
            backgroundColor = Color.green
        }
    }
    styledDiv {
        css { +styles.root }
        child(styles.component) // add this
    }
}
```

In this case, the style exists when the function registered in useEffect is called. But I don't think this is a good idea.

**Comment by Skolotsky** [comment]
Why do you need to create stylesheets in render time, especially each render? It wasn't designed to work like this.
Anyway if you create it in `useMemo` and call `inject` it will schedule rendering stylesheet component using microtask. So it isn't in DOM when effect is called.
Please describe your use case, why do you need to access it?

**Comment by nosix** [comment]
What I tried to do is calculate the height of the child component based on the height of the parent component. The parent component has a height of 100vh, and the child component was thinking about how to determine the height according to the specific number of pixels of the parent component.

At first, the calculation process was performed at the place where `useEffect` was printed. However, at this point I found that the style had not been applied, so I changed to a method that calculates where the `nextTick` is printed. I thought I could solve it, but when I added other processing using coroutines, I sometimes couldn't solve it. In that case, I found that it can be solved by adding `delay(1)` in the place of `nextTick` and delaying it further. However, this is not an essential solution, and I suspect that more problems will arise in the future. 

And I wanted to know a better solution, so I first wanted to see if the library was working as expected. If it works as expected, it is a problem to be dealt with on the application side, so I am willing to close this issue.

**Comment by Leonya** [comment]
What Akif was saying is that style creation `val styles = ...` belongs outside a component. Please try moving it and report back.

**Comment by Skolotsky** [comment]
To calculate sizes - use ResizeObserver

**Comment by nosix** [comment]
> What Akif was saying is that style creation `val styles = ...` belongs outside a component. Please try moving it and report back.

The result does not change even if you do the following.

```kotlin
private val styles = object : StyleSheet("SampleStyles", isStatic = true) {
    val root by css {
        height = 100.vh
        backgroundColor = Color.green
    }
}

val Sample = functionalComponent<RProps> {
    useEffect {
        console.log("useEffect")
        MainScope().launch {
            console.log("nextTick")
        }
    }
    styledDiv {
        css { +styles.root }
    }
}```

Thanks.
