### ISSUE TITLE
How to use getDerivedStateFromProps

### ISSUE THREAD

**Issue by heinrisch** [JetBrains/kotlin-wrappers#52]
`getDerivedStateFromProps` is currently defined as member function without return, but should be a static function returning a state. 

How do I use it?

**Comment by Leonya** [comment]
@Hypnosphi we have to figure out a way to declare getDerivedStateFromProps as a static function. A member function simply doesn't work, React throws an exception.

**Comment by Hypnosphi** [comment]
> A member function simply doesn't work

And it shouldn't

We need to declare `RStatics` interface, and use it in component's `companion object`

**Comment by Hypnosphi** [comment]
Looks like the above won't work: Kotlin doesn't attach companion object members directly to JS constructor. https://youtrack.jetbrains.com/issue/KT-18891 may help in the future, but for now you need to do it by hand:

```
MyComponent::Class.js.asDynamic().getDerivedStateFromProps = ...
```

**Comment by heinrisch** [comment]
Thanks for the answers! I'll close this and wait for the future :)

**Comment by Leonya** [comment]
```
MyComponent::Class.js.asDynamic().getDerivedStateFromProps = ....
```

What am I supposed to write on the right-hand side?

**Comment by Hypnosphi** [comment]
A lambda, of course

**Comment by Leonya** [comment]
Added some documentation.
