### ISSUE TITLE
How to define a custom hook?

### ISSUE THREAD

**Issue by cangSDARM** [JetBrains/kotlin-wrappers#530]
I tried this, but the compilation was unsuccessful

```kotlin
fun useXX(): List<Card> {
    var cardsInDeck by useState<List<Card>>(listOf())  /// useState cannot used in there

    useEffect {
        MainScope().launch {
            initCards().also {
                cardsInDeck = it
            }
        }
    }
    
    return cardsInDeck
}
```

[Similar question](https://stackoverflow.com/questions/67024924/writing-a-custom-hook-in-kotlin-react) on StackOverflow

**Comment by turansky** [comment]
Valid realization:
```Kotlin
fun useXX(): List<Card> {
    var cardsInDeck by useState<List<Card>>(listOf())  /// useState cannot used in there

    // one time
    useEffectOnce {
        val job = GlobalScope.launch {
            cardsInDeck = initCards()
        }
        
        // cleanup
        cleanup(job::cancel)
    }
    
    return cardsInDeck
}
```

**Comment by cangSDARM** [comment]
> Valid realization:
> 
> ```kotlin
> fun useXX(): List<Card> {
>     var cardsInDeck by useState(emptyList<Card>())
> 
>     // one time
>     useEffectOnce {
>         val job = GlobalScope.launch {
>             cardsInDeck = initCards()
>         }
>         
>         // cleanup
>         cleanup(job::cancel)
>     }
>     
>     return cardsInDeck
> }
> ```

I did not find `useEffectOnce` and `cleanup`

But I changed it like this according to your suggestion:
```kotlin
fun useXX(): List<Card> {
   var cardsInDeck by useState(emptyList<Card>())
   
   useEffectWithCleanup(emptyList()) {
        val job = GlobalScope().launch {
            initCards().also {
               deckCards = it
            }
        };
        { job.cancel() }
   }

   return cardsInDeck
}
```

**Comment by cangSDARM** [comment]
Now it works fine.
Thanks!

**Comment by turansky** [comment]
> I did not find useEffectOnce and cleanup

It available in `pre.215` for sure
