### ISSUE TITLE
Typesafe RProps/RState

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#54]
Type-safe RProps and RState with default values. 

It looks nice to be able to define and create a wrapper class for `RProps` that deals with default values, validation, state updates. The class uses original `RProps` like a key-value map. Similarly, we do with RProps. Current approach with interfaces works nice but lacks any type checks and one has to have an interface declared (no assertions, btw in the code).

The outcome is that a component is ready to work (all properties are set to correct values). 

Having such class created explicitly is the way to specify all non-default values. That will make the compiler to check if all parameters are specified

**Comment by sgrishchenko** [comment]
duplicated by #132
