### ISSUE TITLE
cannot define same styles for CSSBuilder

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#56]
```
CSSBuilder().apply { body + head { ... } }
```

That or similar is not possible right now, thus I need to duplicate code.
Could be cool to be able to generate CSS without duplicates too

**Comment by Leonya** [comment]
I wouldn't do it like this because + is an adjacent sibling selector, using it instead of a comma would be wildly confusing.

**Comment by Hypnosphi** [comment]
You can avoid duplication by extracting a variable
