### ISSUE TITLE
  StyledComponents.injectGlobal for CSSBuilder

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#57]
Let's have an extension function to make it work directly with `CSSBuilder` or probably only via a lambda with a receiver.

Current (too tricky, hard to make IJ to add necessary extension operators, btw) code is 
```
StyledComponents.injectGlobal(CSSBuilder().apply { ...csshere ... }.toString())
```

It looks nice to have something like
```
StyledComponents.injectGlobal { 
  ...csshere...
}
```

**Comment by Leonya** [comment]
Done.
