### ISSUE TITLE
CSSBuilder generates CSS without offsets

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#60]
The `toString()` returns the CSS, where
 - missing new-line separator between selectors
 - missing indenting (4 spaces) for every block internals

example output
```body {
font-family: -apple-system,BlinkMacSystemFont,Helvetica Neue,Arial,sans-serif;
font-size: 12px;
background-color: #999;
}
button {
line-height: 24px;
border-radius: 3px;
border-color: rgb(68, 68, 68);
padding-right: 16px;
padding-left: 16px;
margin-right: 8px;
margin-left: 8px;
}```

**Comment by turansky** [comment]
Compact formatting - expected behaviour for `toString`

@Leonya We can close this issues
