### ISSUE TITLE
useEffectOnce / useLayoutEffectOnce / useRef broken when re-rendering at an above component

### ISSUE THREAD

**Issue by Lezzio** [JetBrains/kotlin-wrappers#614]
Hi,

When using these hooks in a component, whenever we trigger a re-render from the above components it doesn't remember it has been fired once already and loses its "memory". Note that the re-render needs to induce DOM modifications (node add/delete as far as I know) for the bug to happen.

The expected behavior is the following on React JS :
https://codesandbox.io/s/kind-sea-45wqs?file=/src/App.tsx
But it instead acts just like this : 
https://codesandbox.io/s/kind-sea-45wqs?file=/src/App.tsx

It's what we've at least observed in our project and we reproduced the bug this way : 

**Main component with the state update and children:**
![image](https://user-images.githubusercontent.com/7536802/128907318-81cd4abc-7fa4-4cdf-b06e-fb7282b487b8.png)

**OnceComponent :** 
![image](https://user-images.githubusercontent.com/7536802/128907074-cc4597a6-3c6b-4c85-b686-d7bfce8c885b.png)

**ParentComponent :**
![image](https://user-images.githubusercontent.com/7536802/128907579-7bc92bc0-cd7f-4047-adaa-1466f897a906.png)

Console output after pressing the button multiple times : 
![image](https://user-images.githubusercontent.com/7536802/128907732-086b546d-58db-4efc-84a5-40f412a54408.png)

The minimal way to work around this issue is by using a unique key on the uppermost components next to the state being updated (direct children) : 

**Works**
![image](https://user-images.githubusercontent.com/7536802/128908413-2487905a-dd9d-477f-9b15-5884280bdf60.png)

**Works**
![image](https://user-images.githubusercontent.com/7536802/128908340-35e171bb-f634-46e1-8fa7-a203f532c5d0.png)

NB : Slack thread on the issue https://kotlinlang.slack.com/archives/C5ZTZ6ER0/p1628553043020800

**Comment by turansky** [comment]
@Lezzio @PeredurOmega Do you use function components?

**Comment by PeredurOmega** [comment]
Almost exclusively

**Comment by sgrishchenko** [comment]
This issue is reopened because we still have problems with keys in wrappers and we have plans to introduce some solution.

**Comment by turansky** [comment]
Workarounds unlocked by #1264

**Comment by turansky** [comment]
Next step - compiler plugin! :)

**Comment by turansky** [comment]
Compiler plugin with conditional rendering support [is ready](https://github.com/turansky/seskar#conditional-rendering)!
