### ISSUE TITLE
how to import and use react-bootstrap components on Kotlin multiplatform

### ISSUE THREAD

**Issue by Slava96** [JetBrains/kotlin-wrappers#618]
Hello!
I try to import React components from the react-bootstrap library and use it on my project.

I use Dukat, at first, to generate Kotlin types. Next, I remove some of these types and fix some non-existing classes to the kotlin-wrappers analogues.

It's my final code of Button component with related props.
```
external interface ButtonProps: RProps {
  var active: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var block: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var variant: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var size: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var type: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var href: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var disabled: Boolean?
    get() = definedExternally
    set(value)=definedExternally
var target: Boolean?
    get() = definedExternally
    set(value)=definedExternally
}

@JsName("default")
external var Button: RClass<ButtonProps>
```

How can I add an onClick event handler to props? Because I want to write type-safe code on these components. 
Or can you guide me on how to provide correct type-safe bindings to existing React components from JS libraries?

**Comment by turansky** [comment]
Also:
`PropsWithChildren` - children accepted
`Props` - children not accepted

**Comment by turansky** [comment]
@Slava96 Solved?

**Comment by Slava96** [comment]
No, this not works because I receive an error.

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports
```

**Comment by Slava96** [comment]
Finally, this problem was resolved. 
This problem is caused by an invalid name on @JsName annotation. Instead of using "default", we need to use "Button".
So, with this fix, it's working.
