### ISSUE TITLE
Support attrs in styled components

### ISSUE THREAD

**Issue by jonnyzzz** [JetBrains/kotlin-wrappers#62]
I see no equivalent to 
```
const Component = styled.div.attrs({
    style: ({ background }) => ({
      background,
    }),
  })`width: 100%;`

```

Also, I have warnings in browser console that I generate too many styles (because try do depend on parameters) 
![image](https://user-images.githubusercontent.com/256431/40459689-24ad50e6-5f03-11e8-8b07-d743c722607f.png)

**Comment by Hypnosphi** [comment]
The way `kotlin-styled` uses `styled-component` is completely different from recommended usage. Basically, it creates `styled(props => props.css)` for all the components.

Unfortunately, neither me nor @Leonya had a chance to implement it properly.

**Comment by Hypnosphi** [comment]
But what's actually does this warning recommend is to use inline styles, which is totally doable:

```
styledDiv {
  attrs.jsStyle.background = props.background
}
```

**Comment by chadmorrow-fd** [comment]
Just curious, how exactly is `kotlin-styled` different from recommended usage of styled-components? If this isn't implemented properly, should we hold off on using this library for now?

**Comment by Hypnosphi** [comment]
The recommended way is to use `styled` as higher order component, and include styles at declaration side, like this

```
const StyledButton = styled(MyButton)(props => `
   display: inline-block;
   color: props.color;
`);
```

What we do, basically, is wrap every component in `styled(MyComponent)(props => props.css)` and then add styles at usage side, which can be more convenient (you just work with it like with inline styles), but less efficient and scalable

>  If this isn't implemented properly, should we hold off on using this library for now?

I would say so

**Comment by chadmorrow-fd** [comment]
Thanks, that's helpful to know. I'll hold off for now then but you all have done awesome stuff with this library so far. Looking forward to what you've got planned in the future!

**Comment by fluidsonic** [comment]
I ran into this issue too and came up with a first shot at styling a `FunctionalComponent` here:

https://github.com/JetBrains/kotlin-wrappers/issues/356#issuecomment-713255640
