### ISSUE TITLE
[Question] kotlin-styled import modules from ecosystem

### ISSUE THREAD

**Issue by kastork** [JetBrains/kotlin-wrappers#63]
Is there a convenient way to utilize React javascript modules in kotlin-react code?

For example, to use a styled-components package like react-flexa -- if you were writing JS, you could say

import { Row, Col } from 'react-flexa';

And then use it

`<Row justifyContent="center"> ... `

What is the analog for this in Kotlin (if any)?

**Comment by Hypnosphi** [comment]
Here's some example: https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/main/kotlin/example/Quill.kt
