### ISSUE TITLE
[ring-ui] Add Footer component?

### ISSUE THREAD

**Issue by Neitex** [JetBrains/kotlin-wrappers#636]
I've tried to implement it by myself, but it did not seem to work, so i ask it here (sorry, if that is the wrong place)

**Comment by turansky** [comment]
> sorry, if that is the wrong place

Place is valid :)

@Neitex Did you check `Header` as reference?

**Comment by Neitex** [comment]
@turansky Yes, I did. But when I try to insert FooterColumn into website, it throws this error:
 ```Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```
As I'm not the strongest JS dev out there, I don't know, what it is talking about.
Also, there are that array props of Footer: 
```js
Footer.propTypes = {
  className: PropTypes.string,
  floating: PropTypes.bool,
  left: PropTypes.array,
  center: PropTypes.array,
  right: PropTypes.array
};
```
The problem is that I don't understand, what types it expects. I've tried to set it to dynamic ( 
```kotlin
external interface FooterProps: WithClassName{
    var floating: Boolean
    var left: Array<dynamic>
    var center: Array<dynamic>
    var right: Array<dynamic>
}
```
), but only input that seems to work is String, which is not the best customization option.
My full code: https://gist.github.com/Neitex/2c8f7d8cd9b928092c212273f1025ef2

**Comment by turansky** [comment]
`dynamic` prohibited :)
Strict types you can see [here](https://jetbrains.github.io/ring-ui/master/?path=/story/components-footer--basic) and in sources

**Comment by Neitex** [comment]
As I said, I'm not good enough in JS, and can't find any strict types in source, nor in Storybook :(
It just says 
```js 
left: PropTypes.array,
center: PropTypes.array,
right: PropTypes.array
```
 , which are not strict

**Comment by Neitex** [comment]
I've implemented Footer (it seems that FooterLine and FooterColumn are not supposed to be used, as it's only usage is inside Footer's content function) with extension to make it easier to use
Full Footer.kt file: https://gist.github.com/Neitex/6435dd059e840be623e459d24b663516
Full Footer.ext.kt file: https://gist.github.com/Neitex/98e241b239ff01de9f9edc9d9285407e

**Comment by Neitex** [comment]
I've written another version, working this time :).
Footer.kt: https://gist.github.com/Neitex/e8749d2a12c538eec0886c9003defcf2
Footer.ext.kt: https://gist.github.com/Neitex/3a7f3f9b245671bdce3f3a0b13a02162
Target.kt: https://gist.github.com/Neitex/8af0b892800a55cf45e3dea4d0112639

**Comment by turansky** [comment]
1. "Target" already exists in wrappers
2. `left`, `right` ... - `ReadonlyArray`?
3. More granular builder required

For first PR (without builder) required:
1. Name check for external interfaces
2. String adoption

cc @sgrishchenko
