### ISSUE TITLE
Wrappers for TestUtils

### ISSUE THREAD

**Issue by eiswind** [JetBrains/kotlin-wrappers#67]
It would be great to have wrappers for the TestUtils from react-dom. 

Is something like this on the Roadmap?
I could help with this, but I still fail to run any Unit Test at all...

**Comment by epabst** [comment]
I wonder if Enzyme might be preferable to this.

**Comment by turansky** [comment]
[kotlin-react-dom-test-utils](https://github.com/JetBrains/kotlin-wrappers/tree/master/kotlin-react-dom-test-utils) introduced
