### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by campino** [JetBrains/kotlin-wrappers#69]
Using kotlin-react-router-dom, I get this error: 

````
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `MainComponent`. in MainComponent
````
I managed to reduce it to a reproducible example: 
````
import react.RBuilder
import react.RComponent
import react.RProps
import react.RState
import react.dom.div
import react.dom.render
import react.router.dom.browserRouter
import react.router.dom.hashRouter
import react.router.dom.route
import react.router.dom.switch
import kotlin.browser.document
import kotlin.browser.window

class SimpleComponent : RComponent<RProps, RState>() {
    override fun RBuilder.render() {
        div {
            +"Test"
        }
    }

}

class MainComponent : RComponent<RProps, RState>() {
    override fun RBuilder.render() {
        div {
            + "before"
        }
        browserRouter {
            switch {
                route("/", SimpleComponent::class, exact = true)
            }
        }
    }

}

fun main(args: Array<String>) {
    window.onload = {
        render(document.getElementById("root")!!) {
            child(MainComponent::class) {}
        }
    }
}
````
I comment out the div before the browserRouter (the one containing the text "before"), the error disappears and the router works as advertised. 

I use gradle to build, my build.gradle is identical to https://github.com/Kotlin/kotlin-frontend-plugin/blob/master/examples/frontend-only/build.gradle, except that I am using kotlin 1.2.51, and I added the dependencies and repo  for org.jetbrains:kotlin-react:16.4.1-pre.34-kotlin-1.2.51 and org.jetbrains:kotlin-react-dom:16.4.1-pre.34-kotlin-1.2.51 and org.jetbrains:kotlin-react-router-dom:4.2.2-pre.34-kotlin-1.2.51.

**Comment by Leonya** [comment]
@neworld can you help?

**Comment by turansky** [comment]
Not reproduced anymore

Also strict component type introduced in #505 

cc @Leonya
