### ISSUE TITLE
Console error after upgrading to 1.5.30 and `17.0.2-pre.241-kotlin-1.5.30`

### ISSUE THREAD

**Issue by blindpirate** [JetBrains/kotlin-wrappers#710]
### Context

With kotlin `1.5.21` and kotlin-react `17.0.2-pre.217-kotlin-1.5.21`, everything works fine.

After upgrading to kotlin `1.5.30` and `17.0.2-pre.241-kotlin-1.5.30`, there's an error in latest npm `react-bootstrap` `1.6.1`

![image](https://user-images.githubusercontent.com/12689835/132188183-7115e272-5e59-4eae-9edc-353c0da666ca.png)

```
validateModifiers.js?239d:36 Popper: modifier "popoverArrowMargins" provided an invalid "fn" property, expected "function" but got "undefined"
eval @ validateModifiers.js?239d:36
eval @ validateModifiers.js?239d:11
validateModifiers @ validateModifiers.js?239d:7
setOptions @ createPopper.js?232e:86
createPopper @ createPopper.js?232e:215
eval @ usePopper.js?2632:155
invokePassiveEffectCreate @ react-dom.development.js?f6e0:23487
callCallback @ react-dom.development.js?f6e0:3945
invokeGuardedCallbackDev @ react-dom.development.js?f6e0:3994
invokeGuardedCallback @ react-dom.development.js?f6e0:4056
flushPassiveEffectsImpl @ react-dom.development.js?f6e0:23574
unstable_runWithPriority @ scheduler.development.js?1ab3:468
runWithPriority$1 @ react-dom.development.js?f6e0:11276
flushPassiveEffects @ react-dom.development.js?f6e0:23447
eval @ react-dom.development.js?f6e0:23324
workLoop @ scheduler.development.js?1ab3:417
flushWork @ scheduler.development.js?1ab3:390
performWorkUntilDeadline @ scheduler.development.js?1ab3:157
```

### Steps to reproduce

- Clone `https://github.com/blindpirate/kotlin-react-popover-reproducer`
- Run `./gradlew browserDevelopmentRun`
- Click `ClickMe` button.

**Comment by jschneider** [comment]
I run into some kind of NullPointerException when upgrading to 0.0.1-pre.241-kotlin-1.5.30.
0.0.1-pre.240-kotlin-1.5.30 runs just fine.

The exception happends very early, it seems to maybe related to module loading? I can't exactly get an exact stack trace :-(

**Comment by turansky** [comment]
@blindpirate Does it work in combination Kotlin `1.5.21` + `pre.241`?
Additional config for check:
```
    val kotlinVersion = "1.5.21"

    configurations.all {
        resolutionStrategy {
            eachDependency {
                if (requested.group == "org.jetbrains.kotlin" && requested.name.startsWith("kotlin-"))
                    useVersion(kotlinVersion)
            }
        }
    }
```

**Comment by blindpirate** [comment]
@turansky there is no `pre.241-kotlin-1.5.21`, do you mean `pre.241-kotlin-1.5.30`?

I tried the following combinations, `pre.242` seems to fix this issue.

- `1.5.21` + `pre.241-1.5.30`  :white_check_mark:
- `1.5.30` + `pre.241-1.5.30`  :x:
- `1.5.30` + `pre.242-1.5.30`  :white_check_mark:

**Comment by turansky** [comment]
@blindpirate Kotlin downgrade is possible with configuration above
`1.5.21` + gradle configuration above + `pre.242-1.5.30`
