### ISSUE TITLE
How to write/export React HOC's on Kotlin/JS

### ISSUE THREAD

**Issue by Slava96** [JetBrains/kotlin-wrappers#747]
Hello!

I tried to work with react-i18next library and cannot understand how to export withTranslation HOC into KotlinJS code.
I need a working example with JS export and usage on Kotlin code (how we can wrap functional components and class components).
Also, if you can - give me information on how to create my own HOC's on Kotlin code.

**Comment by turansky** [comment]
@Slava96 Do you really need class components?

**Comment by Slava96** [comment]
Yes.
For react-i18next, I already have worked example with functionalComponent + hook (useTranslation)

**Comment by turansky** [comment]
Custom HOC example (same as in JS):
```kotlin
fun superPuperButton(button: FC<ButtonProps>): FC<SuperPuperButtonProps> =
    fc("SuperPuper_" + button.displayName) {
        div {
            +"Super Pupper"
            button()
        }
    }
```

**Comment by Slava96** [comment]
It's OK, but can we export existing JS hoc's from imported libraries?
For example, this - https://react.i18next.com/latest/withtranslation-hoc.

**Comment by turansky** [comment]
It's just function. No magic :)

**Comment by Slava96** [comment]
Can you provide me an example?
I understand that this is function - but how I can export it?

**Comment by turansky** [comment]
> For react-i18next, I already have worked example with functionalComponent + hook (useTranslation)

Like `useTranslation`

**Comment by sgrishchenko** [comment]
@Slava96 just use guides for interop with js
https://kotlinlang.org/docs/js-interop.html
