### ISSUE TITLE
jsBrowserDevelopmentWebpack break after Kotlin plugin version update

### ISSUE THREAD

**Issue by Slava96** [JetBrains/kotlin-wrappers#804]
I add kotlin-wrappers-bom to my Gradle build, then I updated Kotlin version to 1.5 because there is no kotlin-wrappers-bom for Kotlin 1.4.

After this changes, my jsBrowserDevelopmentWebpack Gradle task doesn't succeed with such error:
```[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
Execution failed for task ':jsBrowserDevelopmentWebpack'.
> [webpack-cli] Error: Unknown option '--env ENV=LOCAL'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

I run this task with --debug, and found a webpack command. When I try it, it succeed, but with 1 error.

```99% done plugins TeamCityErrorPlugin
##teamcity[message text='Module not found: Error: Can|'t resolve |'source-map-loader|' in |'C:\Users\parayar\IdeaProjects\tax-ui|'' type='error']
99% done plugins

100%
asset tax-ui.js 663 bytes [compared for emit] (name: main)
webpack 5.35.0 compiled with 1 error in 427 ms
```

Kotlin multiplatform plugin version - 1.5.10
Kotlin wrappers bom version - 0.0.1-pre.213-kotlin-1.5.10
Node version - 14.15.5

How can i run webpack with success?

**Comment by turansky** [comment]
> How can i run webpack with success?

For start you need latest versions of Kotlin and Kotlin Wrappers

**Comment by sgrishchenko** [comment]
@Slava96 Thank you for your report, but it seems main problem relates to tasks for node/webpack integration in Kotlin Gradle plugin. Unfortunately this is beyond our competence. Kotlin Wrappers project is the same user of these plugins as you :slightly_smiling_face:. Try to report this problem in their repo, please.

**Comment by Slava96** [comment]
Can you give me link to repo?

**Comment by turansky** [comment]
[Issue tracker](https://youtrack.jetbrains.com/issues/KT)
