### ISSUE TITLE
Material UI

### ISSUE THREAD

**Issue by Pitel** [JetBrains/kotlin-wrappers#851]
- [x] `LoadingButton` #848
- [x] Date/Time pickers from Lab #848
- [x] Theming (`Theme`, `useTheme()`, `ThemeProvider`, ...)
- [x] `useMediaQuery`, Breakpoint helpers
- [x] `ListItemText`
- [x] `onClick` on `Button`s
- [x] Weird `*TextFieldProps`
- [x] Some simple example(s) for README? #915
- [x] DSL #1000

**Comment by sgrishchenko** [comment]
@Pitel could you strike through DSL point in the list? We don't plan to support some special DSL for Material UI. Or you can describe your needs in DSL more concrete and we can discuss it in separate ticket.

**Comment by mysticfall** [comment]
Yes, I've been using it already in my project. And I managed to construct a fairly complex UI with it, using just the DSL other wrappers provide already. So, I think the library would be quite usable once we fill out missing parts without having to create any special DSL for it.

**Comment by turansky** [comment]
> You want to generate everything through `garagum/mui-kotlin`?

Yes, it's current plan

> Is there a place where one can find some additional info about your idea on the overall approach to mui wrapper?

`#react` and `#javascript` channels in Kotlin Slack

> but I wonder if the lack of specific DSL might less help you before actual app run

Do you special factory methods?

cc @aerialist7

**Comment by mysticfall** [comment]
Could you bump the version to 5.2.1? The current version used by the project has a [major problem](https://github.com/mui-org/material-ui/issues/29860), which was hotfixed in 5.2.1.

**Comment by turansky** [comment]
After `./gradlew clean` you will receive latest versions
`pre.272` will use latest MUI version

**Comment by mysticfall** [comment]
Yes, it certainly fixed the problem for me. I thought MUI version was tied to the wrapper as it still says v5.2.0 but apparently I was mistaken.

Thanks much for the help! :)

**Comment by turansky** [comment]
@Pitel, could you highlight if something from list missed in `pre.286`?

**Comment by Pitel** [comment]
@turansky Sorry, I can't. I no longer work on React Kotlin project, I got back to Android. So if you consider this as ticket for me, feel free to close it, because I'm no longer interested. But I may return to Kotlin React in a few months, so it's up to you.
