### ISSUE TITLE
Using HTML Entities with React

### ISSUE THREAD

**Issue by piacenti** [JetBrains/kotlin-wrappers#90]
I've tried using simple HTML entities with code such as attrs { entity(Entities.times) } or +Entities.times.text inside an RTBuilder context but it always seem to escape the characters and print the raw entity code such as  &times;

What is the right way to use them in the RTBuilder context?

**Comment by Leonya** [comment]
You can do it like this:

```
fun RBuilder.unsafeHTML(html: String) {
    div {
        attrs.unsafe { +html }
    }
}
```
