### ISSUE TITLE
CSS wrapper for JS doesn't see kotlin module

### ISSUE THREAD

**Issue by aviadmini** [JetBrains/kotlin-wrappers#93]
Adding any code that references _kotlin-css-js_ results in the following error:
`Error loading module 'kotlin-css-js'. Its dependency 'kotlin' was not found. Please, check whether 'kotlin' is loaded prior to 'kotlin-css-js'`

I've found a few people having similar issue with their modules, mostly they got it fixed by adding `compileKotlin2Js.kotlinOptions.moduleKind = 'commonjs'` to their build.gradle. But in this case it is _kotlin-css-js_ which is probably 

Also tried to rollback versions but rest of 1.3 ones produced `Cannot read property 'call' of undefined` in _kotlinext_

Also curious whether it's by design that on bintray there's no  _pre-61_ version of _kotlin-css_ (only _pre-60_)

**Comment by gbaldeck** [comment]
Are you using webpack as a module loader? If so create a module alias to the kotlin.js file that is output by the kotlin2js compiler. Then it will resolve that file as the module. Here's the documentation for using an alias: https://webpack.js.org/configuration/resolve/

**Comment by aviadmini** [comment]
Thanks, will check it ou rn.

I'm using _kotlin-frontend-plugin_ which internally uses webpack.

**Comment by aviadmini** [comment]
Since I'm using the _kotlin-frontend-plugin_ the only way I know of editing the webpack config is by adding additional files contents of which are then appended to the end of _webpack.config.d_

So I created this:
```js
var path = require('path');
config.resolve.alias = {kotlin$: path.resolve(__dirname, "node_modules/kotlin/kotlin.js")};
```
Webpack seems to process it (no errors)
However, even after it I'm getting the same error:
`Error loading module 'kotlin-css-js'. Its dependency 'kotlin' was not found. Please, check whether 'kotlin' is loaded prior to 'kotlin-css-js'`

I also added a simple log at beginning of files to check that _kotlin.js_ is loaded before _kotlin-css-js.js_ (don't blame me for medeival methods) - and this is confirmed to be true

I'll gladly provide more info if needed

**Comment by aviadmini** [comment]
This only happens to latest version (60-61). 
The `pre-59` version works just fine, even without adding a module alias to webpack

**Comment by Danilo-Araujo-Silva** [comment]
Using `build.gradle.kts` and having a module called `common` and one other one called `reactApp`, I was able to solve this problem adding the following configuration in both `build.gradle.kts` configuration files:

```
js("js") {
        configure(listOf(compilations["main"], compilations["test"])) {
            tasks.getByName(compileKotlinTaskName) {
                kotlinOptions {
                    //                    languageVersion = "1.3"
                    metaInfo = true
//                    outputFile = "${project.buildDir.path}/js/${project.name}.js"
                    sourceMap = true
                    sourceMapEmbedSources = "always"
                    moduleKind = "umd"
                }
            }
        }

        configure(listOf(compilations["main"])) {
            tasks.getByName(compileKotlinTaskName) {
                kotlinOptions {
                    main = "call"
                }
            }
        }
    }
```
