### ISSUE TITLE
[kotlin-styled] Support styled-components v4

### ISSUE THREAD

**Issue by null-dev** [JetBrains/kotlin-wrappers#95]
It looks like `styled-components` has changed the way they require animations to be specified. I get the following now when I try to run an app containing an element with an animation:

```
Error: It seems you are interpolating a keyframe declaration (jrktBO) into an untagged string.
This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand.
Please wrap your string in the css\`\` helper (see https://www.styled-components.com/docs/api#css), which ensures the styles are injected correctly.
```

**Comment by Leonya** [comment]
kotlin-styled doesn't support styled-components v4 yet.

**Comment by Leonya** [comment]
I have added a notice to the documentation (9eb86a7afb61e957ea4bbe3008580a00036b0214), everyone is welcome to submit a PR adding styled-components@4 support.

**Comment by Leonya** [comment]
Done as of `pre.82`, many thanks to @Skolotsky!
