### ISSUE TITLE
[kotlin-mui] Autocomplete is unusable

### ISSUE THREAD

**Issue by krzema12** [JetBrains/kotlin-wrappers#985]
Looks like its code was generated and placed in kotlin-mui, but in practice it's not possible to use. It's not possible to define options. See e.g. https://karakum-team.github.io/kotlin-mui-showcase/

It's a show-stopper for migrating an internal service in my company to React & Kotlin/JS.

**Comment by krzema12** [comment]
In Muirwik (manually maintained wrappers on MUI), there's a working Autocomplete: 
* source: https://github.com/cfnz/muirwik/blob/6c831c51127648f2b8ddb65af7f2482a3bc9a115/muirwik-components/src/main/kotlin/com/ccfraser/muirwik/components/lab/AutoComplete.kt. There's `var options: Array<T>`.

**Comment by krzema12** [comment]
https://user-images.githubusercontent.com/3110813/143844487-236d3abf-e88f-423c-bb1c-37f8e0ea4868.mp4

**Comment by krzema12** [comment]
I'm looking for a workaround.

Following @turansky's advice, I defined

```kotlin
inline var AutocompleteProps<*>.options: Array<String>
    get() = asDynamic()["options"]
    set(value) {
        asDynamic()["options"] = value
    }
```

and then
```kotlin
Autocomplete {
    attrs {
        options = arrayOf("foo", "bar", "baz")
        disablePortal = true
        renderInput = {
            buildElement {
                TextField {
                    attrs {
                        @Suppress("UNCHECKED_CAST_TO_EXTERNAL_INTERFACE")
                        this as BaseTextFieldProps
                        label = ReactNode("Choose value")
                        variant = "outlined"
                    }
                }
            }
        }
        renderOption = { _, option, _ ->
            buildElement {
                Fragment {
                    +option.toString()
                }
            }
        }
    }
}
```

but it led me only to this point, where no options are listed and everything looks and works weird:

https://user-images.githubusercontent.com/3110813/144656128-89da7cfa-66de-4f52-adc5-021970d7a22b.mp4

When clicking most of component's area, I get this in the console:
![image](https://user-images.githubusercontent.com/3110813/144656101-8f8f9fb5-4c83-4fff-b641-c1e913d82343.png)

**Comment by turansky** [comment]
It looks like invalid render method implementation

**Comment by turansky** [comment]
[Works fine](https://github.com/karakum-team/mui-kotlin/blob/fc7958ec521e33820c383607fd105976c12df0e7/local-server/src/main/kotlin/MyAutocomplete.kt#L23) with valid `renderInput`

Also `options` can be strict (like in example)

**Comment by krzema12** [comment]
Thanks, displaying options works now.

Other crucial props that are missing are `onChange` and `value`. I added:
```kotlin
inline var <T : Any> AutocompleteProps<T>.value: T?
    get() = asDynamic().value
    set(value) {
        asDynamic().value = value
    }

var <T : Any> AutocompleteProps<T>.onChange: (event: dynamic, value: T?) -> Unit
    get() = asDynamic().onChange
    set(value) {
        asDynamic().onChange = value
    }
```
And it looks to be enough for my use case.

**Comment by krzema12** [comment]
Thank you!

**Comment by turansky** [comment]
And more compact in `pre.280` :)

<img width="1275" alt="Screenshot 2021-12-08 at 03 26 16" src="https://user-images.githubusercontent.com/9942723/145126659-6644a4a7-908d-4077-ad40-37521365a085.png">
