### ISSUE TITLE
[kotlin-mui] Icons are unusable

### ISSUE THREAD

**Issue by krzema12** [JetBrains/kotlin-wrappers#986]
I tried using them via the `Icon` API, but just the text was displayed. I had to use `SvgIcon` and hardcode the SVG path:

```
        SvgIcon {
            path {
                attrs.d = "M9 16.17 4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"
            }
        }
```

**Comment by turansky** [comment]
Not reproduced
[Test](https://github.com/karakum-team/mui-kotlin/blob/57e092e7d162acb4653d184255cf31b31c9b4793/local-server/src/main/kotlin/App.kt#L13)

Result:
<img width="47" alt="Screenshot 2021-11-27 at 03 42 55" src="https://user-images.githubusercontent.com/9942723/143662784-61b0f70b-3f58-4979-af2a-51d8ac176469.png">

**Comment by Leonya** [comment]
`SvgIcon` is not the desired API.

**Comment by turansky** [comment]
@krzema12 Which code doesn't work for `Icon`?

**Comment by krzema12** [comment]
I don't have my code at hand now, but please see https://mui.com/components/icons/. Looking at equivalent JS code, I'd like to use separate components for each icon

```js
import AccessAlarmIcon from '@mui/icons-material/AccessAlarm';
<AccessAlarmIcon/>
```

or, as last resort, font-based icons:

```js
import Icon from '@mui/material/Icon'; <Icon>star</Icon>;
```

**Comment by turansky** [comment]
Do you use IR or legacy?
