### ISSUE TITLE
Support react-router props

### ISSUE THREAD

**Issue by spand** [JetBrains/kotlin-wrappers#99]
React router also have props that can be passed to them.
The base router has history (https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Router.md)

Browser router has additional props: basename, forceRefresh, getUserConfirmation, keyLength (https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/BrowserRouter.md)

**Comment by Leonya** [comment]
Please make a PR.
